* [[https://leetcode.com/problems/relative-ranks][506. Relative Ranks]]
  :PROPERTIES:
  :CUSTOM_ID: relative-ranks
  :END:
[[./solution/0500-0599/0506.Relative Ranks/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

You are given an integer array score of size n, where score[i] is the
score of the ith athlete in a competition. All the scores are guaranteed
to be unique.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

The athletes are placed based on their scores, where the 1st place
athlete has the highest score, the 2nd place athlete has the 2nd highest
score, and so on. The placement of each athlete determines their rank:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

The 1st place athlete's rank is "Gold Medal".

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

The 2nd place athlete's rank is "Silver Medal".

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

The 3rd place athlete's rank is "Bronze Medal".

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

For the 4th place to the nth place athlete, their rank is their
placement number (i.e., the xth place athlete's rank is "x").

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

#+begin_html
  <p>
#+end_html

Return an array answer of size n where answer[i] is the rank of the ith
athlete.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> score = [5,4,3,2,1]
  <strong>Output:</strong> [&quot;Gold Medal&quot;,&quot;Silver Medal&quot;,&quot;Bronze Medal&quot;,&quot;4&quot;,&quot;5&quot;]
  <strong>Explanation:</strong> The placements are [1<sup>st</sup>, 2<sup>nd</sup>, 3<sup>rd</sup>, 4<sup>th</sup>, 5<sup>th</sup>].</pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> score = [10,3,8,9,4]
  <strong>Output:</strong> [&quot;Gold Medal&quot;,&quot;5&quot;,&quot;Bronze Medal&quot;,&quot;Silver Medal&quot;,&quot;4&quot;]
  <strong>Explanation:</strong> The placements are [1<sup>st</sup>, 5<sup>th</sup>, 3<sup>rd</sup>, 2<sup>nd</sup>, 4<sup>th</sup>].

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

n == score.length

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= n <= 104

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= score[i] <= 106

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

All the values in score are unique.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
