* [[https://leetcode.com/problems/maximize-number-of-nice-divisors][1808.
Maximize Number of Nice Divisors]]
  :PROPERTIES:
  :CUSTOM_ID: maximize-number-of-nice-divisors
  :END:
[[./solution/1800-1899/1808.Maximize Number of Nice Divisors/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

You are given a positive integer primeFactors. You are asked to
construct a positive integer n that satisfies the following conditions:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

The number of prime factors of n (not necessarily distinct) is at most
primeFactors.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

The number of nice divisors of n is maximized. Note that a divisor of n
is nice if it is divisible by every prime factor of n. For example, if n
= 12, then its prime factors are [2,2,3], then 6 and 12 are nice
divisors, while 3 and 4 are not.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

#+begin_html
  <p>
#+end_html

Return the number of nice divisors of n. Since that number can be too
large, return it modulo 109 + 7.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Note that a prime number is a natural number greater than 1 that is not
a product of two smaller natural numbers. The prime factors of a number
n is a list of prime numbers such that their product equals n.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> primeFactors = 5

  <strong>Output:</strong> 6

  <strong>Explanation:</strong> 200 is a valid value of n.

  It has 5 prime factors: [2,2,2,5,5], and it has 6 nice divisors: [10,20,40,50,100,200].

  There is not other value of n that has at most 5 prime factors and more nice divisors.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> primeFactors = 8

  <strong>Output:</strong> 18

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= primeFactors <= 109

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
