* [[https://leetcode.com/problems/cherry-pickup-ii][1463. Cherry Pickup
II]]
  :PROPERTIES:
  :CUSTOM_ID: cherry-pickup-ii
  :END:
[[./solution/1400-1499/1463.Cherry Pickup II/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Given a rows x cols matrix grid representing a field of cherries. Each
cell in grid represents the number of cherries that you can collect.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

You have two robots that can collect cherries for you, Robot #1 is
located at the top-left corner (0,0) , and Robot #2 is located at the
top-right corner (0, cols-1) of the grid.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the maximum number of cherries collection using both robots  by
following the rules below:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

From a cell (i,j), robots can move to cell (i+1, j-1) , (i+1, j) or
(i+1, j+1).

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

When any robot is passing through a cell, It picks it up all cherries,
and the cell becomes an empty cell (0).

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

When both robots stay on the same cell, only one of them takes the
cherries.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Both robots cannot move outside of the grid at any moment.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Both robots should reach the bottom row in the grid.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> grid = [[3,1,1],[2,5,1],[1,5,5],[2,1,1]]
  <strong>Output:</strong> 24
  <strong>Explanation:</strong>&nbsp;Path of robot #1 and #2 are described in color green and blue respectively.
  Cherries taken by Robot #1, (3 + 2 + 5 + 2) = 12.
  Cherries taken by Robot #2, (1 + 5 + 5 + 1) = 12.
  Total of cherries: 12 + 12 = 24.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> grid = [[1,0,0,0,0,0,1],[2,0,0,0,0,3,0],[2,0,9,0,0,0,0],[0,3,0,5,4,0,0],[1,0,2,3,0,0,6]]
  <strong>Output:</strong> 28
  <strong>Explanation:</strong>&nbsp;Path of robot #1 and #2 are described in color green and blue respectively.
  Cherries taken by Robot #1, (1 + 9 + 5 + 2) = 17.
  Cherries taken by Robot #2, (1 + 3 + 4 + 3) = 11.
  Total of cherries: 17 + 11 = 28.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> grid = [[1,0,0,3],[0,0,0,3],[0,0,3,3],[9,0,3,3]]
  <strong>Output:</strong> 22
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 4:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> grid = [[1,1],[1,1]]
  <strong>Output:</strong> 4
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

rows == grid.length

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

cols == grid[i].length

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

2 <= rows, cols <= 70

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= grid[i][j] <= 100 

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
