* [[https://leetcode.com/problems/kids-with-the-greatest-number-of-candies][1431.
Kids With the Greatest Number of Candies]]
  :PROPERTIES:
  :CUSTOM_ID: kids-with-the-greatest-number-of-candies
  :END:
[[./solution/1400-1499/1431.Kids With the Greatest Number of Candies/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Given the array candies and the integer extraCandies, where candies[i]
represents the number of candies that the ith kid has.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

For each kid check if there is a way to distribute extraCandies among
the kids such that he or she can have the greatest number of candies
among them. Notice that multiple kids can have the greatest number of
candies.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> candies = [2,3,5,1,3], extraCandies = 3

  <strong>Output:</strong> [true,true,true,false,true] 

  <strong>Explanation:</strong> 

  Kid 1 has 2 candies and if he or she receives all extra candies (3) will have 5 candies --- the greatest number of candies among the kids. 

  Kid 2 has 3 candies and if he or she receives at least 2 extra candies will have the greatest number of candies among the kids. 

  Kid 3 has 5 candies and this is already the greatest number of candies among the kids. 

  Kid 4 has 1 candy and even if he or she receives all extra candies will only have 4 candies. 

  Kid 5 has 3 candies and if he or she receives at least 2 extra candies will have the greatest number of candies among the kids. 

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> candies = [4,2,1,1,2], extraCandies = 1

  <strong>Output:</strong> [true,false,false,false,false] 

  <strong>Explanation:</strong> There is only 1 extra candy, therefore only kid 1 will have the greatest number of candies among the kids regardless of who takes the extra candy.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> candies = [12,1,12], extraCandies = 10

  <strong>Output:</strong> [true,false,true]

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

2 <= candies.length <= 100

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= candies[i] <= 100

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= extraCandies <= 50

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
