* [[https://leetcode.com/problems/number-of-sets-of-k-non-overlapping-line-segments][1621.
Number of Sets of K Non-Overlapping Line Segments]]
  :PROPERTIES:
  :CUSTOM_ID: number-of-sets-of-k-non-overlapping-line-segments
  :END:
[[./solution/1600-1699/1621.Number of Sets of K Non-Overlapping Line Segments/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Given n points on a 1-D plane, where the ith point (from 0 to n-1) is at
x = i, find the number of ways we can draw exactly k non-overlapping
line segments such that each segment covers two or more points. The
endpoints of each segment must have integral coordinates. The k line
segments do not have to cover all n points, and they are allowed to
share endpoints.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the number of ways we can draw k non-overlapping line
segments. Since this number can be huge, return it modulo 109 + 7.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> n = 4, k = 2

  <strong>Output:</strong> 5

  <strong>Explanation: 

  </strong>The two line segments are shown in red and blue.

  The image above shows the 5 different ways {(0,2),(2,3)}, {(0,1),(1,3)}, {(0,1),(2,3)}, {(1,2),(2,3)}, {(0,1),(1,2)}.</pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> n = 3, k = 1

  <strong>Output:</strong> 3

  <strong>Explanation: </strong>The 3 ways are {(0,1)}, {(0,2)}, {(1,2)}.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> n = 30, k = 7

  <strong>Output:</strong> 796297179

  <strong>Explanation: </strong>The total number of possible ways to draw 7 line segments is 3796297200. Taking this number modulo 10<sup>9</sup> + 7 gives us 796297179.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 4:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> n = 5, k = 3

  <strong>Output:</strong> 7

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 5:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> n = 3, k = 2

  <strong>Output:</strong> 1</pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

2 <= n <= 1000

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= k <= n-1

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
