* [[https://leetcode.com/problems/ways-to-make-a-fair-array][1664. Ways
to Make a Fair Array]]
  :PROPERTIES:
  :CUSTOM_ID: ways-to-make-a-fair-array
  :END:
[[./solution/1600-1699/1664.Ways to Make a Fair Array/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

You are given an integer array nums. You can choose exactly one index
(0-indexed) and remove the element. Notice that the index of the
elements may change after the removal.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

For example, if nums = [6,1,7,4,1]:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

Choosing to remove index 1 results in nums = [6,7,4,1].

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Choosing to remove index 2 results in nums = [6,1,4,1].

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Choosing to remove index 4 results in nums = [6,1,7,4].

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

#+begin_html
  <p>
#+end_html

An array is fair if the sum of the odd-indexed values equals the sum of
the even-indexed values.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the number of indices that you could choose such that after the
removal, nums is fair.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> nums = [2,1,6,4]
  <strong>Output:</strong> 1
  <strong>Explanation:</strong>
  Remove index 0: [1,6,4] -&gt; Even sum: 1 + 4 = 5. Odd sum: 6. Not fair.
  Remove index 1: [2,6,4] -&gt; Even sum: 2 + 4 = 6. Odd sum: 6. Fair.
  Remove index 2: [2,1,4] -&gt; Even sum: 2 + 4 = 6. Odd sum: 1. Not fair.
  Remove index 3: [2,1,6] -&gt; Even sum: 2 + 6 = 8. Odd sum: 1. Not fair.
  There is 1 index that you can remove to make nums fair.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> nums = [1,1,1]
  <strong>Output:</strong> 3
  <strong>Explanation:</strong>&nbsp;You can remove any index and the remaining array is fair.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> nums = [1,2,3]
  <strong>Output:</strong> 0
  <strong>Explanation:</strong>&nbsp;You cannot make a fair array after removing any index.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= nums.length <= 105

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= nums[i] <= 104

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
