* [[https://leetcode.com/problems/super-washing-machines][517. Super
Washing Machines]]
  :PROPERTIES:
  :CUSTOM_ID: super-washing-machines
  :END:
[[./solution/0500-0599/0517.Super Washing Machines/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

You have n super washing machines on a line. Initially, each washing
machine has some dresses or is empty.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

For each move, you could choose any m (1 ≤ m ≤ n) washing machines, and
pass one dress of each washing machine to one of its adjacent washing
machines at the same time .

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Given an integer array representing the number of dresses in each
washing machine from left to right on the line, you should find the
minimum number of moves to make all the washing machines have the same
number of dresses. If it is not possible to do it, return -1.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example1

#+begin_html
  <pre>

  <b>Input:</b> [1,0,5]



  <b>Output:</b> 3



  <b>Explanation:</b> 

  1st move:    1     0 <-- 5    =>    1     1     4

  2nd move:    1 <-- 1 <-- 4    =>    2     1     3    

  3rd move:    2     1 <-- 3    =>    2     2     2   

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example2

#+begin_html
  <pre>

  <b>Input:</b> [0,3,0]



  <b>Output:</b> 2



  <b>Explanation:</b> 

  1st move:    0 <-- 3     0    =>    1     2     0    

  2nd move:    1     2 --> 0    =>    1     1     1     

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example3

#+begin_html
  <pre>

  <b>Input:</b> [0,2,0]



  <b>Output:</b> -1



  <b>Explanation:</b> 

  It's impossible to make all the three washing machines have the same number of dresses. 

  </pre>
#+end_html

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Note:

#+begin_html
  <ol>
#+end_html

#+begin_html
  <li>
#+end_html

The range of n is [1, 10000].

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

The range of dresses number in a super washing machine is [0, 1e5].

#+begin_html
  </li>
#+end_html

#+begin_html
  </ol>
#+end_html

#+begin_html
  </p>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
