* [[https://leetcode.com/problems/unique-email-addresses][929. Unique
Email Addresses]]
  :PROPERTIES:
  :CUSTOM_ID: unique-email-addresses
  :END:
[[./solution/0900-0999/0929.Unique Email Addresses/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Every valid email consists of a local name and a domain name, separated
by the '@' sign. Besides lowercase letters, the email may contain one or
more '.' or '+'.

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

For example, in "alice@leetcode.com", "alice" is the local name, and
"leetcode.com" is the domain name.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

#+begin_html
  <p>
#+end_html

If you add periods '.' between some characters in the local name part of
an email address, mail sent there will be forwarded to the same address
without dots in the local name. Note that this rule does not apply to
domain names.

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

For example, "alice.z@leetcode.com" and "alicez@leetcode.com" forward to
the same email address.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

#+begin_html
  <p>
#+end_html

If you add a plus '+' in the local name, everything after the first plus
sign will be ignored. This allows certain emails to be filtered. Note
that this rule does not apply to domain names.

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

For example, "m.y+name@email.com" will be forwarded to "my@email.com".

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

#+begin_html
  <p>
#+end_html

It is possible to use both of these rules at the same time.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Given an array of strings emails where we send one email to each
email[i], return the number of different addresses that actually receive
mails.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> emails = [&quot;test.email+alex@leetcode.com&quot;,&quot;test.e.mail+bob.cathy@leetcode.com&quot;,&quot;testemail+david@lee.tcode.com&quot;]
  <strong>Output:</strong> 2
  <strong>Explanation:</strong> &quot;testemail@leetcode.com&quot; and &quot;testemail@lee.tcode.com&quot; actually receive mails.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> emails = [&quot;a@leetcode.com&quot;,&quot;b@leetcode.com&quot;,&quot;c@leetcode.com&quot;]
  <strong>Output:</strong> 3
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= emails.length <= 100

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= emails[i].length <= 100

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

email[i] consist of lowercase English letters, '+', '.' and '@'.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Each emails[i] contains exactly one '@' character.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

All local and domain names are non-empty.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Local names do not start with a '+' character.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
