* [[https://leetcode.com/problems/closest-room][1847. Closest Room]]
  :PROPERTIES:
  :CUSTOM_ID: closest-room
  :END:
[[./solution/1800-1899/1847.Closest Room/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

There is a hotel with n rooms. The rooms are represented by a 2D integer
array rooms where rooms[i] = [roomIdi, sizei] denotes that there is a
room with room number roomIdi and size equal to sizei. Each roomIdi is
guaranteed to be unique.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

You are also given k queries in a 2D array queries where queries[j] =
[preferredj, minSizej]. The answer to the jth query is the room number
id of a room such that:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

The room has a size of at least minSizej, and

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

abs(id - preferredj) is minimized, where abs(x) is the absolute value of
x.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

#+begin_html
  <p>
#+end_html

If there is a tie in the absolute difference, then use the room with the
smallest such id. If there is no such room, the answer is -1.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return an array answer of length k where answer[j] contains the answer
to the jth query.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> rooms = [[2,2],[1,2],[3,2]], queries = [[3,1],[3,3],[5,2]]
  <strong>Output:</strong> [3,-1,3]
  <strong>Explanation: </strong>The answers to the queries are as follows:
  Query = [3,1]: Room number 3 is the closest as abs(3 - 3) = 0, and its size of 2 is at least 1. The answer is 3.
  Query = [3,3]: There are no rooms with a size of at least 3, so the answer is -1.
  Query = [5,2]: Room number 3 is the closest as abs(3 - 5) = 2, and its size of 2 is at least 2. The answer is 3.</pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> rooms = [[1,4],[2,3],[3,5],[4,1],[5,2]], queries = [[2,3],[2,4],[2,5]]
  <strong>Output:</strong> [2,1,3]
  <strong>Explanation: </strong>The answers to the queries are as follows:
  Query = [2,3]: Room number 2 is the closest as abs(2 - 2) = 0, and its size of 3 is at least 3. The answer is 2.
  Query = [2,4]: Room numbers 1 and 3 both have sizes of at least 4. The answer is 1 since it is smaller.
  Query = [2,5]: Room number 3 is the only room with a size of at least 5. The answer is 3.</pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

n == rooms.length

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= n <= 105

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

k == queries.length

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= k <= 104

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= roomIdi, preferredj <= 107

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= sizei, minSizej <= 107

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

 

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
