* [[https://leetcode.com/problems/find-the-winner-of-an-array-game][1535.
Find the Winner of an Array Game]]
  :PROPERTIES:
  :CUSTOM_ID: find-the-winner-of-an-array-game
  :END:
[[./solution/1500-1599/1535.Find the Winner of an Array Game/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Given an integer array arr of distinct integers and an integer k.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

A game will be played between the first two elements of the array
(i.e. arr[0] and arr[1]). In each round of the game, we compare arr[0]
with arr[1], the larger integer wins and remains at position 0 and the
smaller integer moves to the end of the array. The game ends when an
integer wins k consecutive rounds.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the integer which will win the game.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

It is guaranteed that there will be a winner of the game.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> arr = [2,1,3,5,4,6,7], k = 2

  <strong>Output:</strong> 5

  <strong>Explanation:</strong> Let&#39;s see the rounds of the game:

  Round |       arr       | winner | win_count

    1   | [2,1,3,5,4,6,7] | 2      | 1

    2   | [2,3,5,4,6,7,1] | 3      | 1

    3   | [3,5,4,6,7,1,2] | 5      | 1

    4   | [5,4,6,7,1,2,3] | 5      | 2

  So we can see that 4 rounds will be played and 5 is the winner because it wins 2 consecutive games.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> arr = [3,2,1], k = 10

  <strong>Output:</strong> 3

  <strong>Explanation:</strong> 3 will win the first 10 rounds consecutively.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> arr = [1,9,8,2,3,7,6,4,5], k = 7

  <strong>Output:</strong> 9

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 4:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> arr = [1,11,22,33,44,55,66,77,88,99], k = 1000000000

  <strong>Output:</strong> 99

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

2 <= arr.length <= 10^5

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= arr[i] <= 10^6

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

arr contains distinct integers.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= k <= 10^9

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
