* [[https://leetcode.com/problems/sell-diminishing-valued-colored-balls][1648.
Sell Diminishing-Valued Colored Balls]]
  :PROPERTIES:
  :CUSTOM_ID: sell-diminishing-valued-colored-balls
  :END:
[[./solution/1600-1699/1648.Sell Diminishing-Valued Colored Balls/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

You have an inventory of different colored balls, and there is a
customer that wants orders balls of any color.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

The customer weirdly values the colored balls. Each colored ball's value
is the number of balls of that color you currently have in your
inventory. For example, if you own 6 yellow balls, the customer would
pay 6 for the first yellow ball. After the transaction, there are only 5
yellow balls left, so the next yellow ball is then valued at 5 (i.e.,
the value of the balls decreases as you sell more to the customer).

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

You are given an integer array, inventory, where inventory[i] represents
the number of balls of the ith color that you initially own. You are
also given an integer orders, which represents the total number of balls
that the customer wants. You can sell the balls in any order.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the maximum total value that you can attain after selling orders
colored balls. As the answer may be too large, return it modulo 109 + 7.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> inventory = [2,5], orders = 4
  <strong>Output:</strong> 14
  <strong>Explanation:</strong> Sell the 1st color 1 time (2) and the 2nd color 3 times (5 + 4 + 3).
  The maximum total value is 2 + 5 + 4 + 3 = 14.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> inventory = [3,5], orders = 6
  <strong>Output:</strong> 19
  <strong>Explanation: </strong>Sell the 1st color 2 times (3 + 2) and the 2nd color 4 times (5 + 4 + 3 + 2).
  The maximum total value is 3 + 2 + 5 + 4 + 3 + 2 = 19.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> inventory = [2,8,4,10,6], orders = 20
  <strong>Output:</strong> 110
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 4:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> inventory = [1000000000], orders = 1000000000
  <strong>Output:</strong> 21
  <strong>Explanation: </strong>Sell the 1st color 1000000000 times for a total value of 500000000500000000. 500000000500000000 modulo 10<sup>9 </sup>+ 7 = 21.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= inventory.length <= 105

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= inventory[i] <= 109

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= orders <= min(sum(inventory[i]), 109)

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
