* [[https://leetcode.com/problems/satisfiability-of-equality-equations][990.
Satisfiability of Equality Equations]]
  :PROPERTIES:
  :CUSTOM_ID: satisfiability-of-equality-equations
  :END:
[[./solution/0900-0999/0990.Satisfiability of Equality Equations/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Given an array equations of strings that represent relationships between
variables, each string equations[i] has length 4 and takes one of two
different forms: "a==b" or "a!=b".  Here, a and b are lowercase letters
(not necessarily different) that represent one-letter variable names.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return true if and only if it is possible to assign integers to variable
names so as to satisfy all the given equations.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <ol>
#+end_html

#+begin_html
  </ol>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input: </strong><span id="example-input-1-1">[&quot;a==b&quot;,&quot;b!=a&quot;]</span>

  <strong>Output: </strong><span id="example-output-1">false</span>

  <strong>Explanation: </strong>If we assign say, a = 1 and b = 1, then the first equation is satisfied, but not the second.  There is no way to assign the variables to satisfy both equations.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input: </strong><span id="example-input-2-1">[&quot;b==a&quot;,&quot;a==b&quot;]</span>

  <strong>Output: </strong><span id="example-output-2">true</span>

  <strong>Explanation: </strong>We could assign a = 1 and b = 1 to satisfy both equations.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input: </strong><span id="example-input-3-1">[&quot;a==b&quot;,&quot;b==c&quot;,&quot;a==c&quot;]</span>

  <strong>Output: </strong><span id="example-output-3">true</span>

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 4:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input: </strong><span id="example-input-4-1">[&quot;a==b&quot;,&quot;b!=c&quot;,&quot;c==a&quot;]</span>

  <strong>Output: </strong><span id="example-output-4">false</span>

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 5:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input: </strong><span id="example-input-5-1">[&quot;c==c&quot;,&quot;b==d&quot;,&quot;x!=z&quot;]</span>

  <strong>Output: </strong><span id="example-output-5">true</span>

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Note:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ol>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= equations.length <= 500

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

equations[i].length == 4

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

equations[i][0] and equations[i][3] are lowercase letters

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

equations[i][1] is either '=' or '!'

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

equations[i][2] is '='

#+begin_html
  </li>
#+end_html

#+begin_html
  </ol>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
