* [[https://leetcode.com/problems/k-closest-points-to-origin][973. K
Closest Points to Origin]]
  :PROPERTIES:
  :CUSTOM_ID: k-closest-points-to-origin
  :END:
[[./solution/0900-0999/0973.K Closest Points to Origin/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Given an array of points where points[i] = [xi, yi] represents a point
on the X-Y plane and an integer k, return the k closest points to the
origin (0, 0).

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

The distance between two points on the X-Y plane is the Euclidean
distance (i.e., √(x1 - x2)2 + (y1 - y2)2).

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

You may return the answer in any order. The answer is guaranteed to be
unique (except for the order that it is in).

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> points = [[1,3],[-2,2]], k = 1
  <strong>Output:</strong> [[-2,2]]
  <strong>Explanation:</strong>
  The distance between (1, 3) and the origin is sqrt(10).
  The distance between (-2, 2) and the origin is sqrt(8).
  Since sqrt(8) &lt; sqrt(10), (-2, 2) is closer to the origin.
  We only want the closest k = 1 points from the origin, so the answer is just [[-2,2]].
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> points = [[3,3],[5,-1],[-2,4]], k = 2
  <strong>Output:</strong> [[3,3],[-2,4]]
  <strong>Explanation:</strong> The answer [[-2,4],[3,3]] would also be accepted.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= k <= points.length <= 104

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

-104 < xi, yi < 104

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
