* [[https://leetcode.com/problems/encode-string-with-shortest-length][471.
Encode String with Shortest Length]]
  :PROPERTIES:
  :CUSTOM_ID: encode-string-with-shortest-length
  :END:
[[./solution/0400-0499/0471.Encode String with Shortest Length/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Given a string s, encode the string such that its encoded length is the
shortest.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

The encoding rule is: k[encoded_string], where the encoded_string inside
the square brackets is being repeated exactly k times. k should be a
positive integer.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

If an encoding process does not make the string shorter, then do not
encode it. If there are several solutions, return any of them.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> s = &quot;aaa&quot;
  <strong>Output:</strong> &quot;aaa&quot;
  <strong>Explanation:</strong> There is no way to encode it such that it is shorter than the input string, so we do not encode it.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> s = &quot;aaaaa&quot;
  <strong>Output:</strong> &quot;5[a]&quot;
  <strong>Explanation:</strong> &quot;5[a]&quot; is shorter than &quot;aaaaa&quot; by 1 character.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> s = &quot;aaaaaaaaaa&quot;
  <strong>Output:</strong> &quot;10[a]&quot;
  <strong>Explanation:</strong> &quot;a9[a]&quot; or &quot;9[a]a&quot; are also valid solutions, both of them have the same length = 5, which is the same as &quot;10[a]&quot;.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 4:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> s = &quot;aabcaabcd&quot;
  <strong>Output:</strong> &quot;2[aabc]d&quot;
  <strong>Explanation:</strong> &quot;aabc&quot; occurs twice, so one answer can be &quot;2[aabc]d&quot;.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 5:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> s = &quot;abbbabbbcabbbabbbc&quot;
  <strong>Output:</strong> &quot;2[2[abbb]c]&quot;
  <strong>Explanation:</strong> &quot;abbbabbbc&quot; occurs twice, but &quot;abbbabbbc&quot; can also be encoded to &quot;2[abbb]c&quot;, so one answer can be &quot;2[2[abbb]c]&quot;.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= s.length <= 150

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

s consists of only lowercase English letters.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
