* [[https://leetcode.com/problems/magnetic-force-between-two-balls][1552.
Magnetic Force Between Two Balls]]
  :PROPERTIES:
  :CUSTOM_ID: magnetic-force-between-two-balls
  :END:
[[./solution/1500-1599/1552.Magnetic Force Between Two Balls/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

In universe Earth C-137, Rick discovered a special form of magnetic
force between two balls if they are put in his new invented basket. Rick
has n empty baskets, the ith basket is at position[i], Morty has m balls
and needs to distribute the balls into the baskets such that the
minimum magnetic force between any two balls is maximum.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Rick stated that magnetic force between two different balls at positions
x and y is |x - y|.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Given the integer array position and the integer m. Return the required
force.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> position = [1,2,3,4,7], m = 3
  <strong>Output:</strong> 3
  <strong>Explanation:</strong> Distributing the 3 balls into baskets 1, 4 and 7 will make the magnetic force between ball pairs [3, 3, 6]. The minimum magnetic force is 3. We cannot achieve a larger minimum magnetic force than 3.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> position = [5,4,3,2,1,1000000000], m = 2
  <strong>Output:</strong> 999999999
  <strong>Explanation:</strong> We can use baskets 1 and 1000000000.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

n == position.length

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

2 <= n <= 10^5

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= position[i] <= 10^9

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

All integers in position are distinct.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

2 <= m <= position.length

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
