* [[https://leetcode.com/problems/count-good-meals][1711. Count Good
Meals]]
  :PROPERTIES:
  :CUSTOM_ID: count-good-meals
  :END:
[[./solution/1700-1799/1711.Count Good Meals/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

A good meal is a meal that contains exactly two different food items
with a sum of deliciousness equal to a power of two.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

You can pick any two different foods to make a good meal.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Given an array of integers deliciousness where deliciousness[i] is the
deliciousness of the i​​​​​​th​​​​​​​​ item of food, return the number
of different good meals you can make from this list modulo 109 + 7.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Note that items with different indices are considered different even if
they have the same deliciousness value.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> deliciousness = [1,3,5,7,9]
  <strong>Output:</strong> 4
  <strong>Explanation: </strong>The good meals are (1,3), (1,7), (3,5) and, (7,9).
  Their respective sums are 4, 8, 8, and 16, all of which are powers of 2.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> deliciousness = [1,1,1,3,3,3,7]
  <strong>Output:</strong> 15
  <strong>Explanation: </strong>The good meals are (1,1) with 3 ways, (1,3) with 9 ways, and (1,7) with 3 ways.</pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= deliciousness.length <= 105

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= deliciousness[i] <= 220

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
