* [[https://leetcode.com/problems/count-ways-to-distribute-candies][1692.
Count Ways to Distribute Candies]]
  :PROPERTIES:
  :CUSTOM_ID: count-ways-to-distribute-candies
  :END:
[[./solution/1600-1699/1692.Count Ways to Distribute Candies/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

There are n unique candies (labeled 1 through n) and k bags. You are
asked to distribute all the candies into the bags such that every bag
has at least one candy.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

There can be multiple ways to distribute the candies. Two ways are
considered different if the candies in one bag in the first way are not
all in the same bag in the second way. The order of the bags and the
order of the candies within each bag do not matter.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

For example, (1), (2,3) and (2), (1,3) are considered different because
candies 2 and 3 in the bag (2,3) in the first way are not in the same
bag in the second way (they are split between the bags (2) and (1,3)).
However, (1), (2,3) and (3,2), (1) are considered the same because the
candies in each bag are all in the same bags in both ways.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Given two integers, n and k, return the number of different ways to
distribute the candies. As the answer may be too large, return it modulo
109 + 7.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> n = 3, k = 2
  <strong>Output:</strong> 3
  <strong>Explanation:</strong> You can distribute 3 candies into 2 bags in 3 ways:
  (1), (2,3)
  (1,2), (3)
  (1,3), (2)
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> n = 4, k = 2
  <strong>Output:</strong> 7
  <strong>Explanation:</strong> You can distribute 4 candies into 2 bags in 7 ways:
  (1), (2,3,4)
  (1,2), (3,4)
  (1,3), (2,4)
  (1,4), (2,3)
  (1,2,3), (4)
  (1,2,4), (3)
  (1,3,4), (2)
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> n = 20, k = 5
  <strong>Output:</strong> 206085257
  <strong>Explanation:</strong> You can distribute 20 candies into 5 bags in 1881780996 ways. 1881780996 modulo 10<sup>9</sup> + 7 = 206085257.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= k <= n <= 1000

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
