* [[https://leetcode.com/problems/house-robber-iii][337. House Robber
III]]
  :PROPERTIES:
  :CUSTOM_ID: house-robber-iii
  :END:
[[./solution/0300-0399/0337.House Robber III/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

The thief has found himself a new place for his thievery again. There is
only one entrance to this area, called root.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Besides the root, each house has one and only one parent house. After a
tour, the smart thief realized that all houses in this place form a
binary tree. It will automatically contact the police if two
directly-linked houses were broken into on the same night.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Given the root of the binary tree, return the maximum amount of money
the thief can rob without alerting the police.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> root = [3,2,3,null,3,null,1]
  <strong>Output:</strong> 7
  <strong>Explanation:</strong> Maximum amount of money the thief can rob = 3 + 3 + 1 = 7.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> root = [3,4,5,1,3,null,1]
  <strong>Output:</strong> 9
  <strong>Explanation:</strong> Maximum amount of money the thief can rob = 4 + 5 = 9.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

The number of nodes in the tree is in the range [1, 104].

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= Node.val <= 104

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
