* [[https://leetcode.com/problems/escape-the-ghosts][789. Escape The
Ghosts]]
  :PROPERTIES:
  :CUSTOM_ID: escape-the-ghosts
  :END:
[[./solution/0700-0799/0789.Escape The Ghosts/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

You are playing a simplified PAC-MAN game on an infinite 2-D grid. You
start at the point [0, 0], and you are given a destination point target
= [xtarget, ytarget], which you are trying to get to. There are several
ghosts on the map with their starting positions given as an array
ghosts, where ghosts[i] = [xi, yi] represents the starting position of
the ith ghost. All inputs are integral coordinates.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Each turn, you and all the ghosts may independently choose to either
move 1 unit in any of the four cardinal directions: north, east, south,
or west or stay still. All actions happen simultaneously.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

You escape if and only if you can reach the target before any ghost
reaches you. If you reach any square (including the target) at the same
time as a ghost, it does not count as an escape.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return true if it is possible to escape, otherwise return false.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> ghosts = [[1,0],[0,3]], target = [0,1]
  <strong>Output:</strong> true
  <strong>Explanation:</strong> You can reach the destination (0, 1) after 1 turn, while the ghosts located at (1, 0) and (0, 3) cannot catch up with you.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> ghosts = [[1,0]], target = [2,0]
  <strong>Output:</strong> false
  <strong>Explanation:</strong> You need to reach the destination (2, 0), but the ghost at (1, 0) lies between you and the destination.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> ghosts = [[2,0]], target = [1,0]
  <strong>Output:</strong> false
  <strong>Explanation:</strong> The ghost can reach the target at the same time as you.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 4:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> ghosts = [[5,0],[-10,-2],[0,-5],[-2,-2],[-7,1]], target = [7,7]
  <strong>Output:</strong> false
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 5:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> ghosts = [[-1,0],[0,1],[-1,0],[0,1],[-1,0]], target = [0,0]
  <strong>Output:</strong> true
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= ghosts.length <= 100

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

ghosts[i].length == 2

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

-104 <= xi, yi <= 104

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

There can be multiple ghosts in the same location.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

target.length == 2

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

-104 <= xtarget, ytarget <= 104

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
