* [[https://leetcode.com/problems/can-make-palindrome-from-substring][1177.
Can Make Palindrome from Substring]]
  :PROPERTIES:
  :CUSTOM_ID: can-make-palindrome-from-substring
  :END:
[[./solution/1100-1199/1177.Can Make Palindrome from Substring/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Given a string s, we make queries on substrings of s.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

For each query queries[i] = [left, right, k], we may rearrange the
substring s[left], ..., s[right], and then choose up to k of them to
replace with any lowercase English letter. 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

If the substring is possible to be a palindrome string after the
operations above, the result of the query is true. Otherwise, the
result is false.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return an array answer[], where answer[i] is the result of the i-th
query queries[i].

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Note that: Each letter is counted individually for replacement so if for
example s[left..right] = "aaa", and k = 2, we can only replace two of
the letters.  (Also, note that the initial string s is never modified by
any query.)

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example :

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> s = &quot;abcda&quot;, queries = [[3,3,0],[1,2,0],[0,3,1],[0,3,2],[0,4,1]]
  <strong>Output:</strong> [true,false,false,true,true]
  <strong>Explanation:</strong>
  queries[0] : substring = &quot;d&quot;, is palidrome.
  queries[1] :&nbsp;substring = &quot;bc&quot;, is not palidrome.
  queries[2] :&nbsp;substring = &quot;abcd&quot;, is not palidrome after replacing only 1 character.
  queries[3] :&nbsp;substring = &quot;abcd&quot;, could be changed to &quot;abba&quot; which is palidrome. Also this can be changed to &quot;baab&quot; first rearrange it &quot;bacd&quot; then replace &quot;cd&quot; with &quot;ab&quot;.
  queries[4] :&nbsp;substring = &quot;abcda&quot;,&nbsp;could be changed to &quot;abcba&quot; which is palidrome.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= s.length, queries.length <= 10^5

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= queries[i][0] <= queries[i][1] < s.length

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= queries[i][2] <= s.length

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

s only contains lowercase English letters.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
