* [[https://leetcode.com/problems/maximum-number-of-balls-in-a-box][1742.
Maximum Number of Balls in a Box]]
  :PROPERTIES:
  :CUSTOM_ID: maximum-number-of-balls-in-a-box
  :END:
[[./solution/1700-1799/1742.Maximum Number of Balls in a Box/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

You are working in a ball factory where you have n balls numbered from
lowLimit up to highLimit inclusive (i.e., n == highLimit - lowLimit +
1), and an infinite number of boxes numbered from 1 to infinity.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Your job at this factory is to put each ball in the box with a number
equal to the sum of digits of the ball's number. For example, the ball
number 321 will be put in the box number 3 + 2 + 1 = 6 and the ball
number 10 will be put in the box number 1 + 0 = 1.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Given two integers lowLimit and highLimit, return the number of balls in
the box with the most balls.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> lowLimit = 1, highLimit = 10
  <strong>Output:</strong> 2
  <strong>Explanation:</strong>
  Box Number:  1 2 3 4 5 6 7 8 9 10 11 ...
  Ball Count:  2 1 1 1 1 1 1 1 1 0  0  ...
  Box 1 has the most number of balls with 2 balls.</pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> lowLimit = 5, highLimit = 15
  <strong>Output:</strong> 2
  <strong>Explanation:</strong>
  Box Number:  1 2 3 4 5 6 7 8 9 10 11 ...
  Ball Count:  1 1 1 1 2 2 1 1 1 0  0  ...
  Boxes 5 and 6 have the most number of balls with 2 balls in each.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> lowLimit = 19, highLimit = 28
  <strong>Output:</strong> 2
  <strong>Explanation:</strong>
  Box Number:  1 2 3 4 5 6 7 8 9 10 11 12 ...
  Ball Count:  0 1 1 1 1 1 1 1 1 2  0  0  ...
  Box 10 has the most number of balls with 2 balls.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= lowLimit <= highLimit <= 105

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
