* [[https://leetcode.com/problems/height-checker][1051. Height Checker]]
  :PROPERTIES:
  :CUSTOM_ID: height-checker
  :END:
[[./solution/1000-1099/1051.Height Checker/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

A school is trying to take an annual photo of all the students. The
students are asked to stand in a single file line in non-decreasing
order by height. Let this ordering be represented by the integer array
expected where expected[i] is the expected height of the ith student in
line.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

You are given an integer array heights representing the current order
that the students are standing in. Each heights[i] is the height of the
ith student in line (0-indexed).

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the number of indices where heights[i] != expected[i].

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> heights = [1,1,4,2,1,3]
  <strong>Output:</strong> 3
  <strong>Explanation:</strong> 
  heights:  [1,1,<u>4</u>,2,<u>1</u>,<u>3</u>]
  expected: [1,1,<u>1</u>,2,<u>3</u>,<u>4</u>]
  Indices 2, 4, and 5 do not match.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> heights = [5,1,2,3,4]
  <strong>Output:</strong> 5
  <strong>Explanation:</strong>
  heights:  [<u>5</u>,<u>1</u>,<u>2</u>,<u>3</u>,<u>4</u>]
  expected: [<u>1</u>,<u>2</u>,<u>3</u>,<u>4</u>,<u>5</u>]
  All indices do not match.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> heights = [1,2,3,4,5]
  <strong>Output:</strong> 0
  <strong>Explanation:</strong>
  heights:  [1,2,3,4,5]
  expected: [1,2,3,4,5]
  All indices match.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= heights.length <= 100

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= heights[i] <= 100

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
