* [[https://leetcode.com/problems/minimum-number-of-refueling-stops][871.
Minimum Number of Refueling Stops]]
  :PROPERTIES:
  :CUSTOM_ID: minimum-number-of-refueling-stops
  :END:
[[./solution/0800-0899/0871.Minimum Number of Refueling Stops/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

A car travels from a starting position to a destination which is target
miles east of the starting position.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Along the way, there are gas stations.  Each station[i] represents a gas
station that is station[i][0] miles east of the starting position, and
has station[i][1] liters of gas.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

The car starts with an infinite tank of gas, which initially
has startFuel liters of fuel in it.  It uses 1 liter of gas per 1 mile
that it drives.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

When the car reaches a gas station, it may stop and refuel, transferring
all the gas from the station into the car.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

What is the least number of refueling stops the car must make in order
to reach its destination?  If it cannot reach the destination, return
-1.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Note that if the car reaches a gas station with 0 fuel left, the car can
still refuel there.  If the car reaches the destination with 0 fuel
left, it is still considered to have arrived.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input: </strong>target = <span id="example-input-1-1">1</span>, startFuel = <span id="example-input-1-2">1</span>, stations = <span id="example-input-1-3">[]</span>

  <strong>Output: </strong><span id="example-output-1">0</span>

  <strong>Explanation: </strong>We can reach the target without refueling.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input: </strong>target = <span id="example-input-2-1">100</span>, startFuel = <span id="example-input-2-2">1</span>, stations = <span id="example-input-2-3">[[10,100]]</span>

  <strong>Output: </strong><span id="example-output-2">-1</span>

  <strong>Explanation: </strong>We can&#39;t reach the target (or even the first gas station).

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input: </strong>target = <span id="example-input-3-1">100</span>, startFuel = <span id="example-input-3-2">10</span>, stations = <span id="example-input-3-3">[[10,60],[20,30],[30,30],[60,40]]</span>

  <strong>Output: </strong><span id="example-output-3">2</span>

  <strong>Explanation: </strong>

  We start with 10 liters of fuel.

  We drive to position 10, expending 10 liters of fuel.  We refuel from 0 liters to 60 liters of gas.

  Then, we drive from position 10 to position 60 (expending 50 liters of fuel),

  and refuel from 10 liters to 50 liters of gas.  We then drive to and reach the target.

  We made 2 refueling stops along the way, so we return 2.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Note:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ol>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= target, startFuel, stations[i][1] <= 10^9

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= stations.length <= 500

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 < stations[0][0] < stations[1][0] < ... <
stations[stations.length-1][0] < target

#+begin_html
  </li>
#+end_html

#+begin_html
  </ol>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
