* [[https://leetcode.com/problems/minimum-swaps-to-make-strings-equal][1247.
Minimum Swaps to Make Strings Equal]]
  :PROPERTIES:
  :CUSTOM_ID: minimum-swaps-to-make-strings-equal
  :END:
[[./solution/1200-1299/1247.Minimum Swaps to Make Strings Equal/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

You are given two strings s1 and s2 of equal length consisting of
letters "x" and "y" only. Your task is to make these two strings equal
to each other. You can swap any two characters that belong to different
strings, which means: swap s1[i] and s2[j].

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the minimum number of swaps required to make s1 and s2 equal, or
return -1 if it is impossible to do so.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> s1 = &quot;xx&quot;, s2 = &quot;yy&quot;

  <strong>Output:</strong> 1

  <strong>Explanation: 

  </strong>Swap s1[0] and s2[1], s1 = &quot;yx&quot;, s2 = &quot;yx&quot;.</pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2: 

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> s1 = &quot;xy&quot;, s2 = &quot;yx&quot;

  <strong>Output:</strong> 2

  <strong>Explanation: 

  </strong>Swap s1[0] and s2[0], s1 = &quot;yy&quot;, s2 = &quot;xx&quot;.

  Swap s1[0] and s2[1], s1 = &quot;xy&quot;, s2 = &quot;xy&quot;.

  Note that you can&#39;t swap s1[0] and s1[1] to make s1 equal to &quot;yx&quot;, cause we can only swap chars in different strings.</pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> s1 = &quot;xx&quot;, s2 = &quot;xy&quot;

  <strong>Output:</strong> -1

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 4:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> s1 = &quot;xxyyxyxyxx&quot;, s2 = &quot;xyyxyxxxyx&quot;

  <strong>Output:</strong> 4

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= s1.length, s2.length <= 1000

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

s1, s2 only contain 'x' or 'y'.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
