* [[https://leetcode.com/problems/max-increase-to-keep-city-skyline][807.
Max Increase to Keep City Skyline]]
  :PROPERTIES:
  :CUSTOM_ID: max-increase-to-keep-city-skyline
  :END:
[[./solution/0800-0899/0807.Max Increase to Keep City Skyline/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

In a 2 dimensional array grid, each value grid[i][j] represents the
height of a building located there. We are allowed to increase the
height of any number of buildings, by any amount (the amounts can be
different for different buildings). Height 0 is considered to be
a building as well. 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

At the end, the "skyline" when viewed from all four directions of the
grid, i.e. top, bottom, left, and right, must be the same as the skyline
of the original grid. A city's skyline is the outer contour of the
rectangles formed by all the buildings when viewed from a distance.
See the following example.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

What is the maximum total sum that the height of the buildings can be
increased?

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Example:</strong>

  <strong>Input:</strong> grid = [[3,0,8,4],[2,4,5,7],[9,2,6,3],[0,3,1,0]]

  <strong>Output:</strong> 35

  <strong>Explanation:</strong> 

  The grid is:

  [ [3, 0, 8, 4], 

    [2, 4, 5, 7],

    [9, 2, 6, 3],

    [0, 3, 1, 0] ]



  The skyline viewed from top or bottom is: [9, 4, 8, 7]

  The skyline viewed from left or right is: [8, 7, 9, 3]



  The grid after increasing the height of buildings without affecting skylines is:



  gridNew = [ [8, 4, 8, 7],

              [7, 4, 7, 7],

              [9, 4, 8, 7],

              [3, 3, 3, 3] ]



  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Notes:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 < grid.length = grid[0].length <= 50.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

All heights grid[i][j] are in the range [0, 100].

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

All buildings in grid[i][j] occupy the entire grid cell: that is, they
are a 1 x 1 x grid[i][j] rectangular prism.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
