* [[https://leetcode.com/problems/get-biggest-three-rhombus-sums-in-a-grid][1878.
Get Biggest Three Rhombus Sums in a Grid]]
  :PROPERTIES:
  :CUSTOM_ID: get-biggest-three-rhombus-sums-in-a-grid
  :END:
[[./solution/1800-1899/1878.Get Biggest Three Rhombus Sums in a Grid/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

You are given an m x n integer matrix grid​​​.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

A rhombus sum is the sum of the elements that form the border of a
regular rhombus shape in grid​​​. The rhombus must have the shape of a
square rotated 45 degrees with each of the corners centered in a grid
cell. Below is an image of four valid rhombus shapes with the
corresponding colored cells that should be included in each rhombus sum:

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Note that the rhombus can have an area of 0, which is depicted by the
purple rhombus in the bottom right corner.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the biggest three distinct rhombus sums in the grid in descending
order. If there are less than three distinct values, return all of them.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> grid = [[3,4,5,1,3],[3,3,4,2,3],[20,30,200,40,10],[1,5,5,4,1],[4,3,2,2,5]]
  <strong>Output:</strong> [228,216,211]
  <strong>Explanation:</strong> The rhombus shapes for the three biggest distinct rhombus sums are depicted above.
  - Blue: 20 + 3 + 200 + 5 = 228
  - Red: 200 + 2 + 10 + 4 = 216
  - Green: 5 + 200 + 4 + 2 = 211
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> grid = [[1,2,3],[4,5,6],[7,8,9]]
  <strong>Output:</strong> [20,9,8]
  <strong>Explanation:</strong> The rhombus shapes for the three biggest distinct rhombus sums are depicted above.
  - Blue: 4 + 2 + 6 + 8 = 20
  - Red: 9 (area 0 rhombus in the bottom right corner)
  - Green: 8 (area 0 rhombus in the bottom middle)
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> grid = [[7,7,7]]
  <strong>Output:</strong> [7]
  <strong>Explanation:</strong> All three possible rhombus sums are the same, so return [7].
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

m == grid.length

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

n == grid[i].length

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= m, n <= 100

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= grid[i][j] <= 105

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
