* [[https://leetcode.com/problems/find-two-non-overlapping-sub-arrays-each-with-target-sum][1477.
Find Two Non-overlapping Sub-arrays Each With Target Sum]]
  :PROPERTIES:
  :CUSTOM_ID: find-two-non-overlapping-sub-arrays-each-with-target-sum
  :END:
[[./solution/1400-1499/1477.Find Two Non-overlapping Sub-arrays Each With Target Sum/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Given an array of integers arr and an integer target.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

You have to find two non-overlapping sub-arrays of arr each with a sum
equal target. There can be multiple answers so you have to find an
answer where the sum of the lengths of the two sub-arrays is minimum.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the minimum sum of the lengths of the two required sub-arrays, or
return -1 if you cannot find such two sub-arrays.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> arr = [3,2,2,4,3], target = 3
  <strong>Output:</strong> 2
  <strong>Explanation:</strong> Only two sub-arrays have sum = 3 ([3] and [3]). The sum of their lengths is 2.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> arr = [7,3,4,7], target = 7
  <strong>Output:</strong> 2
  <strong>Explanation:</strong> Although we have three non-overlapping sub-arrays of sum = 7 ([7], [3,4] and [7]), but we will choose the first and third sub-arrays as the sum of their lengths is 2.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> arr = [4,3,2,6,2,3,4], target = 6
  <strong>Output:</strong> -1
  <strong>Explanation:</strong> We have only one sub-array of sum = 6.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 4:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> arr = [5,5,4,4,5], target = 3
  <strong>Output:</strong> -1
  <strong>Explanation:</strong> We cannot find a sub-array of sum = 3.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 5:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> arr = [3,1,1,1,5,1,2,1], target = 3
  <strong>Output:</strong> 3
  <strong>Explanation:</strong> Note that sub-arrays [1,2] and [2,1] cannot be an answer because they overlap.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= arr.length <= 105

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= arr[i] <= 1000

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= target <= 108

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
