* [[https://leetcode.com/problems/roman-to-integer][13. Roman to
Integer]]
  :PROPERTIES:
  :CUSTOM_ID: roman-to-integer
  :END:
[[./solution/0000-0099/0013.Roman to Integer/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Roman numerals are represented by seven different symbols: I, V, X, L,
C, D and M.

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Symbol</strong>       <strong>Value</strong>

  I             1

  V             5

  X             10

  L             50

  C             100

  D             500

  M             1000</pre>
#+end_html

#+begin_html
  <p>
#+end_html

For example, 2 is written as II in Roman numeral, just two one's added
together. 12 is written as XII, which is simply X + II. The number 27 is
written as XXVII, which is XX + V + II.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Roman numerals are usually written largest to smallest from left to
right. However, the numeral for four is not IIII. Instead, the number
four is written as IV. Because the one is before the five we subtract it
making four. The same principle applies to the number nine, which is
written as IX. There are six instances where subtraction is used:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

I can be placed before V (5) and X (10) to make 4 and 9. 

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

X can be placed before L (50) and C (100) to make 40 and 90. 

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

C can be placed before D (500) and M (1000) to make 400 and 900.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

#+begin_html
  <p>
#+end_html

Given a roman numeral, convert it to an integer.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> s = &quot;III&quot;

  <strong>Output:</strong> 3

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> s = &quot;IV&quot;

  <strong>Output:</strong> 4

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> s = &quot;IX&quot;

  <strong>Output:</strong> 9

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 4:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> s = &quot;LVIII&quot;

  <strong>Output:</strong> 58

  <strong>Explanation:</strong> L = 50, V= 5, III = 3.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 5:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> s = &quot;MCMXCIV&quot;

  <strong>Output:</strong> 1994

  <strong>Explanation:</strong> M = 1000, CM = 900, XC = 90 and IV = 4.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= s.length <= 15

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

s contains only the characters ('I', 'V', 'X', 'L', 'C', 'D', 'M').

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

It is guaranteed that s is a valid roman numeral in the range [1, 3999].

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
  class Solution:
      def romanToInt(self, s: str) -> int:
          nums = {
              'M': 1000,
              'CM': 900,
              'D': 500,
              'CD': 400,
              'C': 100,
              'XC': 90,
              'L': 50,
              'XL': 40,
              'X': 10,
              'IX': 9,
              'V': 5,
              'IV': 4,
              'I': 1
          }
          i = res = 0
          while i < len(s):
              if i + 1 < len(s) and s[i:i + 2] in nums:
                  res += nums[s[i: i + 2]]
                  i += 2
              else:
                  res += nums[s[i: i + 1]]
                  i += 1
          return res
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
  class Solution {
      public int romanToInt(String s) {
          Map<String, Integer> nums = new HashMap<>();
          nums.put("M", 1000);
          nums.put("CM", 900);
          nums.put("D", 500);
          nums.put("CD", 400);
          nums.put("C", 100);
          nums.put("XC", 90);
          nums.put("L", 50);
          nums.put("XL", 40);
          nums.put("X", 10);
          nums.put("IX", 9);
          nums.put("V", 5);
          nums.put("IV", 4);
          nums.put("I", 1);
          int res = 0;
          for (int i = 0; i < s.length();) {
              if (i + 1 < s.length() && nums.get(s.substring(i, i + 2)) != null) {
                  res += nums.get(s.substring(i, i + 2));
                  i += 2;
              } else {
                  res += nums.get(s.substring(i, i + 1));
                  i += 1;
              }
          }
          return res;
      }
  }
#+end_src

*** *C++*
    :PROPERTIES:
    :CUSTOM_ID: c
    :END:
#+begin_src cpp
  class Solution {
     public:
      int romanToInt(string s) {
          unordered_map<char, int> nums{
              {'I', 1},
              {'V', 5},
              {'X', 10},
              {'L', 50},
              {'C', 100},
              {'D', 500},
              {'M', 1000},
          };
          int ans = 0;
          for (int i = 0; i < s.size() - 1; ++i) {
              if (nums[s[i]] < nums[s[i + 1]])
                  ans -= nums[s[i]];
              else
                  ans += nums[s[i]];
          }
          return ans + nums[s.back()];
      }
  };
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
