* [[https://leetcode.com/problems/largest-time-for-given-digits][949.
Largest Time for Given Digits]]
  :PROPERTIES:
  :CUSTOM_ID: largest-time-for-given-digits
  :END:
[[./solution/0900-0999/0949.Largest Time for Given Digits/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Given an array arr of 4 digits, find the latest 24-hour time that can be
made using each digit exactly once.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

24-hour times are formatted as "HH:MM", where HH is between 00 and 23,
and MM is between 00 and 59. The earliest 24-hour time is 00:00, and the
latest is 23:59.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the latest 24-hour time in "HH:MM" format.  If no valid time can
be made, return an empty string.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> A = [1,2,3,4]
  <strong>Output:</strong> &quot;23:41&quot;
  <strong>Explanation:</strong>&nbsp;The valid 24-hour times are &quot;12:34&quot;, &quot;12:43&quot;, &quot;13:24&quot;, &quot;13:42&quot;, &quot;14:23&quot;, &quot;14:32&quot;, &quot;21:34&quot;, &quot;21:43&quot;, &quot;23:14&quot;, and &quot;23:41&quot;. Of these times, &quot;23:41&quot; is the latest.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> A = [5,5,5,5]
  <strong>Output:</strong> &quot;&quot;
  <strong>Explanation:</strong>&nbsp;There are no valid 24-hour times as &quot;55:55&quot; is not valid.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> A = [0,0,0,0]
  <strong>Output:</strong> &quot;00:00&quot;
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 4:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> A = [0,0,1,0]
  <strong>Output:</strong> &quot;10:00&quot;
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

arr.length == 4

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= arr[i] <= 9

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
