* [[https://leetcode.com/problems/minimum-cost-to-hire-k-workers][857.
Minimum Cost to Hire K Workers]]
  :PROPERTIES:
  :CUSTOM_ID: minimum-cost-to-hire-k-workers
  :END:
[[./solution/0800-0899/0857.Minimum Cost to Hire K Workers/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

There are N workers.  The i-th worker has a quality[i] and a minimum
wage expectation wage[i].

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Now we want to hire exactly K workers to form a paid group.  When hiring
a group of K workers, we must pay them according to the following rules:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ol>
#+end_html

#+begin_html
  <li>
#+end_html

Every worker in the paid group should be paid in the ratio of their
quality compared to other workers in the paid group.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Every worker in the paid group must be paid at least their minimum wage
expectation.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ol>
#+end_html

#+begin_html
  <p>
#+end_html

Return the least amount of money needed to form a paid group satisfying
the above conditions.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <ol>
#+end_html

#+begin_html
  </ol>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input: </strong>quality = <span id="example-input-1-1">[10,20,5]</span>, wage = <span id="example-input-1-2">[70,50,30]</span>, K = <span id="example-input-1-3">2</span>

  <strong>Output: </strong><span id="example-output-1">105.00000

  <strong>Explanation</strong>: </span><span>We pay 70 to 0-th worker and 35 to 2-th worker.</span>

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input: </strong>quality = <span id="example-input-2-1">[3,1,10,10,1]</span>, wage = <span id="example-input-2-2">[4,8,2,2,7]</span>, K = <span id="example-input-2-3">3</span>

  <strong>Output: </strong><span id="example-output-2">30.66667

  <strong>Explanation</strong>: </span><span>We pay 4 to 0-th worker, 13.33333 to 2-th and 3-th workers seperately.</span> 

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Note:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ol>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= K <= N <= 10000, where N = quality.length = wage.length

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= quality[i] <= 10000

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= wage[i] <= 10000

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Answers within 10^-5 of the correct answer will be considered correct.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ol>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
