* [[https://leetcode.com/problems/count-binary-substrings][696. Count
Binary Substrings]]
  :PROPERTIES:
  :CUSTOM_ID: count-binary-substrings
  :END:
[[./solution/0600-0699/0696.Count Binary Substrings/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Give a string s, count the number of non-empty (contiguous) substrings
that have the same number of 0's and 1's, and all the 0's and all the
1's in these substrings are grouped consecutively.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Substrings that occur multiple times are counted the number of times
they occur.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  <pre>

  <b>Input:</b> "00110011"

  <b>Output:</b> 6

  <b>Explanation:</b> There are 6 substrings that have equal number of consecutive 1's and 0's: "0011", "01", "1100", "10", "0011", and "01".

  <br>Notice that some of these substrings repeat and are counted the number of times they occur.

  <br>Also, "00110011" is not a valid substring because <b>all</b> the 0's (and 1's) are not grouped together.

  </pre>
#+end_html

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  <pre>

  <b>Input:</b> "10101"

  <b>Output:</b> 4

  <b>Explanation:</b> There are 4 substrings: "10", "01", "10", "01" that have equal number of consecutive 1's and 0's.

  </pre>
#+end_html

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Note:

#+begin_html
  <li>
#+end_html

s.length will be between 1 and 50,000.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

s will only consist of "0" or "1" characters.

#+begin_html
  </li>
#+end_html

#+begin_html
  </p>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
