* [[https://leetcode.com/problems/maximum-vacation-days][568. Maximum
Vacation Days]]
  :PROPERTIES:
  :CUSTOM_ID: maximum-vacation-days
  :END:
[[./solution/0500-0599/0568.Maximum Vacation Days/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

LeetCode wants to give one of its best employees the option to travel
among N cities to collect algorithm problems. But all work and no play
makes Jack a dull boy, you could take vacations in some particular
cities and weeks. Your job is to schedule the traveling to maximize the
number of vacation days you could take, but there are certain rules and
restrictions you need to follow.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Rules and restrictions:

#+begin_html
  <ol>
#+end_html

#+begin_html
  <li>
#+end_html

You can only travel among N cities, represented by indexes from 0 to
N-1. Initially, you are in the city indexed 0 on Monday.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

The cities are connected by flights. The flights are represented as a
N*N matrix (not necessary symmetrical), called flights representing the
airline status from the city i to the city j. If there is no flight from
the city i to the city j, flights[i][j] = 0; Otherwise, flights[i][j] =
1. Also, flights[i][i] = 0 for all i.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

You totally have K weeks (each week has 7 days) to travel. You can only
take flights at most once per day and can only take flights on each
week's Monday morning. Since flight time is so short, we don't consider
the impact of flight time.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

For each city, you can only have restricted vacation days in different
weeks, given an N*K matrix called days representing this relationship.
For the value of days[i][j], it represents the maximum days you could
take vacation in the city i in the week j.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ol>
#+end_html

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

You're given the flights matrix and days matrix, and you need to output
the maximum vacation days you could take during K weeks.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  <pre>

  <b>Input:</b>flights = [[0,1,1],[1,0,1],[1,1,0]], days = [[1,3,1],[6,0,3],[3,3,3]]

  <b>Output:</b> 12

  <b>Explanation:</b> <br>Ans = 6 + 3 + 3 = 12. <br>

  One of the best strategies is:

  1st week : fly from city 0 to city 1 on Monday, and play 6 days and work 1 day. <br/>(Although you start at city 0, we could also fly to and start at other cities since it is Monday.) 

  2nd week : fly from city 1 to city 2 on Monday, and play 3 days and work 4 days.

  3rd week : stay at city 2, and play 3 days and work 4 days.

  </pre>
#+end_html

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  <pre>

  <b>Input:</b>flights = [[0,0,0],[0,0,0],[0,0,0]], days = [[1,1,1],[7,7,7],[7,7,7]]

  <b>Output:</b> 3

  <b>Explanation:</b> <br>Ans = 1 + 1 + 1 = 3. <br>

  Since there is no flights enable you to move to another city, you have to stay at city 0 for the whole 3 weeks. <br/>For each week, you only have one day to play and six days to work. <br/>So the maximum number of vacation days is 3.

  </pre>
#+end_html

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  <pre>

  <b>Input:</b>flights = [[0,1,1],[1,0,1],[1,1,0]], days = [[7,0,0],[0,7,0],[0,0,7]]

  <b>Output:</b> 21

  <b>Explanation:</b><br>Ans = 7 + 7 + 7 = 21<br>

  One of the best strategies is:

  1st week : stay at city 0, and play 7 days. 

  2nd week : fly from city 0 to city 1 on Monday, and play 7 days.

  3rd week : fly from city 1 to city 2 on Monday, and play 7 days.

  </pre>
#+end_html

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Note:

#+begin_html
  <ol>
#+end_html

#+begin_html
  <li>
#+end_html

N and K are positive integers, which are in the range of [1, 100].

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

In the matrix flights, all the values are integers in the range of [0,
1].

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

In the matrix days, all the values are integers in the range [0, 7].

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

You could stay at a city beyond the number of vacation days, but you
should work on the extra days, which won't be counted as vacation days.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

If you fly from the city A to the city B and take the vacation on that
day, the deduction towards vacation days will count towards the vacation
days of city B in that week.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

We don't consider the impact of flight hours towards the calculation of
vacation days.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ol>
#+end_html

#+begin_html
  </p>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
