* [[https://leetcode.com/problems/sliding-window-median][480. Sliding
Window Median]]
  :PROPERTIES:
  :CUSTOM_ID: sliding-window-median
  :END:
[[./solution/0400-0499/0480.Sliding Window Median/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

The median is the middle value in an ordered integer list. If the size
of the list is even, there is no middle value. So the median is the mean
of the two middle values.

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

For examples, if arr = [2,3,4], the median is 3.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

For examples, if arr = [1,2,3,4], the median is (2 + 3) / 2 = 2.5.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

#+begin_html
  <p>
#+end_html

You are given an integer array nums and an integer k. There is a sliding
window of size k which is moving from the very left of the array to the
very right. You can only see the k numbers in the window. Each time the
sliding window moves right by one position.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the median array for each window in the original array. Answers
within 10-5 of the actual value will be accepted.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> nums = [1,3,-1,-3,5,3,6,7], k = 3
  <strong>Output:</strong> [1.00000,-1.00000,-1.00000,3.00000,5.00000,6.00000]
  <strong>Explanation:</strong> 
  Window position                Median
  ---------------                -----
  [<strong>1  3  -1</strong>] -3  5  3  6  7        1
   1 [<strong>3  -1  -3</strong>] 5  3  6  7       -1
   1  3 [<strong>-1  -3  5</strong>] 3  6  7       -1
   1  3  -1 [<strong>-3  5  3</strong>] 6  7        3
   1  3  -1  -3 [<strong>5  3  6</strong>] 7        5
   1  3  -1  -3  5 [<strong>3  6  7</strong>]       6
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> nums = [1,2,3,4,2,3,1,4,2], k = 3
  <strong>Output:</strong> [2.00000,3.00000,3.00000,3.00000,2.00000,3.00000,2.00000]
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= k <= nums.length <= 105

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

231 <= nums[i] <= 231 - 1

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
