* [[https://leetcode.com/problems/flood-fill][733. Flood Fill]]
  :PROPERTIES:
  :CUSTOM_ID: flood-fill
  :END:
[[./solution/0700-0799/0733.Flood Fill/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

An image is represented by a 2-D array of integers, each integer
representing the pixel value of the image (from 0 to 65535).

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Given a coordinate (sr, sc) representing the starting pixel (row and
column) of the flood fill, and a pixel value newColor, "flood fill" the
image.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

To perform a "flood fill", consider the starting pixel, plus any pixels
connected 4-directionally to the starting pixel of the same color as the
starting pixel, plus any pixels connected 4-directionally to those
pixels (also with the same color as the starting pixel), and so on.
Replace the color of all of the aforementioned pixels with the newColor.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

At the end, return the modified image.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  <pre>

  <b>Input:</b> 

  image = [[1,1,1],[1,1,0],[1,0,1]]

  sr = 1, sc = 1, newColor = 2

  <b>Output:</b> [[2,2,2],[2,2,0],[2,0,1]]

  <b>Explanation:</b> 

  From the center of the image (with position (sr, sc) = (1, 1)), all pixels connected 

  by a path of the same color as the starting pixel are colored with the new color.

  Note the bottom corner is not colored 2, because it is not 4-directionally connected

  to the starting pixel.

  </pre>
#+end_html

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Note:

#+begin_html
  <li>
#+end_html

The length of image and image[0] will be in the range [1, 50].

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

The given starting pixel will satisfy 0 <= sr < image.length and 0 <= sc
< image[0].length.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

The value of each color in image[i][j] and newColor will be an integer
in [0, 65535].

#+begin_html
  </li>
#+end_html

#+begin_html
  </p>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
