* [[https://leetcode.com/problems/statistics-from-a-large-sample][1093.
Statistics from a Large Sample]]
  :PROPERTIES:
  :CUSTOM_ID: statistics-from-a-large-sample
  :END:
[[./solution/1000-1099/1093.Statistics from a Large Sample/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

You are given a large sample of integers in the range [0, 255]. Since
the sample is so large, it is represented by an array count where
count[k] is the number of times that k appears in the sample.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Calculate the following statistics:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

minimum: The minimum element in the sample.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

maximum: The maximum element in the sample.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

mean: The average of the sample, calculated as the total sum of all
elements divided by the total number of elements.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

median:

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

If the sample has an odd number of elements, then the median is the
middle element once the sample is sorted.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

If the sample has an even number of elements, then the median is the
average of the two middle elements once the sample is sorted.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

#+begin_example
  </li>
  <li><code>mode</code>: The number that appears the most in the sample. It is guaranteed to be <strong>unique</strong>.</li>
#+end_example

#+begin_html
  </ul>
#+end_html

#+begin_html
  <p>
#+end_html

Return the statistics of the sample as an array of floating-point
numbers [minimum, maximum, mean, median, mode]. Answers within 10-5 of
the actual answer will be accepted.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> count = [0,1,3,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
  <strong>Output:</strong> [1.00000,3.00000,2.37500,2.50000,3.00000]
  <strong>Explanation:</strong> The sample represented by count is [1,2,2,2,3,3,3,3].
  The minimum and maximum are 1 and 3 respectively.
  The mean is (1+2+2+2+3+3+3+3) / 8 = 19 / 8 = 2.375.
  Since the size of the sample is even, the median is the average of the two middle elements 2 and 3, which is 2.5.
  The mode is 3 as it appears the most in the sample.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> count = [0,4,3,2,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
  <strong>Output:</strong> [1.00000,4.00000,2.18182,2.00000,1.00000]
  <strong>Explanation:</strong> The sample represented by count is [1,1,1,1,2,2,2,3,3,4,4].
  The minimum and maximum are 1 and 4 respectively.
  The mean is (1+1+1+1+2+2+2+3+3+4+4) / 11 = 24 / 11 = 2.18181818... (for display purposes, the output shows the rounded number 2.18182).
  Since the size of the sample is odd, the median is the middle element 2.
  The mode is 1 as it appears the most in the sample.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

count.length == 256

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= count[i] <= 109

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= sum(count) <= 109

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

The mode of the sample that count represents is unique.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
