* [[https://leetcode.com/problems/validate-ip-address][468. Validate IP
Address]]
  :PROPERTIES:
  :CUSTOM_ID: validate-ip-address
  :END:
[[./solution/0400-0499/0468.Validate IP Address/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Given a string IP, return "IPv4" if IP is a valid IPv4 address, "IPv6"
if IP is a valid IPv6 address or "Neither" if IP is not a correct IP of
any type.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

A valid IPv4 address is an IP in the form "x1.x2.x3.x4" where 0 <= xi <=
255 and xi cannot contain leading zeros. For example, "192.168.1.1" and
"192.168.1.0" are valid IPv4 addresses but "192.168.01.1", while
"192.168.1.00" and "192.168@1.1" are invalid IPv4 addresses.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

A valid IPv6 address is an IP in the form "x1:x2:x3:x4:x5:x6:x7:x8"
where:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= xi.length <= 4

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

xi is a hexadecimal string which may contain digits, lower-case English
letter ('a' to 'f') and upper-case English letters ('A' to 'F').

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Leading zeros are allowed in xi.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

#+begin_html
  <p>
#+end_html

For example, "2001:0db8:85a3:0000:0000:8a2e:0370:7334" and
"2001:db8:85a3:0:0:8A2E:0370:7334" are valid IPv6 addresses, while
"2001:0db8:85a3::8A2E:037j:7334" and
"02001:0db8:85a3:0000:0000:8a2e:0370:7334" are invalid IPv6 addresses.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> IP = &quot;172.16.254.1&quot;
  <strong>Output:</strong> &quot;IPv4&quot;
  <strong>Explanation:</strong> This is a valid IPv4 address, return &quot;IPv4&quot;.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> IP = &quot;2001:0db8:85a3:0:0:8A2E:0370:7334&quot;
  <strong>Output:</strong> &quot;IPv6&quot;
  <strong>Explanation:</strong> This is a valid IPv6 address, return &quot;IPv6&quot;.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> IP = &quot;256.256.256.256&quot;
  <strong>Output:</strong> &quot;Neither&quot;
  <strong>Explanation:</strong> This is neither a IPv4 address nor a IPv6 address.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 4:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> IP = &quot;2001:0db8:85a3:0:0:8A2E:0370:7334:&quot;
  <strong>Output:</strong> &quot;Neither&quot;
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 5:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> IP = &quot;1e1.4.5.6&quot;
  <strong>Output:</strong> &quot;Neither&quot;
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

IP consists only of English letters, digits and the characters '.' and
':'.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
