* [[https://leetcode.com/problems/people-whose-list-of-favorite-companies-is-not-a-subset-of-another-list][1452.
People Whose List of Favorite Companies Is Not a Subset of Another
List]]
  :PROPERTIES:
  :CUSTOM_ID: people-whose-list-of-favorite-companies-is-not-a-subset-of-another-list
  :END:
[[./solution/1400-1499/1452.People Whose List of Favorite Companies Is Not a Subset of Another List/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Given the array favoriteCompanies where favoriteCompanies[i] is the list
of favorites companies for the ith person (indexed from 0).

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the indices of people whose list of favorite companies is not a
subset of any other list of favorites companies. You must return the
indices in increasing order.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> favoriteCompanies = [[&quot;leetcode&quot;,&quot;google&quot;,&quot;facebook&quot;],[&quot;google&quot;,&quot;microsoft&quot;],[&quot;google&quot;,&quot;facebook&quot;],[&quot;google&quot;],[&quot;amazon&quot;]]
  <strong>Output:</strong> [0,1,4] 
  <strong>Explanation:</strong> 
  Person with index=2 has favoriteCompanies[2]=[&quot;google&quot;,&quot;facebook&quot;] which is a subset of favoriteCompanies[0]=[&quot;leetcode&quot;,&quot;google&quot;,&quot;facebook&quot;] corresponding to the person with index 0. 
  Person with index=3 has favoriteCompanies[3]=[&quot;google&quot;] which is a subset of favoriteCompanies[0]=[&quot;leetcode&quot;,&quot;google&quot;,&quot;facebook&quot;] and favoriteCompanies[1]=[&quot;google&quot;,&quot;microsoft&quot;]. 
  Other lists of favorite companies are not a subset of another list, therefore, the answer is [0,1,4].
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> favoriteCompanies = [[&quot;leetcode&quot;,&quot;google&quot;,&quot;facebook&quot;],[&quot;leetcode&quot;,&quot;amazon&quot;],[&quot;facebook&quot;,&quot;google&quot;]]
  <strong>Output:</strong> [0,1] 
  <strong>Explanation:</strong> In this case favoriteCompanies[2]=[&quot;facebook&quot;,&quot;google&quot;] is a subset of favoriteCompanies[0]=[&quot;leetcode&quot;,&quot;google&quot;,&quot;facebook&quot;], therefore, the answer is [0,1].
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> favoriteCompanies = [[&quot;leetcode&quot;],[&quot;google&quot;],[&quot;facebook&quot;],[&quot;amazon&quot;]]
  <strong>Output:</strong> [0,1,2,3]
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= favoriteCompanies.length <= 100

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= favoriteCompanies[i].length <= 500

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= favoriteCompanies[i][j].length <= 20

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

All strings in favoriteCompanies[i] are distinct.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

All lists of favorite companies are distinct, that is, If we sort
alphabetically each list then favoriteCompanies[i] !=
favoriteCompanies[j].

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

All strings consist of lowercase English letters only.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
