* [[https://leetcode.com/problems/knight-probability-in-chessboard][688.
Knight Probability in Chessboard]]
  :PROPERTIES:
  :CUSTOM_ID: knight-probability-in-chessboard
  :END:
[[./solution/0600-0699/0688.Knight Probability in Chessboard/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

On an NxN chessboard, a knight starts at the r-th row and c-th column
and attempts to make exactly K moves. The rows and columns are 0
indexed, so the top-left square is (0, 0), and the bottom-right square
is (N-1, N-1).

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

A chess knight has 8 possible moves it can make, as illustrated below.
Each move is two squares in a cardinal direction, then one square in an
orthogonal direction.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Each time the knight is to move, it chooses one of eight possible moves
uniformly at random (even if the piece would go off the chessboard) and
moves there.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

The knight continues moving until it has made exactly K moves or has
moved off the chessboard. Return the probability that the knight remains
on the board after it has stopped moving.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <b>Input:</b> 3, 2, 0, 0

  <b>Output:</b> 0.0625

  <b>Explanation:</b> There are two moves (to (1,2), (2,1)) that will keep the knight on the board.

  From each of those positions, there are also two moves that will keep the knight on the board.

  The total probability the knight stays on the board is 0.0625.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Note:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

N will be between 1 and 25.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

K will be between 0 and 100.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

The knight always initially starts on the board.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
