* [[https://leetcode.com/problems/reducing-dishes][1402. Reducing
Dishes]]
  :PROPERTIES:
  :CUSTOM_ID: reducing-dishes
  :END:
[[./solution/1400-1499/1402.Reducing Dishes/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

A chef has collected data on the satisfaction level of his n
dishes. Chef can cook any dish in 1 unit of time.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Like-time coefficient of a dish is defined as the time taken to cook
that dish including previous dishes multiplied by its satisfaction level
 i.e.  time[i]*satisfaction[i]

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the maximum sum of Like-time coefficient that the chef can obtain
after dishes preparation.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Dishes can be prepared in any order and the chef can discard some dishes
to get this maximum value.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> satisfaction = [-1,-8,0,5,-9]

  <strong>Output:</strong> 14

  <strong>Explanation: </strong>After Removing the second and last dish, the maximum total <em>Like-time coefficient</em> will be equal to (-1*1 + 0*2 + 5*3 = 14). Each dish is prepared in one unit of time.</pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> satisfaction = [4,3,2]

  <strong>Output:</strong> 20

  <strong>Explanation:</strong> Dishes can be prepared in any order, (2*1 + 3*2 + 4*3 = 20)

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> satisfaction = [-1,-4,-5]

  <strong>Output:</strong> 0

  <strong>Explanation:</strong> People don&#39;t like the dishes. No dish is prepared.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 4:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> satisfaction = [-2,5,-1,0,3,-3]

  <strong>Output:</strong> 35

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

n == satisfaction.length

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= n <= 500

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

-10^3 <= satisfaction[i] <= 10^3

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
