* [[https://leetcode.com/problems/chalkboard-xor-game][810. Chalkboard
XOR Game]]
  :PROPERTIES:
  :CUSTOM_ID: chalkboard-xor-game
  :END:
[[./solution/0800-0899/0810.Chalkboard XOR Game/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

We are given non-negative integers nums[i] which are written on a
chalkboard.  Alice and Bob take turns erasing exactly one number from
the chalkboard, with Alice starting first.  If erasing a number
causes the bitwise XOR of all the elements of the chalkboard to
become 0, then that player loses.  (Also, we'll say the bitwise XOR of
one element is that element itself, and the bitwise XOR of no elements
is 0.)

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Also, if any player starts their turn with the bitwise XOR of all the
elements of the chalkboard equal to 0, then that player wins.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return True if and only if Alice wins the game, assuming both players
play optimally.

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Example:</strong>

  <strong>Input:</strong> nums = [1, 1, 2]

  <strong>Output:</strong> false

  <strong>Explanation:</strong> 

  Alice has two choices: erase 1 or erase 2. 

  If she erases 1, the nums array becomes [1, 2]. The bitwise XOR of all the elements of the chalkboard is 1 XOR 2 = 3. Now Bob can remove any element he wants, because Alice will be the one to erase the last element and she will lose. 

  If Alice erases 2 first, now nums becomes [1, 1]. The bitwise XOR of all the elements of the chalkboard is 1 XOR 1 = 0. Alice will lose.



  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Notes:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= N <= 1000. 

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= nums[i] <= 2^16.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
