* [[https://leetcode.com/problems/minimum-deletion-cost-to-avoid-repeating-letters][1578.
Minimum Deletion Cost to Avoid Repeating Letters]]
  :PROPERTIES:
  :CUSTOM_ID: minimum-deletion-cost-to-avoid-repeating-letters
  :END:
[[./solution/1500-1599/1578.Minimum Deletion Cost to Avoid Repeating Letters/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Given a string s and an array of integers cost where cost[i] is the cost
of deleting the ith character in s.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the minimum cost of deletions such that there are no two
identical letters next to each other.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Notice that you will delete the chosen characters at the same time, in
other words, after deleting a character, the costs of deleting other
characters will not change.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> s = &quot;abaac&quot;, cost = [1,2,3,4,5]
  <strong>Output:</strong> 3
  <strong>Explanation:</strong> Delete the letter &quot;a&quot; with cost 3 to get &quot;abac&quot; (String without two identical letters next to each other).
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> s = &quot;abc&quot;, cost = [1,2,3]
  <strong>Output:</strong> 0
  <strong>Explanation:</strong> You don&#39;t need to delete any character because there are no identical letters next to each other.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> s = &quot;aabaa&quot;, cost = [1,2,3,4,1]
  <strong>Output:</strong> 2
  <strong>Explanation:</strong> Delete the first and the last character, getting the string (&quot;aba&quot;).
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

s.length == cost.length

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= s.length, cost.length <= 10^5

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= cost[i] <= 10^4

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

s contains only lowercase English letters.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
