* [[https://leetcode.com/problems/display-table-of-food-orders-in-a-restaurant][1418.
Display Table of Food Orders in a Restaurant]]
  :PROPERTIES:
  :CUSTOM_ID: display-table-of-food-orders-in-a-restaurant
  :END:
[[./solution/1400-1499/1418.Display Table of Food Orders in a Restaurant/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Given the array orders, which represents the orders that customers have
done in a restaurant. More
specifically orders[i]=[customerNamei,tableNumberi,foodItemi] where
customerNamei is the name of the customer, tableNumberi is the table
customer sit at, and foodItemi is the item customer orders.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the restaurant's “display table”. The “display table” is a table
whose row entries denote how many of each food item each table ordered.
The first column is the table number and the remaining columns
correspond to each food item in alphabetical order. The first row should
be a header whose first column is “Table”, followed by the names of the
food items. Note that the customer names are not part of the table.
Additionally, the rows should be sorted in numerically increasing order.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> orders = [[&quot;David&quot;,&quot;3&quot;,&quot;Ceviche&quot;],[&quot;Corina&quot;,&quot;10&quot;,&quot;Beef Burrito&quot;],[&quot;David&quot;,&quot;3&quot;,&quot;Fried Chicken&quot;],[&quot;Carla&quot;,&quot;5&quot;,&quot;Water&quot;],[&quot;Carla&quot;,&quot;5&quot;,&quot;Ceviche&quot;],[&quot;Rous&quot;,&quot;3&quot;,&quot;Ceviche&quot;]]

  <strong>Output:</strong> [[&quot;Table&quot;,&quot;Beef Burrito&quot;,&quot;Ceviche&quot;,&quot;Fried Chicken&quot;,&quot;Water&quot;],[&quot;3&quot;,&quot;0&quot;,&quot;2&quot;,&quot;1&quot;,&quot;0&quot;],[&quot;5&quot;,&quot;0&quot;,&quot;1&quot;,&quot;0&quot;,&quot;1&quot;],[&quot;10&quot;,&quot;1&quot;,&quot;0&quot;,&quot;0&quot;,&quot;0&quot;]] 

  <strong>Explanation:

  </strong>The displaying table looks like:

  <strong>Table,Beef Burrito,Ceviche,Fried Chicken,Water</strong>

  3    ,0           ,2      ,1            ,0

  5    ,0           ,1      ,0            ,1

  10   ,1           ,0      ,0            ,0

  For the table 3: David orders &quot;Ceviche&quot; and &quot;Fried Chicken&quot;, and Rous orders &quot;Ceviche&quot;.

  For the table 5: Carla orders &quot;Water&quot; and &quot;Ceviche&quot;.

  For the table 10: Corina orders &quot;Beef Burrito&quot;. 

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> orders = [[&quot;James&quot;,&quot;12&quot;,&quot;Fried Chicken&quot;],[&quot;Ratesh&quot;,&quot;12&quot;,&quot;Fried Chicken&quot;],[&quot;Amadeus&quot;,&quot;12&quot;,&quot;Fried Chicken&quot;],[&quot;Adam&quot;,&quot;1&quot;,&quot;Canadian Waffles&quot;],[&quot;Brianna&quot;,&quot;1&quot;,&quot;Canadian Waffles&quot;]]

  <strong>Output:</strong> [[&quot;Table&quot;,&quot;Canadian Waffles&quot;,&quot;Fried Chicken&quot;],[&quot;1&quot;,&quot;2&quot;,&quot;0&quot;],[&quot;12&quot;,&quot;0&quot;,&quot;3&quot;]] 

  <strong>Explanation:</strong> 

  For the table 1: Adam and Brianna order &quot;Canadian Waffles&quot;.

  For the table 12: James, Ratesh and Amadeus order &quot;Fried Chicken&quot;.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> orders = [[&quot;Laura&quot;,&quot;2&quot;,&quot;Bean Burrito&quot;],[&quot;Jhon&quot;,&quot;2&quot;,&quot;Beef Burrito&quot;],[&quot;Melissa&quot;,&quot;2&quot;,&quot;Soda&quot;]]

  <strong>Output:</strong> [[&quot;Table&quot;,&quot;Bean Burrito&quot;,&quot;Beef Burrito&quot;,&quot;Soda&quot;],[&quot;2&quot;,&quot;1&quot;,&quot;1&quot;,&quot;1&quot;]]

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= orders.length <= 5 * 10^4

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

orders[i].length == 3

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= customerNamei.length, foodItemi.length <= 20

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

customerNamei and foodItemi consist of lowercase and uppercase English
letters and the space character.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

tableNumberi is a valid integer between 1 and 500.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
