* [[https://leetcode.com/problems/my-calendar-iii][732. My Calendar
III]]
  :PROPERTIES:
  :CUSTOM_ID: my-calendar-iii
  :END:
[[./solution/0700-0799/0732.My Calendar III/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

A k-booking happens when k events have some non-empty intersection
(i.e., there is some time that is common to all k events.)

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

You are given some events [start, end), after each given event, return
an integer k representing the maximum k-booking between all the previous
events.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Implement the MyCalendarThree class:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

MyCalendarThree() Initializes the object.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

int book(int start, int end) Returns an integer k representing the
largest integer such that there exists a k-booking in the calendar.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input</strong>
  [&quot;MyCalendarThree&quot;, &quot;book&quot;, &quot;book&quot;, &quot;book&quot;, &quot;book&quot;, &quot;book&quot;, &quot;book&quot;]
  [[], [10, 20], [50, 60], [10, 40], [5, 15], [5, 10], [25, 55]]
  <strong>Output</strong>
  [null, 1, 1, 2, 3, 3, 3]

  <strong>Explanation</strong>
  MyCalendarThree myCalendarThree = new MyCalendarThree();
  myCalendarThree.book(10, 20); // return 1, The first event can be booked and is disjoint, so the maximum k-booking is a 1-booking.
  myCalendarThree.book(50, 60); // return 1, The second event can be booked and is disjoint, so the maximum k-booking is a 1-booking.
  myCalendarThree.book(10, 40); // return 2, The third event [10, 40) intersects the first event, and the maximum k-booking is a 2-booking.
  myCalendarThree.book(5, 15); // return 3, The remaining events cause the maximum K-booking to be only a 3-booking.
  myCalendarThree.book(5, 10); // return 3
  myCalendarThree.book(25, 55); // return 3
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= start < end <= 109

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

At most 400 calls will be made to book.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
