* [[https://leetcode.com/problems/bag-of-tokens][948. Bag of Tokens]]
  :PROPERTIES:
  :CUSTOM_ID: bag-of-tokens
  :END:
[[./solution/0900-0999/0948.Bag of Tokens/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

You have an initial power of P, an initial score of 0, and a bag of
tokens where tokens[i] is the value of the ith token (0-indexed).

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Your goal is to maximize your total score by potentially playing each
token in one of two ways:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

If your current power is at least tokens[i], you may play the ith token
face up, losing tokens[i] power and gaining 1 score.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

If your current score is at least 1, you may play the ith token face
down, gaining tokens[i] power and losing 1 score.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

#+begin_html
  <p>
#+end_html

Each token may be played at most once and in any order. You do not have
to play all the tokens.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the largest possible score you can achieve after playing any
number of tokens.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> tokens = [100], P = 50

  <strong>Output:</strong> 0

  <strong>Explanation</strong><strong>:</strong> Playing the only token in the bag is impossible because you either have too little power or too little score.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> tokens = [100,200], P = 150

  <strong>Output:</strong> 1

  <strong>Explanation:</strong> Play the 0<sup>th</sup> token (100) face up, your power becomes 50 and score becomes 1.

  There is no need to play the 1<sup>st</sup> token since you cannot play it face up to add to your score.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> tokens = [100,200,300,400], P = 200

  <strong>Output:</strong> 2

  <strong>Explanation:</strong> Play the tokens in this order to get a score of 2:

  1. Play the 0<sup>th</sup> token (100) face up, your power becomes 100 and score becomes 1.

  2. Play the 3<sup>rd</sup> token (400) face down, your power becomes 500 and score becomes 0.

  3. Play the 1<sup>st</sup> token (200) face up, your power becomes 300 and score becomes 1.

  4. Play the 2<sup>nd </sup>token (300) face up, your power becomes 0 and score becomes 2.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= tokens.length <= 1000

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= tokens[i], P < 104

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
