* [[https://leetcode.com/problems/course-schedule-iii][630. Course
Schedule III]]
  :PROPERTIES:
  :CUSTOM_ID: course-schedule-iii
  :END:
[[./solution/0600-0699/0630.Course Schedule III/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

There are n different online courses numbered from 1 to n. Each course
has some duration(course length) t and closed on dth day. A course
should be taken continuously for t days and must be finished before or
on the dth day. You will start at the 1st day.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Given n online courses represented by pairs (t,d), your task is to find
the maximal number of courses that can be taken.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <b>Input:</b> [[100, 200], [200, 1300], [1000, 1250], [2000, 3200]]

  <b>Output:</b> 3

  <b>Explanation:</b> 

  There&#39;re totally 4 courses, but you can take 3 courses at most:

  First, take the 1st course, it costs 100 days so you will finish it on the 100th day, and ready to take the next course on the 101st day.

  Second, take the 3rd course, it costs 1000 days so you will finish it on the 1100th day, and ready to take the next course on the 1101st day. 

  Third, take the 2nd course, it costs 200 days so you will finish it on the 1300th day. 

  The 4th course cannot be taken now, since you will finish it on the 3300th day, which exceeds the closed date.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Note:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ol>
#+end_html

#+begin_html
  <li>
#+end_html

The integer 1 <= d, t, n <= 10,000.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

You can't take two courses simultaneously.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ol>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
