* [[https://leetcode.com/problems/number-of-good-ways-to-split-a-string][1525.
Number of Good Ways to Split a String]]
  :PROPERTIES:
  :CUSTOM_ID: number-of-good-ways-to-split-a-string
  :END:
[[./solution/1500-1599/1525.Number of Good Ways to Split a String/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

You are given a string s, a split is called good if you can split s into
2 non-empty strings p and q where its concatenation is equal to s and
the number of distinct letters in p and q are the same.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the number of good splits you can make in s.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> s = &quot;aacaba&quot;

  <strong>Output:</strong> 2

  <strong>Explanation:</strong> There are 5 ways to split <code>&quot;aacaba&quot;</code> and 2 of them are good. 

  (&quot;a&quot;, &quot;acaba&quot;) Left string and right string contains 1 and 3 different letters respectively.

  (&quot;aa&quot;, &quot;caba&quot;) Left string and right string contains 1 and 3 different letters respectively.

  (&quot;aac&quot;, &quot;aba&quot;) Left string and right string contains 2 and 2 different letters respectively (good split).

  (&quot;aaca&quot;, &quot;ba&quot;) Left string and right string contains 2 and 2 different letters respectively (good split).

  (&quot;aacab&quot;, &quot;a&quot;) Left string and right string contains 3 and 1 different letters respectively.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> s = &quot;abcd&quot;

  <strong>Output:</strong> 1

  <strong>Explanation: </strong>Split the string as follows (&quot;ab&quot;, &quot;cd&quot;).

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> s = &quot;aaaaa&quot;

  <strong>Output:</strong> 4

  <strong>Explanation: </strong>All possible splits are good.</pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 4:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> s = &quot;acbadbaada&quot;

  <strong>Output:</strong> 2

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

s contains only lowercase English letters.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= s.length <= 10^5

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
