* [[https://leetcode.com/problems/stone-game-iii][1406. Stone Game III]]
  :PROPERTIES:
  :CUSTOM_ID: stone-game-iii
  :END:
[[./solution/1400-1499/1406.Stone Game III/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Alice and Bob continue their games with piles of stones. There are
several stones arranged in a row, and each stone has an associated value
which is an integer given in the array stoneValue.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Alice and Bob take turns, with Alice starting first. On each player's
turn, that player can take 1, 2 or 3 stones from the first remaining
stones in the row.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

The score of each player is the sum of values of the stones taken. The
score of each player is 0 initially.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

The objective of the game is to end with the highest score, and the
winner is the player with the highest score and there could be a tie.
The game continues until all the stones have been taken.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Assume Alice and Bob play optimally.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return "Alice" if Alice will win, "Bob" if Bob will win or "Tie" if they
end the game with the same score.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> values = [1,2,3,7]

  <strong>Output:</strong> &quot;Bob&quot;

  <strong>Explanation:</strong> Alice will always lose. Her best move will be to take three piles and the score become 6. Now the score of Bob is 7 and Bob wins.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> values = [1,2,3,-9]

  <strong>Output:</strong> &quot;Alice&quot;

  <strong>Explanation:</strong> Alice must choose all the three piles at the first move to win and leave Bob with negative score.

  If Alice chooses one pile her score will be 1 and the next move Bob&#39;s score becomes 5. The next move Alice will take the pile with value = -9 and lose.

  If Alice chooses two piles her score will be 3 and the next move Bob&#39;s score becomes 3. The next move Alice will take the pile with value = -9 and also lose.

  Remember that both play optimally so here Alice will choose the scenario that makes her win.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> values = [1,2,3,6]

  <strong>Output:</strong> &quot;Tie&quot;

  <strong>Explanation:</strong> Alice cannot win this game. She can end the game in a draw if she decided to choose all the first three piles, otherwise she will lose.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 4:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> values = [1,2,3,-1,-2,-3,7]

  <strong>Output:</strong> &quot;Alice&quot;

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 5:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> values = [-1,-2,-3]

  <strong>Output:</strong> &quot;Tie&quot;

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= values.length <= 50000

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

-1000 <= values[i] <= 1000

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
