* [[https://leetcode.com/problems/ambiguous-coordinates][816. Ambiguous
Coordinates]]
  :PROPERTIES:
  :CUSTOM_ID: ambiguous-coordinates
  :END:
[[./solution/0800-0899/0816.Ambiguous Coordinates/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

We had some 2-dimensional coordinates, like "(1, 3)" or "(2, 0.5)". 
Then, we removed all commas, decimal points, and spaces, and ended up
with the string S.  Return a list of strings representing all
possibilities for what our original coordinates could have been.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Our original representation never had extraneous zeroes, so we never
started with numbers like "00", "0.0", "0.00", "1.0", "001", "00.01", or
any other number that can be represented with less digits.  Also, a
decimal point within a number never occurs without at least one digit
occuring before it, so we never started with numbers like ".1".

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

The final answer list can be returned in any order.  Also note that all
coordinates in the final answer have exactly one space between them
(occurring after the comma.)

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Example 1:</strong>

  <strong>Input:</strong> &quot;(123)&quot;

  <strong>Output:</strong> [&quot;(1, 23)&quot;, &quot;(12, 3)&quot;, &quot;(1.2, 3)&quot;, &quot;(1, 2.3)&quot;]

  </pre>
#+end_html

#+begin_html
  <pre>

  <strong>Example 2:</strong>

  <strong>Input:</strong> &quot;(00011)&quot;

  <strong>Output:</strong> &nbsp;[&quot;(0.001, 1)&quot;, &quot;(0, 0.011)&quot;]

  <strong>Explanation:</strong> 

  0.0, 00, 0001 or 00.01 are not allowed.

  </pre>
#+end_html

#+begin_html
  <pre>

  <strong>Example 3:</strong>

  <strong>Input:</strong> &quot;(0123)&quot;

  <strong>Output:</strong> [&quot;(0, 123)&quot;, &quot;(0, 12.3)&quot;, &quot;(0, 1.23)&quot;, &quot;(0.1, 23)&quot;, &quot;(0.1, 2.3)&quot;, &quot;(0.12, 3)&quot;]

  </pre>
#+end_html

#+begin_html
  <pre>

  <strong>Example 4:</strong>

  <strong>Input:</strong> &quot;(100)&quot;

  <strong>Output:</strong> [(10, 0)]

  <strong>Explanation:</strong> 

  1.0 is not allowed.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Note:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

4 <= S.length <= 12.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

S[0] = "(", S[S.length - 1] = ")", and the other elements in S are
digits.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
