* [[https://leetcode.com/problems/minimum-subsequence-in-non-increasing-order][1403.
Minimum Subsequence in Non-Increasing Order]]
  :PROPERTIES:
  :CUSTOM_ID: minimum-subsequence-in-non-increasing-order
  :END:
[[./solution/1400-1499/1403.Minimum Subsequence in Non-Increasing Order/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Given the array nums, obtain a subsequence of the array whose sum of
elements is strictly greater than the sum of the non included elements
in such subsequence. 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

If there are multiple solutions, return the subsequence with minimum
size and if there still exist multiple solutions, return the subsequence
with the maximum total sum of all its elements. A subsequence of an
array can be obtained by erasing some (possibly zero) elements from the
array. 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Note that the solution with the given constraints is guaranteed to
be unique. Also return the answer sorted in non-increasing order.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> nums = [4,3,10,9,8]

  <strong>Output:</strong> [10,9] 

  <strong>Explanation:</strong> The subsequences [10,9] and [10,8] are minimal such that the sum of their elements is strictly greater than the sum of elements not included, however, the subsequence [10,9] has the maximum total sum of its elements.&nbsp;

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> nums = [4,4,7,6,7]

  <strong>Output:</strong> [7,7,6] 

  <strong>Explanation:</strong> The subsequence [7,7] has the sum of its elements equal to 14 which is not strictly greater than the sum of elements not included (14 = 4 + 4 + 6). Therefore, the subsequence [7,6,7] is the minimal satisfying the conditions. Note the subsequence has to returned in non-decreasing order.  

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> nums = [6]

  <strong>Output:</strong> [6]

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= nums.length <= 500

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= nums[i] <= 100

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
