* [[https://leetcode.com/problems/smallest-string-with-swaps][1202.
Smallest String With Swaps]]
  :PROPERTIES:
  :CUSTOM_ID: smallest-string-with-swaps
  :END:
[[./solution/1200-1299/1202.Smallest String With Swaps/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

You are given a string s, and an array of pairs of indices in the
string pairs where pairs[i] = [a, b] indicates 2 indices(0-indexed) of
the string.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

You can swap the characters at any pair of indices in the
given pairs any number of times.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the lexicographically smallest string that s can be changed to
after using the swaps.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> s = &quot;dcab&quot;, pairs = [[0,3],[1,2]]
  <strong>Output:</strong> &quot;bacd&quot;
  <strong>Explaination:</strong> 
  Swap s[0] and s[3], s = &quot;bcad&quot;
  Swap s[1] and s[2], s = &quot;bacd&quot;
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> s = &quot;dcab&quot;, pairs = [[0,3],[1,2],[0,2]]
  <strong>Output:</strong> &quot;abcd&quot;
  <strong>Explaination: </strong>
  Swap s[0] and s[3], s = &quot;bcad&quot;
  Swap s[0] and s[2], s = &quot;acbd&quot;
  Swap s[1] and s[2], s = &quot;abcd&quot;</pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> s = &quot;cba&quot;, pairs = [[0,1],[1,2]]
  <strong>Output:</strong> &quot;abc&quot;
  <strong>Explaination: </strong>
  Swap s[0] and s[1], s = &quot;bca&quot;
  Swap s[1] and s[2], s = &quot;bac&quot;
  Swap s[0] and s[1], s = &quot;abc&quot;
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= s.length <= 10^5

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= pairs.length <= 10^5

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= pairs[i][0], pairs[i][1] < s.length

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

s only contains lower case English letters.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
