* [[https://leetcode.com/problems/detect-pattern-of-length-m-repeated-k-or-more-times][1566.
Detect Pattern of Length M Repeated K or More Times]]
  :PROPERTIES:
  :CUSTOM_ID: detect-pattern-of-length-m-repeated-k-or-more-times
  :END:
[[./solution/1500-1599/1566.Detect Pattern of Length M Repeated K or More Times/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Given an array of positive integers arr,  find a pattern of length m
that is repeated k or more times.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

A pattern is a subarray (consecutive sub-sequence) that consists of one
or more values, repeated multiple times consecutively without
overlapping. A pattern is defined by its length and the number of
repetitions.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return true if there exists a pattern of length m that is repeated k or
more times, otherwise return false.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> arr = [1,2,4,4,4,4], m = 1, k = 3
  <strong>Output:</strong> true
  <strong>Explanation: </strong>The pattern <strong>(4)</strong> of length 1 is repeated 4 consecutive times. Notice that pattern can be repeated k or more times but not less.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> arr = [1,2,1,2,1,1,1,3], m = 2, k = 2
  <strong>Output:</strong> true
  <strong>Explanation: </strong>The pattern <strong>(1,2)</strong> of length 2 is repeated 2 consecutive times. Another valid pattern <strong>(2,1) is</strong> also repeated 2 times.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> arr = [1,2,1,2,1,3], m = 2, k = 3
  <strong>Output:</strong> false
  <strong>Explanation: </strong>The pattern (1,2) is of length 2 but is repeated only 2 times. There is no pattern of length 2 that is repeated 3 or more times.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 4:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> arr = [1,2,3,1,2], m = 2, k = 2
  <strong>Output:</strong> false
  <strong>Explanation: </strong>Notice that the pattern (1,2) exists twice but not consecutively, so it doesn&#39;t count.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 5:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> arr = [2,2,2,2], m = 2, k = 3
  <strong>Output:</strong> false
  <strong>Explanation: </strong>The only pattern of length 2 is (2,2) however it&#39;s repeated only twice. Notice that we do not count overlapping repetitions.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

2 <= arr.length <= 100

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= arr[i] <= 100

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= m <= 100

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

2 <= k <= 100

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
