* [[https://leetcode.com/problems/maximum-number-of-coins-you-can-get][1561.
Maximum Number of Coins You Can Get]]
  :PROPERTIES:
  :CUSTOM_ID: maximum-number-of-coins-you-can-get
  :END:
[[./solution/1500-1599/1561.Maximum Number of Coins You Can Get/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

There are 3n piles of coins of varying size, you and your friends will
take piles of coins as follows:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

In each step, you will choose any 3 piles of coins (not necessarily
consecutive).

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Of your choice, Alice will pick the pile with the maximum number of
coins.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

You will pick the next pile with maximum number of coins.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Your friend Bob will pick the last pile.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Repeat until there are no more piles of coins.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

#+begin_html
  <p>
#+end_html

Given an array of integers piles where piles[i] is the number of coins
in the ith pile.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the maximum number of coins which you can have.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> piles = [2,4,1,2,7,8]
  <strong>Output:</strong> 9
  <strong>Explanation: </strong>Choose the triplet (2, 7, 8), Alice Pick the pile with 8 coins, you the pile with <strong>7</strong> coins and Bob the last one.
  Choose the triplet (1, 2, 4), Alice Pick the pile with 4 coins, you the pile with <strong>2</strong> coins and Bob the last one.
  The maximum number of coins which you can have are: 7 + 2 = 9.
  On the other hand if we choose this arrangement (1, <strong>2</strong>, 8), (2, <strong>4</strong>, 7) you only get 2 + 4 = 6 coins which is not optimal.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> piles = [2,4,5]
  <strong>Output:</strong> 4
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> piles = [9,8,7,6,5,1,2,3,4]
  <strong>Output:</strong> 18
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

3 <= piles.length <= 10^5

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

piles.length % 3 == 0

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= piles[i] <= 10^4

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
