* [[https://leetcode.com/problems/dungeon-game][174. Dungeon Game]]
  :PROPERTIES:
  :CUSTOM_ID: dungeon-game
  :END:
[[./solution/0100-0199/0174.Dungeon Game/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

The demons had captured the princess and imprisoned her in the
bottom-right corner of a dungeon. The dungeon consists of m x n rooms
laid out in a 2D grid. Our valiant knight was initially positioned in
the top-left room and must fight his way through dungeon to rescue the
princess.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

The knight has an initial health point represented by a positive
integer. If at any point his health point drops to 0 or below, he dies
immediately.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Some of the rooms are guarded by demons (represented by negative
integers), so the knight loses health upon entering these rooms; other
rooms are either empty (represented as 0) or contain magic orbs that
increase the knight's health (represented by positive integers).

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

To reach the princess as quickly as possible, the knight decides to move
only rightward or downward in each step.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the knight's minimum initial health so that he can rescue the
princess.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Note that any room can contain threats or power-ups, even the first room
the knight enters and the bottom-right room where the princess is
imprisoned.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> dungeon = [[-2,-3,3],[-5,-10,1],[10,30,-5]]
  <strong>Output:</strong> 7
  <strong>Explanation:</strong> The initial health of the knight must be at least 7 if he follows the optimal path: RIGHT-&gt; RIGHT -&gt; DOWN -&gt; DOWN.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> dungeon = [[0]]
  <strong>Output:</strong> 1
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

m == dungeon.length

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

n == dungeon[i].length

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= m, n <= 200

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

-1000 <= dungeon[i][j] <= 1000

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
