* [[https://leetcode.com/problems/number-of-operations-to-make-network-connected][1319.
Number of Operations to Make Network Connected]]
  :PROPERTIES:
  :CUSTOM_ID: number-of-operations-to-make-network-connected
  :END:
[[./solution/1300-1399/1319.Number of Operations to Make Network Connected/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

There are n computers numbered from 0 to n-1 connected by ethernet
cables connections forming a network where connections[i] = [a,
b] represents a connection between computers a and b. Any computer can
reach any other computer directly or indirectly through the network.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Given an initial computer network connections. You can extract certain
cables between two directly connected computers, and place them between
any pair of disconnected computers to make them directly connected.
Return the minimum number of times you need to do this in order to make
all the computers connected. If it's not possible, return -1. 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> n = 4, connections = [[0,1],[0,2],[1,2]]
  <strong>Output:</strong> 1
  <strong>Explanation:</strong> Remove cable between computer 1 and 2 and place between computers 1 and 3.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> n = 6, connections = [[0,1],[0,2],[0,3],[1,2],[1,3]]
  <strong>Output:</strong> 2
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> n = 6, connections = [[0,1],[0,2],[0,3],[1,2]]
  <strong>Output:</strong> -1
  <strong>Explanation:</strong> There are not enough cables.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 4:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> n = 5, connections = [[0,1],[0,2],[3,4],[2,3]]
  <strong>Output:</strong> 0
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= n <= 10^5

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= connections.length <= min(n*(n-1)/2, 10^5)

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

connections[i].length == 2

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= connections[i][0], connections[i][1] < n

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

connections[i][0] != connections[i][1]

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

There are no repeated connections.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

No two computers are connected by more than one cable.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
