* [[https://leetcode.com/problems/count-good-nodes-in-binary-tree][1448.
Count Good Nodes in Binary Tree]]
  :PROPERTIES:
  :CUSTOM_ID: count-good-nodes-in-binary-tree
  :END:
[[./solution/1400-1499/1448.Count Good Nodes in Binary Tree/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Given a binary tree root, a node X in the tree is named good if in the
path from root to X there are no nodes with a value greater than X.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the number of good nodes in the binary tree.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> root = [3,1,4,3,null,1,5]

  <strong>Output:</strong> 4

  <strong>Explanation:</strong> Nodes in blue are <strong>good</strong>.

  Root Node (3) is always a good node.

  Node 4 -&gt; (3,4) is the maximum value in the path starting from the root.

  Node 5 -&gt; (3,4,5) is the maximum value in the path

  Node 3 -&gt; (3,1,3) is the maximum value in the path.</pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> root = [3,3,null,4,2]

  <strong>Output:</strong> 3

  <strong>Explanation:</strong> Node 2 -&gt; (3, 3, 2) is not good, because &quot;3&quot; is higher than it.</pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> root = [1]

  <strong>Output:</strong> 1

  <strong>Explanation:</strong> Root is considered as <strong>good</strong>.</pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

The number of nodes in the binary tree is in the range [1, 10^5].

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Each node's value is between [-10^4, 10^4].

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
