* [[https://leetcode.com/problems/building-boxes][1739. Building Boxes]]
  :PROPERTIES:
  :CUSTOM_ID: building-boxes
  :END:
[[./solution/1700-1799/1739.Building Boxes/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

You have a cubic storeroom where the width, length, and height of the
room are all equal to n units. You are asked to place n boxes in this
room where each box is a cube of unit side length. There are however
some rules to placing the boxes:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

You can place the boxes anywhere on the floor.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

If box x is placed on top of the box y, then each side of the four
vertical sides of the box y must either be adjacent to another box or to
a wall.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

#+begin_html
  <p>
#+end_html

Given an integer n, return the minimum possible number of boxes touching
the floor.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> n = 3
  <strong>Output:</strong> 3
  <strong>Explanation:</strong> The figure above is for the placement of the three boxes.
  These boxes are placed in the corner of the room, where the corner is on the left side.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> n = 4
  <strong>Output:</strong> 3
  <strong>Explanation:</strong> The figure above is for the placement of the four boxes.
  These boxes are placed in the corner of the room, where the corner is on the left side.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> n = 10
  <strong>Output:</strong> 6
  <strong>Explanation:</strong> The figure above is for the placement of the ten boxes.
  These boxes are placed in the corner of the room, where the corner is on the back side.</pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= n <= 109

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
