* [[https://leetcode.com/problems/moving-stones-until-consecutive][1033.
Moving Stones Until Consecutive]]
  :PROPERTIES:
  :CUSTOM_ID: moving-stones-until-consecutive
  :END:
[[./solution/1000-1099/1033.Moving Stones Until Consecutive/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Three stones are on a number line at positions a, b, and c.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Each turn, you pick up a stone at an endpoint (ie., either the lowest or
highest position stone), and move it to an unoccupied position between
those endpoints.  Formally, let's say the stones are currently at
positions x, y, z with x < y < z.  You pick up the stone at either
position x or position z, and move that stone to an integer position k,
with x < k < z and k != y.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

The game ends when you cannot make any more moves, ie. the stones are in
consecutive positions.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

When the game ends, what is the minimum and maximum number of moves that
you could have made?  Return the answer as an length 2 array: answer =
[minimum_moves, maximum_moves]

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input: </strong>a = <span id="example-input-1-1">1</span>, b = <span id="example-input-1-2">2</span>, c = <span id="example-input-1-3">5</span>

  <strong>Output: </strong><span id="example-output-1">[1,2]</span>

  <strong>Explanation: </strong>Move the stone from 5 to 3, or move the stone from 5 to 4 to 3.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input: </strong>a = <span id="example-input-2-1">4</span>, b = <span id="example-input-2-2">3</span>, c = <span id="example-input-2-3">2</span>

  <strong>Output: </strong><span id="example-output-2">[0,0]</span>

  <strong>Explanation: </strong>We cannot make any moves.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input: </strong>a = <span id="example-input-3-1">3</span>, b = <span id="example-input-3-2">5</span>, c = <span id="example-input-3-3">1</span>

  <strong>Output: </strong><span id="example-output-3">[1,2]</span>

  <strong>Explanation: </strong>Move the stone from 1 to 4; or move the stone from 1 to 2 to 4.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Note:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ol>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= a <= 100

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= b <= 100

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= c <= 100

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

a != b, b != c, c != a

#+begin_html
  </li>
#+end_html

#+begin_html
  </ol>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

 

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
