* [[https://leetcode.com/problems/minimum-cost-to-merge-stones][1000.
Minimum Cost to Merge Stones]]
  :PROPERTIES:
  :CUSTOM_ID: minimum-cost-to-merge-stones
  :END:
[[./solution/1000-1099/1000.Minimum Cost to Merge Stones/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

There are N piles of stones arranged in a row.  The i-th pile has
stones[i] stones.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

A move consists of merging exactly K consecutive piles into one pile,
and the cost of this move is equal to the total number of stones in
these K piles.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Find the minimum cost to merge all piles of stones into one pile.  If it
is impossible, return -1.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input: </strong>stones = <span id="example-input-1-1">[3,2,4,1]</span>, K = <span id="example-input-1-2">2</span>

  <strong>Output: </strong><span id="example-output-1">20</span>

  <strong>Explanation: </strong>

  We start with [3, 2, 4, 1].

  We merge [3, 2] for a cost of 5, and we are left with [5, 4, 1].

  We merge [4, 1] for a cost of 5, and we are left with [5, 5].

  We merge [5, 5] for a cost of 10, and we are left with [10].

  The total cost was 20, and this is the minimum possible.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input: </strong>stones = <span id="example-input-2-1">[3,2,4,1]</span>, K = <span id="example-input-2-2">3</span>

  <strong>Output: </strong><span id="example-output-2">-1</span>

  <strong>Explanation: </strong>After any merge operation, there are 2 piles left, and we can&#39;t merge anymore.  So the task is impossible.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input: </strong>stones = <span id="example-input-3-1">[3,5,1,2,6]</span>, K = <span id="example-input-3-2">3</span>

  <strong>Output: </strong><span id="example-output-3">25</span>

  <strong>Explanation: </strong>

  We start with [3, 5, 1, 2, 6].

  We merge [5, 1, 2] for a cost of 8, and we are left with [3, 8, 6].

  We merge [3, 8, 6] for a cost of 17, and we are left with [17].

  The total cost was 25, and this is the minimum possible.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Note:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= stones.length <= 30

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

2 <= K <= 30

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= stones[i] <= 100

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html

#+begin_html
  <!-- tabs:end -->
#+end_html
