* [[https://leetcode.com/problems/restore-the-array][1416. Restore The
Array]]
  :PROPERTIES:
  :CUSTOM_ID: restore-the-array
  :END:
[[./solution/1400-1499/1416.Restore The Array/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

A program was supposed to print an array of integers. The program forgot
to print whitespaces and the array is printed as a string of digits and
all we know is that all integers in the array were in the range [1,
k] and there are no leading zeros in the array.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Given the string s and the integer k. There can be multiple ways to
restore the array.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the number of possible array that can be printed as a string
s using the mentioned program.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

The number of ways could be very large so return it modulo 10^9 + 7

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> s = &quot;1000&quot;, k = 10000

  <strong>Output:</strong> 1

  <strong>Explanation:</strong> The only possible array is [1000]

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> s = &quot;1000&quot;, k = 10

  <strong>Output:</strong> 0

  <strong>Explanation:</strong> There cannot be an array that was printed this way and has all integer &gt;= 1 and &lt;= 10.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> s = &quot;1317&quot;, k = 2000

  <strong>Output:</strong> 8

  <strong>Explanation:</strong> Possible arrays are [1317],[131,7],[13,17],[1,317],[13,1,7],[1,31,7],[1,3,17],[1,3,1,7]

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 4:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> s = &quot;2020&quot;, k = 30

  <strong>Output:</strong> 1

  <strong>Explanation:</strong> The only possible array is [20,20]. [2020] is invalid because 2020 &gt; 30. [2,020] is ivalid because 020 contains leading zeros.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 5:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> s = &quot;1234567890&quot;, k = 90

  <strong>Output:</strong> 34

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= s.length <= 10^5.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

s consists of only digits and doesn't contain leading zeros.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= k <= 10^9.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
