* [[https://leetcode.com/problems/course-schedule-iv][1462. Course
Schedule IV]]
  :PROPERTIES:
  :CUSTOM_ID: course-schedule-iv
  :END:
[[./solution/1400-1499/1462.Course Schedule IV/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

There are a total of n courses you have to take, labeled from 0 to n-1.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Some courses may have direct prerequisites, for example, to take course
0 you have first to take course 1, which is expressed as a pair: [1,0]

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Given the total number of courses n, a list of direct prerequisite pairs
and a list of queries pairs.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

You should answer for each queries[i] whether the course queries[i][0]
is a prerequisite of the course queries[i][1] or not.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return a list of boolean, the answers to the given queries.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Please note that if course a is a prerequisite of course b and course b
is a prerequisite of course c, then, course a is a prerequisite of
course c.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> n = 2, prerequisites = [[1,0]], queries = [[0,1],[1,0]]
  <strong>Output:</strong> [false,true]
  <strong>Explanation:</strong> course 0 is not a prerequisite of course 1 but the opposite is true.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> n = 2, prerequisites = [], queries = [[1,0],[0,1]]
  <strong>Output:</strong> [false,false]
  <strong>Explanation:</strong> There are no prerequisites and each course is independent.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> n = 3, prerequisites = [[1,2],[1,0],[2,0]], queries = [[1,0],[1,2]]
  <strong>Output:</strong> [true,true]
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 4:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> n = 3, prerequisites = [[1,0],[2,0]], queries = [[0,1],[2,0]]
  <strong>Output:</strong> [false,true]
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 5:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> n = 5, prerequisites = [[0,1],[1,2],[2,3],[3,4]], queries = [[0,4],[4,0],[1,3],[3,0]]
  <strong>Output:</strong> [true,false,true,false]
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

2 <= n <= 100

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= prerequisite.length <= (n * (n - 1) / 2)

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= prerequisite[i][0], prerequisite[i][1] < n

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

prerequisite[i][0] != prerequisite[i][1]

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

The prerequisites graph has no cycles.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

The prerequisites graph has no repeated edges.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= queries.length <= 10^4

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

queries[i][0] != queries[i][1]

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
