* [[https://leetcode.com/problems/ipo][502. IPO]]
  :PROPERTIES:
  :CUSTOM_ID: ipo
  :END:
[[./solution/0500-0599/0502.IPO/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Suppose LeetCode will start its IPO soon. In order to sell a good price
of its shares to Venture Capital, LeetCode would like to work on some
projects to increase its capital before the IPO. Since it has limited
resources, it can only finish at most k distinct projects before the
IPO. Help LeetCode design the best way to maximize its total capital
after finishing at most k distinct projects.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

You are given several projects. For each project i, it has a pure profit
Pi and a minimum capital of Ci is needed to start the corresponding
project. Initially, you have W capital. When you finish a project, you
will obtain its pure profit and the profit will be added to your total
capital.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

To sum up, pick a list of at most k distinct projects from given
projects to maximize your final capital, and output your final maximized
capital.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  <pre>

  <b>Input:</b> k=2, W=0, Profits=[1,2,3], Capital=[0,1,1].



  <b>Output:</b> 4



  <b>Explanation:</b> Since your initial capital is 0, you can only start the project indexed 0.

               After finishing it you will obtain profit 1 and your capital becomes 1.

               With capital 1, you can either start the project indexed 1 or the project indexed 2.

               Since you can choose at most 2 projects, you need to finish the project indexed 2 to get the maximum capital.

               Therefore, output the final maximized capital, which is 0 + 1 + 3 = 4.

  </pre>
#+end_html

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Note:

#+begin_html
  <ol>
#+end_html

#+begin_html
  <li>
#+end_html

You may assume all numbers in the input are non-negative integers.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

The length of Profits array and Capital array will not exceed 50,000.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

The answer is guaranteed to fit in a 32-bit signed integer.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ol>
#+end_html

#+begin_html
  </p>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
