* [[https://leetcode.com/problems/time-needed-to-inform-all-employees][1376.
Time Needed to Inform All Employees]]
  :PROPERTIES:
  :CUSTOM_ID: time-needed-to-inform-all-employees
  :END:
[[./solution/1300-1399/1376.Time Needed to Inform All Employees/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

A company has n employees with a unique ID for each employee from 0 to
n - 1. The head of the company is the one with headID.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Each employee has one direct manager given in the manager array where
manager[i] is the direct manager of the i-th employee, manager[headID] =
-1. Also, it is guaranteed that the subordination relationships have a
tree structure.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

The head of the company wants to inform all the company employees of an
urgent piece of news. He will inform his direct subordinates, and they
will inform their subordinates, and so on until all employees know about
the urgent news.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

The i-th employee needs informTime[i] minutes to inform all of his
direct subordinates (i.e., After informTime[i] minutes, all his direct
subordinates can start spreading the news).

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the number of minutes needed to inform all the employees about
the urgent news.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> n = 1, headID = 0, manager = [-1], informTime = [0]
  <strong>Output:</strong> 0
  <strong>Explanation:</strong> The head of the company is the only employee in the company.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> n = 6, headID = 2, manager = [2,2,-1,2,2,2], informTime = [0,0,1,0,0,0]
  <strong>Output:</strong> 1
  <strong>Explanation:</strong> The head of the company with id = 2 is the direct manager of all the employees in the company and needs 1 minute to inform them all.
  The tree structure of the employees in the company is shown.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> n = 7, headID = 6, manager = [1,2,3,4,5,6,-1], informTime = [0,6,5,4,3,2,1]
  <strong>Output:</strong> 21
  <strong>Explanation:</strong> The head has id = 6. He will inform employee with id = 5 in 1 minute.
  The employee with id = 5 will inform the employee with id = 4 in 2 minutes.
  The employee with id = 4 will inform the employee with id = 3 in 3 minutes.
  The employee with id = 3 will inform the employee with id = 2 in 4 minutes.
  The employee with id = 2 will inform the employee with id = 1 in 5 minutes.
  The employee with id = 1 will inform the employee with id = 0 in 6 minutes.
  Needed time = 1 + 2 + 3 + 4 + 5 + 6 = 21.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 4:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> n = 15, headID = 0, manager = [-1,0,0,1,1,2,2,3,3,4,4,5,5,6,6], informTime = [1,1,1,1,1,1,1,0,0,0,0,0,0,0,0]
  <strong>Output:</strong> 3
  <strong>Explanation:</strong> The first minute the head will inform employees 1 and 2.
  The second minute they will inform employees 3, 4, 5 and 6.
  The third minute they will inform the rest of employees.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 5:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> n = 4, headID = 2, manager = [3,3,-1,2], informTime = [0,0,162,914]
  <strong>Output:</strong> 1076
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= n <= 105

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= headID < n

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

manager.length == n

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= manager[i] < n

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

manager[headID] == -1

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

informTime.length == n

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= informTime[i] <= 1000

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

informTime[i] == 0 if employee i has no subordinates.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

It is guaranteed that all the employees can be informed.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
