* [[https://leetcode.com/problems/card-flipping-game][822. Card Flipping
Game]]
  :PROPERTIES:
  :CUSTOM_ID: card-flipping-game
  :END:
[[./solution/0800-0899/0822.Card Flipping Game/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

On a table are N cards, with a positive integer printed on the front and
back of each card (possibly different).

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

We flip any number of cards, and after we choose one card. 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

If the number X on the back of the chosen card is not on the front of
any card, then this number X is good.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

What is the smallest number that is good?  If no number is good, output
0.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Here, fronts[i] and backs[i] represent the number on the front and back
of card i. 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

A flip swaps the front and back numbers, so the value on the front is
now on the back and vice versa.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> fronts = [1,2,4,4,7], backs = [1,3,4,1,3]

  <strong>Output:</strong> <code>2</code>

  <strong>Explanation:</strong> If we flip the second card, the fronts are <code>[1,3,4,4,7]</code> and the backs are <code>[1,2,4,1,3]</code>.

  We choose the second card, which has number 2 on the back, and it isn&#39;t on the front of any card, so <code>2</code> is good.</pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Note:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ol>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= fronts.length == backs.length <= 1000.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= fronts[i] <= 2000.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= backs[i] <= 2000.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ol>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
