* [[https://leetcode.com/problems/fraction-addition-and-subtraction][592.
Fraction Addition and Subtraction]]
  :PROPERTIES:
  :CUSTOM_ID: fraction-addition-and-subtraction
  :END:
[[./solution/0500-0599/0592.Fraction Addition and Subtraction/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Given a string representing an expression of fraction addition and
subtraction, you need to return the calculation result in string format.
The final result should be irreducible fraction. If your final result is
an integer, say 2, you need to change it to the format of fraction that
has denominator 1. So in this case, 2 should be converted to 2/1.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  <pre>

  <b>Input:</b>"-1/2+1/2"

  <b>Output:</b> "0/1"

  </pre>
#+end_html

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  <pre>

  <b>Input:</b>"-1/2+1/2+1/3"

  <b>Output:</b> "1/3"

  </pre>
#+end_html

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  <pre>

  <b>Input:</b>"1/3-1/2"

  <b>Output:</b> "-1/6"

  </pre>
#+end_html

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 4:

#+begin_html
  <pre>

  <b>Input:</b>"5/3+1/3"

  <b>Output:</b> "2/1"

  </pre>
#+end_html

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Note:

#+begin_html
  <ol>
#+end_html

#+begin_html
  <li>
#+end_html

The input string only contains '0' to '9', '/', '+' and '-'. So does the
output.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Each fraction (input and output) has format ±numerator/denominator. If
the first input fraction or the output is positive, then '+' will be
omitted.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

The input only contains valid irreducible fractions, where the numerator
and denominator of each fraction will always be in the range [1,10]. If
the denominator is 1, it means this fraction is actually an integer in a
fraction format defined above.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

The number of given fractions will be in the range [1,10].

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

The numerator and denominator of the final result are guaranteed to be
valid and in the range of 32-bit int.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ol>
#+end_html

#+begin_html
  </p>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
