* [[https://leetcode.com/problems/decode-xored-array][1720. Decode XORed
Array]]
  :PROPERTIES:
  :CUSTOM_ID: decode-xored-array
  :END:
[[./solution/1700-1799/1720.Decode XORed Array/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

There is a hidden integer array arr that consists of n non-negative
integers.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

It was encoded into another integer array encoded of length n - 1, such
that encoded[i] = arr[i] XOR arr[i + 1]. For example, if arr =
[1,0,2,1], then encoded = [1,2,3].

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

You are given the encoded array. You are also given an integer first,
that is the first element of arr, i.e. arr[0].

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the original array arr. It can be proved that the answer exists
and is unique.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> encoded = [1,2,3], first = 1
  <strong>Output:</strong> [1,0,2,1]
  <strong>Explanation:</strong> If arr = [1,0,2,1], then first = 1 and encoded = [1 XOR 0, 0 XOR 2, 2 XOR 1] = [1,2,3]
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> encoded = [6,2,7,3], first = 4
  <strong>Output:</strong> [4,2,0,7,4]
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

2 <= n <= 104

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

encoded.length == n - 1

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= encoded[i] <= 105

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= first <= 105

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:
XOR.

=a = b ^ c= => =a ^ b = b ^ c ^ b= => =c = a ^ b=.

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
  class Solution:
      def decode(self, encoded: List[int], first: int) -> List[int]:
          res = [first]
          for e in encoded:
              first ^= e
              res.append(first)
          return res
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
  class Solution {
      public int[] decode(int[] encoded, int first) {
          int[] res = new int[encoded.length + 1];
          res[0] = first;
          for (int i = 0; i < encoded.length; ++i) {
              res[i + 1] = res[i] ^ encoded[i];
          }
          return res;
      }
  }
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
