* [[https://leetcode.com/problems/maximum-xor-for-each-query][1829.
Maximum XOR for Each Query]]
  :PROPERTIES:
  :CUSTOM_ID: maximum-xor-for-each-query
  :END:
[[./solution/1800-1899/1829.Maximum XOR for Each Query/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

You are given a sorted array nums of n non-negative integers and an
integer maximumBit. You want to perform the following query n times:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ol>
#+end_html

#+begin_html
  <li>
#+end_html

Find a non-negative integer k < 2maximumBit such that nums[0] XOR
nums[1] XOR ... XOR nums[nums.length-1] XOR k is maximized. k is the
answer to the ith query.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Remove the last element from the current array nums.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ol>
#+end_html

#+begin_html
  <p>
#+end_html

Return an array answer, where answer[i] is the answer to the ith query.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> nums = [0,1,1,3], maximumBit = 2
  <strong>Output:</strong> [0,3,2,3]
  <strong>Explanation</strong>: The queries are answered as follows:
  1<sup>st</sup> query: nums = [0,1,1,3], k = 0 since 0 XOR 1 XOR 1 XOR 3 XOR 0 = 3.
  2<sup>nd</sup> query: nums = [0,1,1], k = 3 since 0 XOR 1 XOR 1 XOR 3 = 3.
  3<sup>rd</sup> query: nums = [0,1], k = 2 since 0 XOR 1 XOR 2 = 3.
  4<sup>th</sup> query: nums = [0], k = 3 since 0 XOR 3 = 3.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> nums = [2,3,4,7], maximumBit = 3
  <strong>Output:</strong> [5,2,6,5]
  <strong>Explanation</strong>: The queries are answered as follows:
  1<sup>st</sup> query: nums = [2,3,4,7], k = 5 since 2 XOR 3 XOR 4 XOR 7 XOR 5 = 7.
  2<sup>nd</sup> query: nums = [2,3,4], k = 2 since 2 XOR 3 XOR 4 XOR 2 = 7.
  3<sup>rd</sup> query: nums = [2,3], k = 6 since 2 XOR 3 XOR 6 = 7.
  4<sup>th</sup> query: nums = [2], k = 5 since 2 XOR 5 = 7.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> nums = [0,1,2,2,5,7], maximumBit = 3
  <strong>Output:</strong> [4,3,6,4,6,7]
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

nums.length == n

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= n <= 105

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= maximumBit <= 20

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= nums[i] < 2maximumBit

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

nums​​​ is sorted in ascending order.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
