* [[https://leetcode.com/problems/check-if-two-string-arrays-are-equivalent][1662.
Check If Two String Arrays are Equivalent]]
  :PROPERTIES:
  :CUSTOM_ID: check-if-two-string-arrays-are-equivalent
  :END:
[[./solution/1600-1699/1662.Check If Two String Arrays are Equivalent/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Given two string arrays word1 and word2, return true if the two arrays
represent the same string, and false otherwise.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

A string is represented by an array if the array elements concatenated
in order forms the string.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> word1 = [&quot;ab&quot;, &quot;c&quot;], word2 = [&quot;a&quot;, &quot;bc&quot;]
  <strong>Output:</strong> true
  <strong>Explanation:</strong>
  word1 represents string &quot;ab&quot; + &quot;c&quot; -&gt; &quot;abc&quot;
  word2 represents string &quot;a&quot; + &quot;bc&quot; -&gt; &quot;abc&quot;
  The strings are the same, so return true.</pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> word1 = [&quot;a&quot;, &quot;cb&quot;], word2 = [&quot;ab&quot;, &quot;c&quot;]
  <strong>Output:</strong> false
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> word1  = [&quot;abc&quot;, &quot;d&quot;, &quot;defg&quot;], word2 = [&quot;abcddefg&quot;]
  <strong>Output:</strong> true
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= word1.length, word2.length <= 103

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= word1[i].length, word2[i].length <= 103

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= sum(word1[i].length), sum(word2[i].length) <= 103

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

word1[i] and word2[i] consist of lowercase letters.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
