* [[https://leetcode.com/problems/minimum-incompatibility][1681. Minimum
Incompatibility]]
  :PROPERTIES:
  :CUSTOM_ID: minimum-incompatibility
  :END:
[[./solution/1600-1699/1681.Minimum Incompatibility/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

You are given an integer array nums​​​ and an integer k. You are asked
to distribute this array into k subsets of equal size such that there
are no two equal elements in the same subset.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

A subset's incompatibility is the difference between the maximum and
minimum elements in that array.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the minimum possible sum of incompatibilities of the k subsets
after distributing the array optimally, or return -1 if it is not
possible.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

A subset is a group integers that appear in the array with no particular
order.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> nums = [1,2,1,4], k = 2
  <strong>Output:</strong> 4
  <strong>Explanation:</strong> The optimal distribution of subsets is [1,2] and [1,4].
  The incompatibility is (2-1) + (4-1) = 4.
  Note that [1,1] and [2,4] would result in a smaller sum, but the first subset contains 2 equal elements.</pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> nums = [6,3,8,1,3,1,2,2], k = 4
  <strong>Output:</strong> 6
  <strong>Explanation:</strong> The optimal distribution of subsets is [1,2], [2,3], [6,8], and [1,3].
  The incompatibility is (2-1) + (3-2) + (8-6) + (3-1) = 6.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> nums = [5,3,3,6,3,3], k = 3
  <strong>Output:</strong> -1
  <strong>Explanation:</strong> It is impossible to distribute nums into 3 subsets where no two elements are equal in the same subset.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= k <= nums.length <= 16

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

nums.length is divisible by k

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= nums[i] <= nums.length

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
