* [[https://leetcode.com/problems/minimum-difficulty-of-a-job-schedule][1335.
Minimum Difficulty of a Job Schedule]]
  :PROPERTIES:
  :CUSTOM_ID: minimum-difficulty-of-a-job-schedule
  :END:
[[./solution/1300-1399/1335.Minimum Difficulty of a Job Schedule/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

You want to schedule a list of jobs in d days. Jobs are dependent (i.e
To work on the i-th job, you have to finish all the jobs j where 0 <= j
< i).

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

You have to finish at least one task every day. The difficulty of a job
schedule is the sum of difficulties of each day of the d days. The
difficulty of a day is the maximum difficulty of a job done in that day.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Given an array of integers jobDifficulty and an integer d. The
difficulty of the i-th job is jobDifficulty[i].

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the minimum difficulty of a job schedule. If you cannot find a
schedule for the jobs return -1.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> jobDifficulty = [6,5,4,3,2,1], d = 2

  <strong>Output:</strong> 7

  <strong>Explanation:</strong> First day you can finish the first 5 jobs, total difficulty = 6.

  Second day you can finish the last job, total difficulty = 1.

  The difficulty of the schedule = 6 + 1 = 7 

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> jobDifficulty = [9,9,9], d = 4

  <strong>Output:</strong> -1

  <strong>Explanation:</strong> If you finish a job per day you will still have a free day. you cannot find a schedule for the given jobs.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> jobDifficulty = [1,1,1], d = 3

  <strong>Output:</strong> 3

  <strong>Explanation:</strong> The schedule is one job per day. total difficulty will be 3.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 4:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> jobDifficulty = [7,1,7,1,7,1], d = 3

  <strong>Output:</strong> 15

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 5:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> jobDifficulty = [11,111,22,222,33,333,44,444], d = 6

  <strong>Output:</strong> 843

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= jobDifficulty.length <= 300

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= jobDifficulty[i] <= 1000

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= d <= 10

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
