* [[https://leetcode.com/problems/string-transforms-into-another-string][1153.
String Transforms Into Another String]]
  :PROPERTIES:
  :CUSTOM_ID: string-transforms-into-another-string
  :END:
[[./solution/1100-1199/1153.String Transforms Into Another String/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Given two strings str1 and str2 of the same length, determine whether
you can transform str1 into str2 by doing zero or more conversions.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

In one conversion you can convert all occurrences of one character in
str1 to any other lowercase English character.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return true if and only if you can transform str1 into str2.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> str1 = &quot;aabcc&quot;, str2 = &quot;ccdee&quot;
  <strong>Output:</strong> true
  <strong>Explanation: </strong>Convert &#39;c&#39; to &#39;e&#39; then &#39;b&#39; to &#39;d&#39; then &#39;a&#39; to &#39;c&#39;. Note that the order of conversions matter.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> str1 = &quot;leetcode&quot;, str2 = &quot;codeleet&quot;
  <strong>Output:</strong> false
  <strong>Explanation: </strong>There is no way to transform str1 to str2.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= str1.length == str2.length <= 104

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

str1 and str2 contain only lowercase English letters.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
