* [[https://leetcode.com/problems/remove-palindromic-subsequences][1332.
Remove Palindromic Subsequences]]
  :PROPERTIES:
  :CUSTOM_ID: remove-palindromic-subsequences
  :END:
[[./solution/1300-1399/1332.Remove Palindromic Subsequences/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

You are given a string s consisting only of letters 'a' and 'b'. In a
single step you can remove one palindromic subsequence from s.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the minimum number of steps to make the given string empty.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

A string is a subsequence of a given string if it is generated by
deleting some characters of a given string without changing its order.
Note that a subsequence does not necessarily need to be contiguous.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

A string is called palindrome if is one that reads the same backward as
well as forward.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> s = &quot;ababa&quot;
  <strong>Output:</strong> 1
  <strong>Explanation:</strong> s is already a palindrome, so its entirety can be removed in a single step.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> s = &quot;abb&quot;
  <strong>Output:</strong> 2
  <strong>Explanation:</strong> &quot;<u>a</u>bb&quot; -&gt; &quot;<u>bb</u>&quot; -&gt; &quot;&quot;. 
  Remove palindromic subsequence &quot;a&quot; then &quot;bb&quot;.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> s = &quot;baabb&quot;
  <strong>Output:</strong> 2
  <strong>Explanation:</strong> &quot;<u>baa</u>b<u>b</u>&quot; -&gt; &quot;<u>b</u>&quot; -&gt; &quot;&quot;. 
  Remove palindromic subsequence &quot;baab&quot; then &quot;b&quot;.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= s.length <= 1000

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

s[i] is either 'a' or 'b'.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
