* [[https://leetcode.com/problems/gas-station][134. Gas Station]]
  :PROPERTIES:
  :CUSTOM_ID: gas-station
  :END:
[[./solution/0100-0199/0134.Gas Station/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

There are n gas stations along a circular route, where the amount of gas
at the ith station is gas[i].

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

You have a car with an unlimited gas tank and it costs cost[i] of gas to
travel from the ith station to its next (i + 1)th station. You begin the
journey with an empty tank at one of the gas stations.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Given two integer arrays gas and cost, return the starting gas station's
index if you can travel around the circuit once in the clockwise
direction, otherwise return -1. If there exists a solution, it is
guaranteed to be unique

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> gas = [1,2,3,4,5], cost = [3,4,5,1,2]
  <strong>Output:</strong> 3
  <strong>Explanation:</strong>
  Start at station 3 (index 3) and fill up with 4 unit of gas. Your tank = 0 + 4 = 4
  Travel to station 4. Your tank = 4 - 1 + 5 = 8
  Travel to station 0. Your tank = 8 - 2 + 1 = 7
  Travel to station 1. Your tank = 7 - 3 + 2 = 6
  Travel to station 2. Your tank = 6 - 4 + 3 = 5
  Travel to station 3. The cost is 5. Your gas is just enough to travel back to station 3.
  Therefore, return 3 as the starting index.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> gas = [2,3,4], cost = [3,4,3]
  <strong>Output:</strong> -1
  <strong>Explanation:</strong>
  You can&#39;t start at station 0 or 1, as there is not enough gas to travel to the next station.
  Let&#39;s start at station 2 and fill up with 4 unit of gas. Your tank = 0 + 4 = 4
  Travel to station 0. Your tank = 4 - 3 + 2 = 3
  Travel to station 1. Your tank = 3 - 3 + 3 = 3
  You cannot travel back to station 2, as it requires 4 unit of gas but you only have 3.
  Therefore, you can&#39;t travel around the circuit once no matter where you start.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

gas.length == n

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

cost.length == n

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= n <= 104

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= gas[i], cost[i] <= 104

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
