* [[https://leetcode.com/problems/valid-word-square][422. Valid Word
Square]]
  :PROPERTIES:
  :CUSTOM_ID: valid-word-square
  :END:
[[./solution/0400-0499/0422.Valid Word Square/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Given an array of strings words, return true if it forms a valid word
square.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

A sequence of strings forms a valid word square if the kth row and
column read the same string, where 0 <= k < max(numRows, numColumns).

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> words = [&quot;abcd&quot;,&quot;bnrt&quot;,&quot;crmy&quot;,&quot;dtye&quot;]
  <strong>Output:</strong> true
  <strong>Explanation:</strong>
  The 1<sup>st</sup> row and 1<sup>st</sup> column both read &quot;abcd&quot;.
  The 2<sup>nd</sup> row and 2<sup>nd</sup> column both read &quot;bnrt&quot;.
  The 3<sup>rd</sup> row and 3<sup>rd</sup> column both read &quot;crmy&quot;.
  The 4<sup>th</sup> row and 4<sup>th</sup> column both read &quot;dtye&quot;.
  Therefore, it is a valid word square.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> words = [&quot;abcd&quot;,&quot;bnrt&quot;,&quot;crm&quot;,&quot;dt&quot;]
  <strong>Output:</strong> true
  <strong>Explanation:</strong>
  The 1<sup>st</sup> row and 1<sup>st</sup> column both read &quot;abcd&quot;.
  The 2<sup>nd</sup> row and 2<sup>nd</sup> column both read &quot;bnrt&quot;.
  The 3<sup>rd</sup> row and 3<sup>rd</sup> column both read &quot;crm&quot;.
  The 4<sup>th</sup> row and 4<sup>th</sup> column both read &quot;dt&quot;.
  Therefore, it is a valid word square.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> words = [&quot;ball&quot;,&quot;area&quot;,&quot;read&quot;,&quot;lady&quot;]
  <strong>Output:</strong> false
  <strong>Explanation:</strong>
  The 3<sup>rd</sup> row reads &quot;read&quot; while the 3<sup>rd</sup> column reads &quot;lead&quot;.
  Therefore, it is NOT a valid word square.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= words.length <= 500

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= words[i].length <= 500

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

words[i] consists of only lowercase English letters.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
