* [[https://leetcode.com/problems/buildings-with-an-ocean-view][1762.
Buildings With an Ocean View]]
  :PROPERTIES:
  :CUSTOM_ID: buildings-with-an-ocean-view
  :END:
[[./solution/1700-1799/1762.Buildings With an Ocean View/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

There are n buildings in a line. You are given an integer array heights
of size n that represents the heights of the buildings in the line.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

The ocean is to the right of the buildings. A building has an ocean view
if the building can see the ocean without obstructions. Formally, a
building has an ocean view if all the buildings to its right have a
smaller height.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return a list of indices (0-indexed) of buildings that have an ocean
view, sorted in increasing order.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> heights = [4,2,3,1]

  <strong>Output:</strong> [0,2,3]

  <strong>Explanation:</strong> Building 1 (0-indexed) does not have an ocean view because building 2 is taller.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> heights = [4,3,2,1]

  <strong>Output:</strong> [0,1,2,3]

  <strong>Explanation:</strong> All the buildings have an ocean view.</pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> heights = [1,3,2,4]

  <strong>Output:</strong> [3]

  <strong>Explanation:</strong> Only building 3 has an ocean view.</pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 4:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> heights = [2,2,2,2]

  <strong>Output:</strong> [3]

  <strong>Explanation:</strong> Buildings cannot see the ocean if there are buildings of the <strong>same</strong> height to its right.</pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= heights.length <= 105

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= heights[i] <= 109

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
