* [[https://leetcode.com/problems/rearrange-spaces-between-words][1592.
Rearrange Spaces Between Words]]
  :PROPERTIES:
  :CUSTOM_ID: rearrange-spaces-between-words
  :END:
[[./solution/1500-1599/1592.Rearrange Spaces Between Words/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

You are given a string text of words that are placed among some number
of spaces. Each word consists of one or more lowercase English letters
and are separated by at least one space. It's guaranteed that text
contains at least one word.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Rearrange the spaces so that there is an equal number of spaces between
every pair of adjacent words and that number is maximized. If you cannot
redistribute all the spaces equally, place the extra spaces at the end,
meaning the returned string should be the same length as text.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the string after rearranging the spaces.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> text = &quot;  this   is  a sentence &quot;
  <strong>Output:</strong> &quot;this   is   a   sentence&quot;
  <strong>Explanation: </strong>There are a total of 9 spaces and 4 words. We can evenly divide the 9 spaces between the words: 9 / (4-1) = 3 spaces.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> text = &quot; practice   makes   perfect&quot;
  <strong>Output:</strong> &quot;practice   makes   perfect &quot;
  <strong>Explanation:</strong>&nbsp;There are a total of 7 spaces and 3 words. 7 / (3-1) = 3 spaces plus 1 extra space. We place this extra space at the end of the string.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> text = &quot;hello   world&quot;
  <strong>Output:</strong> &quot;hello   world&quot;
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 4:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> text = &quot;  walks  udp package   into  bar a&quot;
  <strong>Output:</strong> &quot;walks  udp  package  into  bar  a &quot;
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 5:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> text = &quot;a&quot;
  <strong>Output:</strong> &quot;a&quot;
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= text.length <= 100

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

text consists of lowercase English letters and ' '.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

text contains at least one word.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
