* [[https://leetcode-cn.com/problems/bulls-and-cows][299. 猜数字游戏]]
  :PROPERTIES:
  :CUSTOM_ID: 猜数字游戏
  :END:
[[./solution/0200-0299/0299.Bulls and Cows/README_EN.org][English
Version]]

** 题目描述
   :PROPERTIES:
   :CUSTOM_ID: 题目描述
   :END:

#+begin_html
  <!-- 这里写题目描述 -->
#+end_html

#+begin_html
  <p>
#+end_html

你在和朋友一起玩 猜数字（Bulls and Cows）游戏，该游戏规则如下：

#+begin_html
  </p>
#+end_html

#+begin_html
  <ol>
#+end_html

#+begin_html
  <li>
#+end_html

你写出一个秘密数字，并请朋友猜这个数字是多少。

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

朋友每猜测一次，你就会给他一个提示，告诉他的猜测数字中有多少位属于数字和确切位置都猜对了（称为“Bulls”,
公牛），有多少位属于数字猜对了但是位置不对（称为“Cows”, 奶牛）。

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

朋友根据提示继续猜，直到猜出秘密数字。

#+begin_html
  </li>
#+end_html

#+begin_html
  </ol>
#+end_html

#+begin_html
  <p>
#+end_html

请写出一个根据秘密数字和朋友的猜测数返回提示的函数，返回字符串的格式为
xAyB ，x 和 y 都是数字，A 表示公牛，用 B 表示奶牛。

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

xA 表示有 x 位数字出现在秘密数字中，且位置都与秘密数字一致。

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

yB 表示有 y 位数字出现在秘密数字中，但位置与秘密数字不一致。

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

#+begin_html
  <p>
#+end_html

请注意秘密数字和朋友的猜测数都可能含有重复数字，每位数字只能统计一次。

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

示例 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre><strong>输入:</strong> secret = &quot;1807&quot;, guess = &quot;7810&quot;
  <strong>输出:</strong> &quot;1A3B&quot;
  <strong>解释:</strong> <code>1</code>&nbsp;公牛和&nbsp;<code>3</code>&nbsp;奶牛。公牛是 <code>8</code>，奶牛是 <code>0</code>, <code>1</code>&nbsp;和 <code>7</code>。</pre>
#+end_html

#+begin_html
  <p>
#+end_html

示例 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre><strong>输入:</strong> secret = &quot;1123&quot;, guess = &quot;0111&quot;
  <strong>输出:</strong> &quot;1A1B&quot;
  <strong>解释: </strong>朋友猜测数中的第一个 <code>1</code>&nbsp;是公牛，第二个或第三个 <code>1</code>&nbsp;可被视为奶牛。</pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

说明:
你可以假设秘密数字和朋友的猜测数都只包含数字，并且它们的长度永远相等。

#+begin_html
  </p>
#+end_html

** 解法
   :PROPERTIES:
   :CUSTOM_ID: 解法
   :END:

#+begin_html
  <!-- 这里可写通用的实现逻辑 -->
#+end_html

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:

#+begin_html
  <!-- 这里可写当前语言的特殊实现逻辑 -->
#+end_html

#+begin_src python
  class Solution:
      def getHint(self, secret: str, guess: str) -> str:
          a_cnt = b_cnt = 0
          nums1 = dict()
          nums2 = dict()
          for i in range(len(secret)):
              if secret[i] == guess[i]:
                  a_cnt += 1
              else:
                  nums1[secret[i]] = nums1.get(secret[i], 0) + 1
                  nums2[guess[i]] = nums2.get(guess[i], 0) + 1
          for i, v in nums1.items():
              if i in nums2:
                  b_cnt += min(v, nums2[i])
          return f'{a_cnt}A{b_cnt}B'
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:

#+begin_html
  <!-- 这里可写当前语言的特殊实现逻辑 -->
#+end_html

#+begin_src java
  class Solution {
      public String getHint(String secret, String guess) {
          int aCnt = 0, bCnt = 0;
          Map<Character, Integer> nums1 = new HashMap<>();
          Map<Character, Integer> nums2 = new HashMap<>();
          for (int i = 0; i < secret.length(); ++i) {
              if (secret.charAt(i) == guess.charAt(i)) {
                  ++aCnt;
              } else {
                  nums1.put(secret.charAt(i), nums1.getOrDefault(secret.charAt(i), 0) + 1);
                  nums2.put(guess.charAt(i), nums2.getOrDefault(guess.charAt(i), 0) + 1);
              }
          }

          for (Map.Entry<Character, Integer> entry : nums1.entrySet()) {
              if (nums2.containsKey(entry.getKey())) {
                  bCnt += Math.min(entry.getValue(), nums2.get(entry.getKey()));
              }
          }
          return String.format("%dA%dB", aCnt, bCnt);
      }
  }
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
