* [[https://leetcode.com/problems/sliding-puzzle][773. Sliding Puzzle]]
  :PROPERTIES:
  :CUSTOM_ID: sliding-puzzle
  :END:
[[./solution/0700-0799/0773.Sliding Puzzle/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

On a 2x3 board, there are 5 tiles represented by the integers 1 through
5, and an empty square represented by 0.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

A move consists of choosing 0 and a 4-directionally adjacent number and
swapping it.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

The state of the board is solved if and only if the board is
[[1,2,3],[4,5,0]].

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Given a puzzle board, return the least number of moves required so that
the state of the board is solved. If it is impossible for the state of
the board to be solved, return -1.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Examples:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> board = [[1,2,3],[4,0,5]]

  <strong>Output:</strong> 1

  <strong>Explanation:</strong> Swap the 0 and the 5 in one move.

  </pre>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> board = [[1,2,3],[5,4,0]]

  <strong>Output:</strong> -1

  <strong>Explanation:</strong> No number of moves will make the board solved.

  </pre>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> board = [[4,1,2],[5,0,3]]

  <strong>Output:</strong> 5

  <strong>Explanation:</strong> 5 is the smallest number of moves that solves the board.

  An example path:

  After move 0: [[4,1,2],[5,0,3]]

  After move 1: [[4,1,2],[0,5,3]]

  After move 2: [[0,1,2],[4,5,3]]

  After move 3: [[1,0,2],[4,5,3]]

  After move 4: [[1,2,0],[4,5,3]]

  After move 5: [[1,2,3],[4,5,0]]

  </pre>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> board = [[3,2,4],[1,5,0]]

  <strong>Output:</strong> 14

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Note:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

board will be a 2 x 3 array as described above.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

board[i][j] will be a permutation of [0, 1, 2, 3, 4, 5].

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
