* [[https://leetcode.com/problems/maximum-height-by-stacking-cuboids][1691.
Maximum Height by Stacking Cuboids]]
  :PROPERTIES:
  :CUSTOM_ID: maximum-height-by-stacking-cuboids
  :END:
[[./solution/1600-1699/1691.Maximum Height by Stacking Cuboids/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Given n cuboids where the dimensions of the ith cuboid is cuboids[i] =
[widthi, lengthi, heighti] (0-indexed). Choose a subset of cuboids and
place them on each other.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

You can place cuboid i on cuboid j if widthi <= widthj and lengthi <=
lengthj and heighti <= heightj. You can rearrange any cuboid's
dimensions by rotating it to put it on another cuboid.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the maximum height of the stacked cuboids.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> cuboids = [[50,45,20],[95,37,53],[45,23,12]]
  <strong>Output:</strong> 190
  <strong>Explanation:</strong>
  Cuboid 1 is placed on the bottom with the 53x37 side facing down with height 95.
  Cuboid 0 is placed next with the 45x20 side facing down with height 50.
  Cuboid 2 is placed next with the 23x12 side facing down with height 45.
  The total height is 95 + 50 + 45 = 190.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> cuboids = [[38,25,45],[76,35,3]]
  <strong>Output:</strong> 76
  <strong>Explanation:</strong>
  You can&#39;t place any of the cuboids on the other.
  We choose cuboid 1 and rotate it so that the 35x3 side is facing down and its height is 76.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> cuboids = [[7,11,17],[7,17,11],[11,7,17],[11,17,7],[17,7,11],[17,11,7]]
  <strong>Output:</strong> 102
  <strong>Explanation:</strong>
  After rearranging the cuboids, you can see that all cuboids have the same dimension.
  You can place the 11x7 side down on all cuboids so their heights are 17.
  The maximum height of stacked cuboids is 6 * 17 = 102.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

n == cuboids.length

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= n <= 100

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= widthi, lengthi, heighti <= 100

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
