* [[https://leetcode.com/problems/invalid-transactions][1169. Invalid
Transactions]]
  :PROPERTIES:
  :CUSTOM_ID: invalid-transactions
  :END:
[[./solution/1100-1199/1169.Invalid Transactions/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

A transaction is possibly invalid if:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

the amount exceeds $1000, or;

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

if it occurs within (and including) 60 minutes of another transaction
with the same name in a different city.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

#+begin_html
  <p>
#+end_html

You are given an array of strings transaction where transactions[i]
consists of comma-separated values representing the name, time (in
minutes), amount, and city of the transaction.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return a list of transactions that are possibly invalid. You may return
the answer in any order.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> transactions = [&quot;alice,20,800,mtv&quot;,&quot;alice,50,100,beijing&quot;]
  <strong>Output:</strong> [&quot;alice,20,800,mtv&quot;,&quot;alice,50,100,beijing&quot;]
  <strong>Explanation:</strong> The first transaction is invalid because the second transaction occurs within a difference of 60 minutes, have the same name and is in a different city. Similarly the second one is invalid too.</pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> transactions = [&quot;alice,20,800,mtv&quot;,&quot;alice,50,1200,mtv&quot;]
  <strong>Output:</strong> [&quot;alice,50,1200,mtv&quot;]
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> transactions = [&quot;alice,20,800,mtv&quot;,&quot;bob,50,1200,mtv&quot;]
  <strong>Output:</strong> [&quot;bob,50,1200,mtv&quot;]
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

transactions.length <= 1000

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Each transactions[i] takes the form "{name},{time},{amount},{city}"

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Each {name} and {city} consist of lowercase English letters, and have
lengths between 1 and 10.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Each {time} consist of digits, and represent an integer between 0 and
1000.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Each {amount} consist of digits, and represent an integer between 0 and
2000.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
