* [[https://leetcode.com/problems/domino-and-tromino-tiling][790. Domino
and Tromino Tiling]]
  :PROPERTIES:
  :CUSTOM_ID: domino-and-tromino-tiling
  :END:
[[./solution/0700-0799/0790.Domino and Tromino Tiling/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

We have two types of tiles: a 2x1 domino shape, and an "L" tromino
shape. These shapes may be rotated.

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  XX  &lt;- domino



  XX  &lt;- &quot;L&quot; tromino

  X

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Given N, how many ways are there to tile a 2 x N board? Return your
answer modulo 10^9 + 7.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

(In a tiling, every square must be covered by a tile. Two tilings are
different if and only if there are two 4-directionally adjacent cells on
the board such that exactly one of the tilings has both squares occupied
by a tile.)

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Example:</strong>

  <strong>Input:</strong> 3

  <strong>Output:</strong> 5

  <strong>Explanation:</strong> 

  The five different ways are listed below, different letters indicates different tiles:

  XYZ XXZ XYY XXY XYY

  XYZ YYZ XZZ XYY XXY</pre>
#+end_html

#+begin_html
  <p>
#+end_html

Note:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

N  will be in range [1, 1000].

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
