* [[https://leetcode.com/problems/my-calendar-i][729. My Calendar I]]
  :PROPERTIES:
  :CUSTOM_ID: my-calendar-i
  :END:
[[./solution/0700-0799/0729.My Calendar I/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Implement a MyCalendar class to store your events. A new event can be
added if adding the event will not cause a double booking.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Your class will have the method, book(int start, int end). Formally,
this represents a booking on the half open interval [start, end), the
range of real numbers x such that start <= x < end.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

A double booking happens when two events have some non-empty
intersection (ie., there is some time that is common to both events.)

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

For each call to the method MyCalendar.book, return true if the event
can be added to the calendar successfully without causing a double
booking. Otherwise, return false and do not add the event to the
calendar.

#+begin_html
  </p>
#+end_html

Your class will be called like this: MyCalendar cal = new MyCalendar();
MyCalendar.book(start, end)

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  MyCalendar();

  MyCalendar.book(10, 20); // returns true

  MyCalendar.book(15, 25); // returns false

  MyCalendar.book(20, 30); // returns true

  <b>Explanation:</b> 

  The first event can be booked.  The second can&#39;t because time 15 is already booked by another event.

  The third event can be booked, as the first event takes every time less than 20, but not including 20.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Note:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

The number of calls to MyCalendar.book per test case will be at most
1000.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

In calls to MyCalendar.book(start, end), start and end are integers in
the range [0, 10^9].

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
