* [[https://leetcode.com/problems/minimum-cost-for-tickets][983. Minimum
Cost For Tickets]]
  :PROPERTIES:
  :CUSTOM_ID: minimum-cost-for-tickets
  :END:
[[./solution/0900-0999/0983.Minimum Cost For Tickets/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

In a country popular for train travel, you have planned some train
travelling one year in advance.  The days of the year that you will
travel is given as an array days.  Each day is an integer from 1 to 365.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Train tickets are sold in 3 different ways:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

a 1-day pass is sold for costs[0] dollars;

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

a 7-day pass is sold for costs[1] dollars;

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

a 30-day pass is sold for costs[2] dollars.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

#+begin_html
  <p>
#+end_html

The passes allow that many days of consecutive travel.  For example, if
we get a 7-day pass on day 2, then we can travel for 7 days: day 2, 3,
4, 5, 6, 7, and 8.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the minimum number of dollars you need to travel every day in the
given list of days.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input: </strong>days = <span id="example-input-1-1">[1,4,6,7,8,20]</span>, costs = <span id="example-input-1-2">[2,7,15]</span>

  <strong>Output: </strong><span id="example-output-1">11</span>

  <strong>Explanation: </strong>

  For example, here is one way to buy passes that lets you travel your travel plan:

  On day 1, you bought a 1-day pass for costs[0] = $2, which covered day 1.

  On day 3, you bought a 7-day pass for costs[1] = $7, which covered days 3, 4, ..., 9.

  On day 20, you bought a 1-day pass for costs[0] = $2, which covered day 20.

  In total you spent $11 and covered all the days of your travel.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input: </strong>days = <span id="example-input-2-1">[1,2,3,4,5,6,7,8,9,10,30,31]</span>, costs = <span id="example-input-2-2">[2,7,15]</span>

  <strong>Output: </strong><span id="example-output-2">17</span>

  <strong>Explanation: </strong>

  For example, here is one way to buy passes that lets you travel your travel plan:

  On day 1, you bought a 30-day pass for costs[2] = $15 which covered days 1, 2, ..., 30.

  On day 31, you bought a 1-day pass for costs[0] = $2 which covered day 31.

  In total you spent $17 and covered all the days of your travel.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Note:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ol>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= days.length <= 365

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= days[i] <= 365

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

days is in strictly increasing order.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

costs.length == 3

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= costs[i] <= 1000

#+begin_html
  </li>
#+end_html

#+begin_html
  </ol>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
