* [[https://leetcode.com/problems/guess-the-word][843. Guess the Word]]
  :PROPERTIES:
  :CUSTOM_ID: guess-the-word
  :END:
[[./solution/0800-0899/0843.Guess the Word/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

This is an interactive problem.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

You are given an array of unique strings wordlist where wordlist[i] is 6
letters long, and one word in this list is chosen as secret.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

You may call Master.guess(word) to guess a word. The guessed word should
have type string and must be from the original list with 6 lowercase
letters.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

This function returns an integer type, representing the number of exact
matches (value and position) of your guess to the secret word. Also, if
your guess is not in the given wordlist, it will return -1 instead.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

For each test case, you have exactly 10 guesses to guess the word. At
the end of any number of calls, if you have made 10 or fewer calls to
Master.guess and at least one of these guesses was secret, then you pass
the test case.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> secret = &quot;acckzz&quot;, wordlist = [&quot;acckzz&quot;,&quot;ccbazz&quot;,&quot;eiowzz&quot;,&quot;abcczz&quot;], numguesses = 10
  <strong>Output:</strong> You guessed the secret word correctly.
  <strong>Explanation:</strong>
  master.guess(&quot;aaaaaa&quot;) returns -1, because &quot;aaaaaa&quot; is not in wordlist.
  master.guess(&quot;acckzz&quot;) returns 6, because &quot;acckzz&quot; is secret and has all 6 matches.
  master.guess(&quot;ccbazz&quot;) returns 3, because &quot;ccbazz&quot; has 3 matches.
  master.guess(&quot;eiowzz&quot;) returns 2, because &quot;eiowzz&quot; has 2 matches.
  master.guess(&quot;abcczz&quot;) returns 4, because &quot;abcczz&quot; has 4 matches.
  We made 5 calls to master.guess and one of them was the secret, so we pass the test case.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> secret = &quot;hamada&quot;, wordlist = [&quot;hamada&quot;,&quot;khaled&quot;], numguesses = 10
  <strong>Output:</strong> You guessed the secret word correctly.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= wordlist.length <= 100

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

wordlist[i].length == 6

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

wordlist[i] consist of lowercase English letters.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

All the strings of wordlist are unique.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

secret exists in wordlist.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

numguesses == 10

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
