* [[https://leetcode.com/problems/jump-game-v][1340. Jump Game V]]
  :PROPERTIES:
  :CUSTOM_ID: jump-game-v
  :END:
[[./solution/1300-1399/1340.Jump Game V/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Given an array of integers arr and an integer d. In one step you can
jump from index i to index:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

i + x where: i + x < arr.length and 0 < x <= d.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

i - x where: i - x >= 0 and 0 < x <= d.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

#+begin_html
  <p>
#+end_html

In addition, you can only jump from index i to index j if arr[i] >
arr[j] and arr[i] > arr[k] for all indices k between i and j (More
formally min(i, j) < k < max(i, j)).

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

You can choose any index of the array and start jumping. Return the
maximum number of indices you can visit.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Notice that you can not jump outside of the array at any time.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> arr = [6,4,14,6,8,13,9,7,10,6,12], d = 2

  <strong>Output:</strong> 4

  <strong>Explanation:</strong> You can start at index 10. You can jump 10 --&gt; 8 --&gt; 6 --&gt; 7 as shown.

  Note that if you start at index 6 you can only jump to index 7. You cannot jump to index 5 because 13 &gt; 9. You cannot jump to index 4 because index 5 is between index 4 and 6 and 13 &gt; 9.

  Similarly You cannot jump from index 3 to index 2 or index 1.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> arr = [3,3,3,3,3], d = 3

  <strong>Output:</strong> 1

  <strong>Explanation:</strong> You can start at any index. You always cannot jump to any index.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> arr = [7,6,5,4,3,2,1], d = 1

  <strong>Output:</strong> 7

  <strong>Explanation:</strong> Start at index 0. You can visit all the indicies. 

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 4:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> arr = [7,1,7,1,7,1], d = 2

  <strong>Output:</strong> 2

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 5:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> arr = [66], d = 1

  <strong>Output:</strong> 1

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= arr.length <= 1000

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= arr[i] <= 10^5

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= d <= arr.length

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
