* [[https://leetcode.com/problems/maximum-area-of-a-piece-of-cake-after-horizontal-and-vertical-cuts][1465.
Maximum Area of a Piece of Cake After Horizontal and Vertical Cuts]]
  :PROPERTIES:
  :CUSTOM_ID: maximum-area-of-a-piece-of-cake-after-horizontal-and-vertical-cuts
  :END:
[[./solution/1400-1499/1465.Maximum Area of a Piece of Cake After Horizontal and Vertical Cuts/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Given a rectangular cake with height h and width w, and two arrays of
integers horizontalCuts and verticalCuts where horizontalCuts[i] is the
distance from the top of the rectangular cake to the ith horizontal
cut and similarly, verticalCuts[j] is the distance from the left of the
rectangular cake to the jth vertical cut.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the maximum area of a piece of cake after you cut at each
horizontal and vertical position provided in the arrays horizontalCuts
and verticalCuts. Since the answer can be a huge number, return this
modulo 10^9 + 7.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> h = 5, w = 4, horizontalCuts = [1,2,4], verticalCuts = [1,3]
  <strong>Output:</strong> 4 
  <strong>Explanation:</strong> The figure above represents the given rectangular cake. Red lines are the horizontal and vertical cuts. After you cut the cake, the green piece of cake has the maximum area.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> h = 5, w = 4, horizontalCuts = [3,1], verticalCuts = [1]
  <strong>Output:</strong> 6
  <strong>Explanation:</strong> The figure above represents the given rectangular cake. Red lines are the horizontal and vertical cuts. After you cut the cake, the green and yellow pieces of cake have the maximum area.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> h = 5, w = 4, horizontalCuts = [3], verticalCuts = [3]
  <strong>Output:</strong> 9
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

2 <= h, w <= 10^9

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= horizontalCuts.length < min(h, 10^5)

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= verticalCuts.length < min(w, 10^5)

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= horizontalCuts[i] < h

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= verticalCuts[i] < w

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

It is guaranteed that all elements in horizontalCuts are distinct.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

It is guaranteed that all elements in verticalCuts are distinct.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
