* [[https://leetcode.com/problems/confusing-number][1056. Confusing
Number]]
  :PROPERTIES:
  :CUSTOM_ID: confusing-number
  :END:
[[./solution/1000-1099/1056.Confusing Number/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Given a number N, return true if and only if it is a confusing number,
which satisfies the following condition:

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

We can rotate digits by 180 degrees to form new digits. When 0, 1, 6, 8,
9 are rotated 180 degrees, they become 0, 1, 9, 8, 6 respectively. When
2, 3, 4, 5 and 7 are rotated 180 degrees, they become invalid. A
confusing number is a number that when rotated 180 degrees becomes a
different number with each digit valid.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input: </strong><span id="example-input-1-1">6</span>

  <strong>Output: </strong><span id="example-output-1">true</span>

  <strong>Explanation: </strong>

  We get <code>9</code> after rotating <code>6</code>, <code>9</code> is a valid number and <code>9!=6</code>.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input: </strong><span id="example-input-2-1">89</span>

  <strong>Output: </strong><span id="example-output-2">true</span>

  <strong>Explanation: </strong>

  We get <code>68</code> after rotating <code>89</code>, <code>86</code> is a valid number and <code>86!=89</code>.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input: </strong><span id="example-input-3-1">11</span>

  <strong>Output: </strong><span id="example-output-3">false</span>

  <strong>Explanation: </strong>

  We get <code>11</code> after rotating <code>11</code>, <code>11</code> is a valid number but the value remains the same, thus <code>11</code> is not a confusing number.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 4:

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input: </strong><span id="example-input-4-1">25</span>

  <strong>Output: </strong><span id="example-output-4">false</span>

  <strong>Explanation: </strong>

  We get an invalid number after rotating <code>25</code>.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Note:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ol>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= N <= 10^9

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

After the rotation we can ignore leading zeros, for example if after
rotation we have 0008 then this number is considered as just 8.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ol>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
