* [[https://leetcode.com/problems/teemo-attacking][495. Teemo
Attacking]]
  :PROPERTIES:
  :CUSTOM_ID: teemo-attacking
  :END:
[[./solution/0400-0499/0495.Teemo Attacking/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

You are given an integer array timeSeries and an integer duration. Our
hero Teemo has attacked an enemy where the ith attack was done at the
timeSeries[i]. When Teemo attacks their enemy, the enemy gets poisoned
for duration time (i.e., the enemy is poisoned for the time interval
[timeSeries[i], timeSeries[i] + duration - 1] inclusive).

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the total time that the enemy is in a poisoned condition.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> timeSeries = [1,4], duration = 2
  <strong>Output:</strong> 4
  <strong>Explanation:</strong> At time point 1, Teemo starts attacking the enemy and makes them be poisoned immediately. 
  This poisoned status will last 2 seconds until the end of time point 2. 
  And at time point 4, Teemo attacks the enemy again and causes them to be in poisoned status for another 2 seconds. 
  So you finally need to output 4.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> timeSeries = [1,2], duration = 2
  <strong>Output:</strong> 3
  <strong>Explanation:</strong> At time point 1, Teemo starts attacking the enemy and makes them be poisoned. 
  This poisoned status will last 2 seconds until the end of time point 2. 
  However, at the beginning of time point 2, Teemo attacks the enemy again who is already in poisoned status. 
  Since the poisoned status won&#39;t add up together, though the second poisoning attack will still work at time point 2, it will stop at the end of time point 3. 
  So you finally need to output 3.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= timeSeries.length <= 104

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= timeSeries[i], duration <= 107

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

timeSeries is sorted in non-decreasing order.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
