* [[https://leetcode.com/problems/increasing-decreasing-string][1370.
Increasing Decreasing String]]
  :PROPERTIES:
  :CUSTOM_ID: increasing-decreasing-string
  :END:
[[./solution/1300-1399/1370.Increasing Decreasing String/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Given a string s. You should re-order the string using the following
algorithm:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ol>
#+end_html

#+begin_html
  <li>
#+end_html

Pick the smallest character from s and append it to the result.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Pick the smallest character from s which is greater than the last
appended character to the result and append it.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Repeat step 2 until you cannot pick more characters.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Pick the largest character from s and append it to the result.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Pick the largest character from s which is smaller than the last
appended character to the result and append it.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Repeat step 5 until you cannot pick more characters.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Repeat the steps from 1 to 6 until you pick all characters from s.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ol>
#+end_html

#+begin_html
  <p>
#+end_html

In each step, If the smallest or the largest character appears more than
once you can choose any occurrence and append it to the result.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the result string after sorting s with this algorithm.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> s = &quot;aaaabbbbcccc&quot;
  <strong>Output:</strong> &quot;abccbaabccba&quot;
  <strong>Explanation:</strong> After steps 1, 2 and 3 of the first iteration, result = &quot;abc&quot;
  After steps 4, 5 and 6 of the first iteration, result = &quot;abccba&quot;
  First iteration is done. Now s = &quot;aabbcc&quot; and we go back to step 1
  After steps 1, 2 and 3 of the second iteration, result = &quot;abccbaabc&quot;
  After steps 4, 5 and 6 of the second iteration, result = &quot;abccbaabccba&quot;
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> s = &quot;rat&quot;
  <strong>Output:</strong> &quot;art&quot;
  <strong>Explanation:</strong> The word &quot;rat&quot; becomes &quot;art&quot; after re-ordering it with the mentioned algorithm.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> s = &quot;leetcode&quot;
  <strong>Output:</strong> &quot;cdelotee&quot;
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 4:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> s = &quot;ggggggg&quot;
  <strong>Output:</strong> &quot;ggggggg&quot;
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 5:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> s = &quot;spo&quot;
  <strong>Output:</strong> &quot;ops&quot;
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= s.length <= 500

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

s contains only lower-case English letters.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
