* [[https://leetcode.com/problems/moving-stones-until-consecutive-ii][1040.
Moving Stones Until Consecutive II]]
  :PROPERTIES:
  :CUSTOM_ID: moving-stones-until-consecutive-ii
  :END:
[[./solution/1000-1099/1040.Moving Stones Until Consecutive II/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

On an infinite number line, the position of the i-th stone is given
by stones[i].  Call a stone an endpoint stone if it has the smallest or
largest position.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Each turn, you pick up an endpoint stone and move it to an unoccupied
position so that it is no longer an endpoint stone.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

In particular, if the stones are at say, stones = [1,2,5], you cannot
move the endpoint stone at position 5, since moving it to any position
(such as 0, or 3) will still keep that stone as an endpoint stone.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

The game ends when you cannot make any more moves, ie. the stones are in
consecutive positions.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

When the game ends, what is the minimum and maximum number of moves that
you could have made?  Return the answer as an length 2 array: answer =
[minimum_moves, maximum_moves]

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input: </strong><span id="example-input-1-1">[7,4,9]</span>

  <strong>Output: </strong><span id="example-output-1">[1,2]</span>

  <strong>Explanation: </strong>

  We can move 4 -&gt; 8 for one move to finish the game.

  Or, we can move 9 -&gt; 5, 4 -&gt; 6 for two moves to finish the game.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input: </strong><span id="example-input-2-1">[6,5,4,3,10]</span>

  <strong>Output: </strong><span id="example-output-2">[2,3]</span>

  We can move 3 -&gt; 8 then 10 -&gt; 7 to finish the game.

  Or, we can move 3 -&gt; 7, 4 -&gt; 8, 5 -&gt; 9 to finish the game.

  Notice we cannot move 10 -&gt; 2 to finish the game, because that would be an illegal move.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input: </strong><span id="example-input-3-1">[100,101,104,102,103]</span>

  <strong>Output: </strong><span id="example-output-3">[0,0]</span></pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Note:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ol>
#+end_html

#+begin_html
  <li>
#+end_html

3 <= stones.length <= 10^4

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= stones[i] <= 10^9

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

stones[i] have distinct values.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ol>
#+end_html

 

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
