* [[https://leetcode.com/problems/heaters][475. Heaters]]
  :PROPERTIES:
  :CUSTOM_ID: heaters
  :END:
[[./solution/0400-0499/0475.Heaters/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Winter is coming! During the contest, your first job is to design a
standard heater with a fixed warm radius to warm all the houses.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Every house can be warmed, as long as the house is within the heater's
warm radius range. 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Given the positions of houses and heaters on a horizontal line, return
the minimum radius standard of heaters so that those heaters could cover
all houses.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Notice that all the heaters follow your radius standard, and the warm
radius will the same.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> houses = [1,2,3], heaters = [2]
  <strong>Output:</strong> 1
  <strong>Explanation:</strong> The only heater was placed in the position 2, and if we use the radius 1 standard, then all the houses can be warmed.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> houses = [1,2,3,4], heaters = [1,4]
  <strong>Output:</strong> 1
  <strong>Explanation:</strong> The two heater was placed in the position 1 and 4. We need to use radius 1 standard, then all the houses can be warmed.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> houses = [1,5], heaters = [2]
  <strong>Output:</strong> 3
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= houses.length, heaters.length <= 3 * 104

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= houses[i], heaters[i] <= 109

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
