* [[https://leetcode.com/problems/filling-bookcase-shelves][1105.
Filling Bookcase Shelves]]
  :PROPERTIES:
  :CUSTOM_ID: filling-bookcase-shelves
  :END:
[[./solution/1100-1199/1105.Filling Bookcase Shelves/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

We have a sequence of books: the i-th book has thickness books[i][0] and
height books[i][1].

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

We want to place these books in order onto bookcase shelves that have
total width shelf_width.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

We choose some of the books to place on this shelf (such that the sum of
their thickness is <= shelf_width), then build another level of shelf of
the bookcase so that the total height of the bookcase has increased by
the maximum height of the books we just put down.  We repeat this
process until there are no more books to place.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Note again that at each step of the above process, the order of the
books we place is the same order as the given sequence of books.  For
example, if we have an ordered list of 5 books, we might place the first
and second book onto the first shelf, the third book on the second
shelf, and the fourth and fifth book on the last shelf.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the minimum possible height that the total bookshelf can be after
placing shelves in this manner.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> books = [[1,1],[2,3],[2,3],[1,1],[1,1],[1,1],[1,2]], shelf_width = 4
  <strong>Output:</strong> 6
  <strong>Explanation:</strong>
  The sum of the heights of the 3 shelves are 1 + 3 + 2 = 6.
  Notice that book number 2 does not have to be on the first shelf.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= books.length <= 1000

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= books[i][0] <= shelf_width <= 1000

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= books[i][1] <= 1000

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
