* [[https://leetcode.com/problems/minimum-moves-to-make-array-complementary][1674.
Minimum Moves to Make Array Complementary]]
  :PROPERTIES:
  :CUSTOM_ID: minimum-moves-to-make-array-complementary
  :END:
[[./solution/1600-1699/1674.Minimum Moves to Make Array Complementary/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

You are given an integer array nums of even length n and an integer
limit. In one move, you can replace any integer from nums with another
integer between 1 and limit, inclusive.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

The array nums is complementary if for all indices i (0-indexed),
nums[i] + nums[n - 1 - i] equals the same number. For example, the array
[1,2,3,4] is complementary because for all indices i, nums[i] + nums[n -
1 - i] = 5.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the minimum number of moves required to make nums complementary.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> nums = [1,2,4,3], limit = 4
  <strong>Output:</strong> 1
  <strong>Explanation:</strong> In 1 move, you can change nums to [1,2,<u>2</u>,3] (underlined elements are changed).
  nums[0] + nums[3] = 1 + 3 = 4.
  nums[1] + nums[2] = 2 + 2 = 4.
  nums[2] + nums[1] = 2 + 2 = 4.
  nums[3] + nums[0] = 3 + 1 = 4.
  Therefore, nums[i] + nums[n-1-i] = 4 for every i, so nums is complementary.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> nums = [1,2,2,1], limit = 2
  <strong>Output:</strong> 2
  <strong>Explanation:</strong> In 2 moves, you can change nums to [<u>2</u>,2,2,<u>2</u>]. You cannot change any number to 3 since 3 &gt; limit.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> nums = [1,2,1,2], limit = 2
  <strong>Output:</strong> 0
  <strong>Explanation:</strong> nums is already complementary.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

n == nums.length

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

2 <= n <= 105

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= nums[i] <= limit <= 105

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

n is even.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
