* [[https://leetcode.com/problems/couples-holding-hands][765. Couples
Holding Hands]]
  :PROPERTIES:
  :CUSTOM_ID: couples-holding-hands
  :END:
[[./solution/0700-0799/0765.Couples Holding Hands/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

N couples sit in 2N seats arranged in a row and want to hold hands. We
want to know the minimum number of swaps so that every couple is sitting
side by side. A swap consists of choosing any two people, then they
stand up and switch seats.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

The people and seats are represented by an integer from 0 to 2N-1, the
couples are numbered in order, the first couple being (0, 1), the second
couple being (2, 3), and so on with the last couple being (2N-2, 2N-1).

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

The couples' initial seating is given by row[i] being the value of the
person who is initially sitting in the i-th seat.

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  <pre>

  <b>Input:</b> row = [0, 2, 1, 3]

  <b>Output:</b> 1

  <b>Explanation:</b> We only need to swap the second (row[1]) and third (row[2]) person.

  </pre>
#+end_html

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  <pre>

  <b>Input:</b> row = [3, 2, 0, 1]

  <b>Output:</b> 0

  <b>Explanation:</b> All couples are already seated side by side.

  </pre>
#+end_html

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Note:

#+begin_html
  <ol>
#+end_html

#+begin_html
  <li>
#+end_html

len(row) is even and in the range of [4, 60].

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

row is guaranteed to be a permutation of 0...len(row)-1.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ol>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
