* [[https://leetcode.com/problems/car-fleet-ii][1776. Car Fleet II]]
  :PROPERTIES:
  :CUSTOM_ID: car-fleet-ii
  :END:
[[./solution/1700-1799/1776.Car Fleet II/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

There are n cars traveling at different speeds in the same direction
along a one-lane road. You are given an array cars of length n, where
cars[i] = [positioni, speedi] represents:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

positioni is the distance between the ith car and the beginning of the
road in meters. It is guaranteed that positioni < positioni+1.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

speedi is the initial speed of the ith car in meters per second.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

#+begin_html
  <p>
#+end_html

For simplicity, cars can be considered as points moving along the number
line. Two cars collide when they occupy the same position. Once a car
collides with another car, they unite and form a single car fleet. The
cars in the formed fleet will have the same position and the same speed,
which is the initial speed of the slowest car in the fleet.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return an array answer, where answer[i] is the time, in seconds, at
which the ith car collides with the next car, or -1 if the car does not
collide with the next car. Answers within 10-5 of the actual answers are
accepted.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> cars = [[1,2],[2,1],[4,3],[7,2]]
  <strong>Output:</strong> [1.00000,-1.00000,3.00000,-1.00000]
  <strong>Explanation:</strong> After exactly one second, the first car will collide with the second car, and form a car fleet with speed 1 m/s. After exactly 3 seconds, the third car will collide with the fourth car, and form a car fleet with speed 2 m/s.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> cars = [[3,4],[5,4],[6,3],[9,1]]
  <strong>Output:</strong> [2.00000,1.00000,1.50000,-1.00000]
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= cars.length <= 105

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= positioni, speedi <= 106

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

positioni < positioni+1

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
