* [[https://leetcode.com/problems/next-closest-time][681. Next Closest
Time]]
  :PROPERTIES:
  :CUSTOM_ID: next-closest-time
  :END:
[[./solution/0600-0699/0681.Next Closest Time/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Given a time represented in the format "HH:MM", form the next closest
time by reusing the current digits. There is no limit on how many times
a digit can be reused.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

You may assume the given input string is always valid. For example,
"01:34", "12:09" are all valid. "1:34", "12:9" are all invalid.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> time = &quot;19:34&quot;
  <strong>Output:</strong> &quot;19:39&quot;
  <strong>Explanation:</strong> The next closest time choosing from digits <strong>1</strong>, <strong>9</strong>, <strong>3</strong>, <strong>4</strong>, is <strong>19:39</strong>, which occurs 5 minutes later.
  It is not <strong>19:33</strong>, because this occurs 23 hours and 59 minutes later.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> time = &quot;23:59&quot;
  <strong>Output:</strong> &quot;22:22&quot;
  <strong>Explanation:</strong> The next closest time choosing from digits <strong>2</strong>, <strong>3</strong>, <strong>5</strong>, <strong>9</strong>, is <strong>22:22</strong>.
  It may be assumed that the returned time is next day&#39;s time since it is smaller than the input time numerically.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

time.length == 5

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

time is a valid time in the form "HH:MM".

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= HH < 24

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= MM < 60

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
