* [[https://leetcode.com/problems/the-maze-ii][505. The Maze II]]
  :PROPERTIES:
  :CUSTOM_ID: the-maze-ii
  :END:
[[./solution/0500-0599/0505.The Maze II/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

There is a ball in a maze with empty spaces (represented as 0) and walls
(represented as 1). The ball can go through the empty spaces by rolling
up, down, left or right, but it won't stop rolling until hitting a wall.
When the ball stops, it could choose the next direction.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Given the m x n maze, the ball's start position and the destination,
where start = [startrow, startcol] and destination = [destinationrow,
destinationcol], return the shortest distance for the ball to stop at
the destination. If the ball cannot stop at destination, return -1.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

The distance is the number of empty spaces traveled by the ball from the
start position (excluded) to the destination (included).

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

You may assume that the borders of the maze are all walls (see
examples).

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> maze = [[0,0,1,0,0],[0,0,0,0,0],[0,0,0,1,0],[1,1,0,1,1],[0,0,0,0,0]], start = [0,4], destination = [4,4]
  <strong>Output:</strong> 12
  <strong>Explanation:</strong> One possible way is : left -&gt; down -&gt; left -&gt; down -&gt; right -&gt; down -&gt; right.
  The length of the path is 1 + 1 + 3 + 1 + 2 + 2 + 2 = 12.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> maze = [[0,0,1,0,0],[0,0,0,0,0],[0,0,0,1,0],[1,1,0,1,1],[0,0,0,0,0]], start = [0,4], destination = [3,2]
  <strong>Output:</strong> -1
  <strong>Explanation:</strong> There is no way for the ball to stop at the destination. Notice that you can pass through the destination but you cannot stop there.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> maze = [[0,0,0,0,0],[1,1,0,0,1],[0,0,0,0,0],[0,1,0,0,1],[0,1,0,0,0]], start = [4,3], destination = [0,1]
  <strong>Output:</strong> -1
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

m == maze.length

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

n == maze[i].length

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= m, n <= 100

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

maze[i][j] is 0 or 1.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

start.length == 2

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

destination.length == 2

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= startrow, destinationrow <= m

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= startcol, destinationcol <= n

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Both the ball and the destination exist in an empty space, and they will
not be in the same position initially.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

The maze contains at least 2 empty spaces.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
