* [[https://leetcode.com/problems/unique-morse-code-words][804. Unique
Morse Code Words]]
  :PROPERTIES:
  :CUSTOM_ID: unique-morse-code-words
  :END:
[[./solution/0800-0899/0804.Unique Morse Code Words/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

International Morse Code defines a standard encoding where each letter
is mapped to a series of dots and dashes, as follows: "a" maps to ".-",
"b" maps to "-...", "c" maps to "-.-.", and so on.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

For convenience, the full table for the 26 letters of the English
alphabet is given below:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  [&quot;.-&quot;,&quot;-...&quot;,&quot;-.-.&quot;,&quot;-..&quot;,&quot;.&quot;,&quot;..-.&quot;,&quot;--.&quot;,&quot;....&quot;,&quot;..&quot;,&quot;.---&quot;,&quot;-.-&quot;,&quot;.-..&quot;,&quot;--&quot;,&quot;-.&quot;,&quot;---&quot;,&quot;.--.&quot;,&quot;--.-&quot;,&quot;.-.&quot;,&quot;...&quot;,&quot;-&quot;,&quot;..-&quot;,&quot;...-&quot;,&quot;.--&quot;,&quot;-..-&quot;,&quot;-.--&quot;,&quot;--..&quot;]</pre>
#+end_html

#+begin_html
  <p>
#+end_html

Now, given a list of words, each word can be written as a concatenation
of the Morse code of each letter. For example, "cab" can be written as
"-.-..--...", (which is the concatenation "-.-." + ".-" + "-..."). We'll
call such a concatenation, the transformation of a word.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the number of different transformations among all words we have.

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Example:</strong>
  <strong>Input:</strong> words = [&quot;gin&quot;, &quot;zen&quot;, &quot;gig&quot;, &quot;msg&quot;]
  <strong>Output:</strong> 2
  <strong>Explanation: </strong>
  The transformation of each word is:
  &quot;gin&quot; -&gt; &quot;--...-.&quot;
  &quot;zen&quot; -&gt; &quot;--...-.&quot;
  &quot;gig&quot; -&gt; &quot;--...--.&quot;
  &quot;msg&quot; -&gt; &quot;--...--.&quot;

  There are 2 different transformations, &quot;--...-.&quot; and &quot;--...--.&quot;.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Note:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

The length of words will be at most 100.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Each words[i] will have length in range [1, 12].

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

words[i] will only consist of lowercase letters.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
