* [[https://leetcode.com/problems/asteroid-collision][735. Asteroid
Collision]]
  :PROPERTIES:
  :CUSTOM_ID: asteroid-collision
  :END:
[[./solution/0700-0799/0735.Asteroid Collision/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

We are given an array asteroids of integers representing asteroids in a
row.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

For each asteroid, the absolute value represents its size, and the sign
represents its direction (positive meaning right, negative meaning
left). Each asteroid moves at the same speed.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Find out the state of the asteroids after all collisions. If two
asteroids meet, the smaller one will explode. If both are the same size,
both will explode. Two asteroids moving in the same direction will never
meet.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> asteroids = [5,10,-5]
  <strong>Output:</strong> [5,10]
  <b>Explanation:</b> The 10 and -5 collide resulting in 10. The 5 and 10 never collide.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> asteroids = [8,-8]
  <strong>Output:</strong> []
  <b>Explanation:</b> The 8 and -8 collide exploding each other.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> asteroids = [10,2,-5]
  <strong>Output:</strong> [10]
  <b>Explanation:</b> The 2 and -5 collide resulting in -5. The 10 and -5 collide resulting in 10.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 4:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> asteroids = [-2,-1,1,2]
  <strong>Output:</strong> [-2,-1,1,2]
  <b>Explanation:</b> The -2 and -1 are moving left, while the 1 and 2 are moving right. Asteroids moving the same direction never meet, so no asteroids will meet each other.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

2 <= asteroids.length <= 104

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

-1000 <= asteroids[i] <= 1000

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

asteroids[i] != 0

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
