* [[https://leetcode.com/problems/filter-restaurants-by-vegan-friendly-price-and-distance][1333.
Filter Restaurants by Vegan-Friendly, Price and Distance]]
  :PROPERTIES:
  :CUSTOM_ID: filter-restaurants-by-vegan-friendly-price-and-distance
  :END:
[[./solution/1300-1399/1333.Filter Restaurants by Vegan-Friendly%2C Price and Distance/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Given the array restaurants where  restaurants[i] = [idi, ratingi,
veganFriendlyi, pricei, distancei]. You have to filter the restaurants
using three filters.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

The veganFriendly filter will be either true (meaning you should only
include restaurants with veganFriendlyi set to true) or false (meaning
you can include any restaurant). In addition, you have the
filters maxPrice and maxDistance which are the maximum value for price
and distance of restaurants you should consider respectively.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the array of restaurant IDs after filtering, ordered by rating
from highest to lowest. For restaurants with the same rating, order them
by id from highest to lowest. For simplicity veganFriendlyi and
veganFriendly take value 1 when it is true, and 0 when it is false.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> restaurants = [[1,4,1,40,10],[2,8,0,50,5],[3,8,1,30,4],[4,10,0,10,3],[5,1,1,15,1]], veganFriendly = 1, maxPrice = 50, maxDistance = 10
  <strong>Output:</strong> [3,1,5] 
  <strong>Explanation: 
  </strong>The restaurants are:
  Restaurant 1 [id=1, rating=4, veganFriendly=1, price=40, distance=10]
  Restaurant 2 [id=2, rating=8, veganFriendly=0, price=50, distance=5]
  Restaurant 3 [id=3, rating=8, veganFriendly=1, price=30, distance=4]
  Restaurant 4 [id=4, rating=10, veganFriendly=0, price=10, distance=3]
  Restaurant 5 [id=5, rating=1, veganFriendly=1, price=15, distance=1] 
  After filter restaurants with veganFriendly = 1, maxPrice = 50 and maxDistance = 10 we have restaurant 3, restaurant 1 and restaurant 5 (ordered by rating from highest to lowest). 
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> restaurants = [[1,4,1,40,10],[2,8,0,50,5],[3,8,1,30,4],[4,10,0,10,3],[5,1,1,15,1]], veganFriendly = 0, maxPrice = 50, maxDistance = 10
  <strong>Output:</strong> [4,3,2,1,5]
  <strong>Explanation:</strong> The restaurants are the same as in example 1, but in this case the filter veganFriendly = 0, therefore all restaurants are considered.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> restaurants = [[1,4,1,40,10],[2,8,0,50,5],[3,8,1,30,4],[4,10,0,10,3],[5,1,1,15,1]], veganFriendly = 0, maxPrice = 30, maxDistance = 3
  <strong>Output:</strong> [4,5]
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= restaurants.length <= 10^4

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

restaurants[i].length == 5

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= idi, ratingi, pricei, distancei <= 10^5

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= maxPrice, maxDistance <= 10^5

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

veganFriendlyi and veganFriendly are 0 or 1.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

All idi are distinct.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
