* [[https://leetcode.com/problems/divide-chocolate][1231. Divide
Chocolate]]
  :PROPERTIES:
  :CUSTOM_ID: divide-chocolate
  :END:
[[./solution/1200-1299/1231.Divide Chocolate/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

You have one chocolate bar that consists of some chunks. Each chunk has
its own sweetness given by the array sweetness.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

You want to share the chocolate with your K friends so you start cutting
the chocolate bar into K+1 pieces using K cuts, each piece consists of
some consecutive chunks.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Being generous, you will eat the piece with the minimum total sweetness
and give the other pieces to your friends.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Find the maximum total sweetness of the piece you can get by cutting the
chocolate bar optimally.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> sweetness = [1,2,3,4,5,6,7,8,9], K = 5
  <strong>Output:</strong> 6
  <b>Explanation: </b>You can divide the chocolate to [1,2,3], [4,5], [6], [7], [8], [9]
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> sweetness = [5,6,7,8,9,1,2,3,4], K = 8
  <strong>Output:</strong> 1
  <b>Explanation: </b>There is only one way to cut the bar into 9 pieces.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> sweetness = [1,2,2,1,2,2,1,2,2], K = 2
  <strong>Output:</strong> 5
  <b>Explanation: </b>You can divide the chocolate to [1,2,2], [1,2,2], [1,2,2]
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= K < sweetness.length <= 10^4

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= sweetness[i] <= 10^5

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
