* [[https://leetcode.com/problems/maximum-non-negative-product-in-a-matrix][1594.
Maximum Non Negative Product in a Matrix]]
  :PROPERTIES:
  :CUSTOM_ID: maximum-non-negative-product-in-a-matrix
  :END:
[[./solution/1500-1599/1594.Maximum Non Negative Product in a Matrix/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

You are given a rows x cols matrix grid. Initially, you are located at
the top-left corner (0, 0), and in each step, you can only move
right or down in the matrix.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Among all possible paths starting from the top-left corner (0, 0) and
ending in the bottom-right corner (rows - 1, cols - 1), find the path
with the maximum non-negative product. The product of a path is the
product of all integers in the grid cells visited along the path.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the maximum non-negative product modulo 109 + 7. If the maximum
product is negative return -1.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Notice that the modulo is performed after getting the maximum product.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> grid = [[-1,-2,-3],
  &nbsp;              [-2,-3,-3],
  &nbsp;              [-3,-3,-2]]
  <strong>Output:</strong> -1
  <strong>Explanation:</strong> It&#39;s not possible to get non-negative product in the path from (0, 0) to (2, 2), so return -1.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> grid = [[<strong>1</strong>,-2,1],
  &nbsp;              [<strong>1</strong>,<strong>-2</strong>,1],
  &nbsp;              [3,<strong>-4</strong>,<strong>1</strong>]]
  <strong>Output:</strong> 8
  <strong>Explanation:</strong> Maximum non-negative product is in bold (1 * 1 * -2 * -4 * 1 = 8).
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> grid = [[<strong>1</strong>, 3],
  &nbsp;              [<strong>0</strong>,<strong>-4</strong>]]
  <strong>Output:</strong> 0
  <strong>Explanation:</strong> Maximum non-negative product is in bold (1 * 0 * -4 = 0).
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 4:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> grid = [[ <strong>1</strong>, 4,4,0],
  &nbsp;              [<strong>-2</strong>, 0,0,1],
  &nbsp;              [ <strong>1</strong>,<strong>-1</strong>,<strong>1</strong>,<strong>1</strong>]]
  <strong>Output:</strong> 2
  <strong>Explanation:</strong> Maximum non-negative product is in bold (1 * -2 * 1 * -1 * 1 * 1 = 2).
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= rows, cols <= 15

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

-4 <= grid[i][j] <= 4

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
