* [[https://leetcode.com/problems/maximum-score-from-performing-multiplication-operations][1770.
Maximum Score from Performing Multiplication Operations]]
  :PROPERTIES:
  :CUSTOM_ID: maximum-score-from-performing-multiplication-operations
  :END:
[[./solution/1700-1799/1770.Maximum Score from Performing Multiplication Operations/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

You are given two integer arrays nums and multipliers of size n and m
respectively, where n >= m. The arrays are 1-indexed.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

You begin with a score of 0. You want to perform exactly m operations.
On the ith operation (1-indexed), you will:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

Choose one integer x from either the start or the end of the array nums.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Add multipliers[i] * x to your score.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Remove x from the array nums.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

#+begin_html
  <p>
#+end_html

Return the maximum score after performing m operations.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> nums = [1,2,3], multipliers = [3,2,1]
  <strong>Output:</strong> 14
  <strong>Explanation:</strong>&nbsp;An optimal solution is as follows:
  - Choose from the end, [1,2,<strong><u>3</u></strong>], adding 3 * 3 = 9 to the score.
  - Choose from the end, [1,<strong><u>2</u></strong>], adding 2 * 2 = 4 to the score.
  - Choose from the end, [<strong><u>1</u></strong>], adding 1 * 1 = 1 to the score.
  The total score is 9 + 4 + 1 = 14.</pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> nums = [-5,-3,-3,-2,7,1], multipliers = [-10,-5,3,4,6]
  <strong>Output:</strong> 102
  <strong>Explanation: </strong>An optimal solution is as follows:
  - Choose from the start, [<u><strong>-5</strong></u>,-3,-3,-2,7,1], adding -5 * -10 = 50 to the score.
  - Choose from the start, [<strong><u>-3</u></strong>,-3,-2,7,1], adding -3 * -5 = 15 to the score.
  - Choose from the start, [<strong><u>-3</u></strong>,-2,7,1], adding -3 * 3 = -9 to the score.
  - Choose from the end, [-2,7,<strong><u>1</u></strong>], adding 1 * 4 = 4 to the score.
  - Choose from the end, [-2,<strong><u>7</u></strong>], adding 7 * 6 = 42 to the score. 
  The total score is 50 + 15 - 9 + 4 + 42 = 102.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

n == nums.length

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

m == multipliers.length

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= m <= 103

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

m <= n <= 105

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

-1000 <= nums[i], multipliers[i] <= 1000

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
