* [[https://leetcode.com/problems/number-of-students-doing-homework-at-a-given-time][1450.
Number of Students Doing Homework at a Given Time]]
  :PROPERTIES:
  :CUSTOM_ID: number-of-students-doing-homework-at-a-given-time
  :END:
[[./solution/1400-1499/1450.Number of Students Doing Homework at a Given Time/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Given two integer arrays startTime and endTime and given an integer
queryTime.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

The ith student started doing their homework at the time startTime[i]
and finished it at time endTime[i].

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the number of students doing their homework at time queryTime.
More formally, return the number of students where queryTime lays in the
interval [startTime[i], endTime[i]] inclusive.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> startTime = [1,2,3], endTime = [3,2,7], queryTime = 4
  <strong>Output:</strong> 1
  <strong>Explanation:</strong> We have 3 students where:
  The first student started doing homework at time 1 and finished at time 3 and wasn&#39;t doing anything at time 4.
  The second student started doing homework at time 2 and finished at time 2 and also wasn&#39;t doing anything at time 4.
  The third student started doing homework at time 3 and finished at time 7 and was the only student doing homework at time 4.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> startTime = [4], endTime = [4], queryTime = 4
  <strong>Output:</strong> 1
  <strong>Explanation:</strong> The only student was doing their homework at the queryTime.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> startTime = [4], endTime = [4], queryTime = 5
  <strong>Output:</strong> 0
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 4:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> startTime = [1,1,1,1], endTime = [1,3,2,4], queryTime = 7
  <strong>Output:</strong> 0
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 5:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> startTime = [9,8,7,6,5,4,3,2,1], endTime = [10,10,10,10,10,10,10,10,10], queryTime = 5
  <strong>Output:</strong> 5
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

startTime.length == endTime.length

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= startTime.length <= 100

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= startTime[i] <= endTime[i] <= 1000

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= queryTime <= 1000

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
