* [[https://leetcode.com/problems/shopping-offers][638. Shopping
Offers]]
  :PROPERTIES:
  :CUSTOM_ID: shopping-offers
  :END:
[[./solution/0600-0699/0638.Shopping Offers/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

In LeetCode Store, there are n items to sell. Each item has a price.
However, there are some special offers, and a special offer consists of
one or more different kinds of items with a sale price.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

You are given an integer array price where price[i] is the price of the
ith item, and an integer array needs where needs[i] is the number of
pieces of the ith item you want to buy.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

You are also given an array special where special[i] is of size n + 1
where special[i][j] is the number of pieces of the jth item in the ith
offer and special[i][n] (i.e., the last integer in the array) is the
price of the ith offer.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the lowest price you have to pay for exactly certain items as
given, where you could make optimal use of the special offers. You are
not allowed to buy more items than you want, even if that would lower
the overall price. You could use any of the special offers as many times
as you want.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> price = [2,5], special = [[3,0,5],[1,2,10]], needs = [3,2]
  <strong>Output:</strong> 14
  <strong>Explanation:</strong> There are two kinds of items, A and B. Their prices are $2 and $5 respectively. 
  In special offer 1, you can pay $5 for 3A and 0B
  In special offer 2, you can pay $10 for 1A and 2B. 
  You need to buy 3A and 2B, so you may pay $10 for 1A and 2B (special offer #2), and $4 for 2A.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> price = [2,3,4], special = [[1,1,0,4],[2,2,1,9]], needs = [1,2,1]
  <strong>Output:</strong> 11
  <strong>Explanation:</strong> The price of A is $2, and $3 for B, $4 for C. 
  You may pay $4 for 1A and 1B, and $9 for 2A ,2B and 1C. 
  You need to buy 1A ,2B and 1C, so you may pay $4 for 1A and 1B (special offer #1), and $3 for 1B, $4 for 1C. 
  You cannot add more items, though only $9 for 2A ,2B and 1C.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

n == price.length

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

n == needs.length

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= n <= 6

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= price[i] <= 10

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= needs[i] <= 10

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= special.length <= 100

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

special[i].length == n + 1

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= special[i][j] <= 50

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
