* [[https://leetcode.com/problems/split-a-string-into-the-max-number-of-unique-substrings][1593.
Split a String Into the Max Number of Unique Substrings]]
  :PROPERTIES:
  :CUSTOM_ID: split-a-string-into-the-max-number-of-unique-substrings
  :END:
[[./solution/1500-1599/1593.Split a String Into the Max Number of Unique Substrings/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Given a string s, return the maximum number of unique substrings that
the given string can be split into.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

You can split string s into any list of non-empty substrings, where the
concatenation of the substrings forms the original string. However, you
must split the substrings such that all of them are unique.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

A substring is a contiguous sequence of characters within a string.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> s = &quot;ababccc&quot;
  <strong>Output:</strong> 5
  <strong>Explanation</strong>: One way to split maximally is [&#39;a&#39;, &#39;b&#39;, &#39;ab&#39;, &#39;c&#39;, &#39;cc&#39;]. Splitting like [&#39;a&#39;, &#39;b&#39;, &#39;a&#39;, &#39;b&#39;, &#39;c&#39;, &#39;cc&#39;] is not valid as you have &#39;a&#39; and &#39;b&#39; multiple times.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> s = &quot;aba&quot;
  <strong>Output:</strong> 2
  <strong>Explanation</strong>: One way to split maximally is [&#39;a&#39;, &#39;ba&#39;].
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> s = &quot;aa&quot;
  <strong>Output:</strong> 1
  <strong>Explanation</strong>: It is impossible to split the string any further.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

#+begin_html
  <p>
#+end_html

1 <= s.length <= 16

#+begin_html
  </p>
#+end_html

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

#+begin_html
  <p>
#+end_html

s contains only lower case English letters.

#+begin_html
  </p>
#+end_html

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
