* [[https://leetcode.com/problems/goat-latin][824. Goat Latin]]
  :PROPERTIES:
  :CUSTOM_ID: goat-latin
  :END:
[[./solution/0800-0899/0824.Goat Latin/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

A sentence S is given, composed of words separated by spaces. Each word
consists of lowercase and uppercase letters only.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

We would like to convert the sentence to "Goat Latin" (a made-up
language similar to Pig Latin.)

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

The rules of Goat Latin are as follows:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

If a word begins with a vowel (a, e, i, o, or u), append "ma" to the end
of the word. For example, the word 'apple' becomes 'applema'.  

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

If a word begins with a consonant (i.e. not a vowel), remove the first
letter and append it to the end, then add "ma". For example, the word
"goat" becomes "oatgma".  

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Add one letter 'a' to the end of each word per its word index in the
sentence, starting with 1. For example, the first word gets "a" added to
the end, the second word gets "aa" added to the end and so on.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

#+begin_html
  <p>
#+end_html

Return the final sentence representing the conversion from S to
Goat Latin. 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input: </strong>&quot;I speak Goat Latin&quot;

  <strong>Output: </strong>&quot;Imaa peaksmaaa oatGmaaaa atinLmaaaaa&quot;

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input: </strong>&quot;The quick brown fox jumped over the lazy dog&quot;

  <strong>Output: </strong>&quot;heTmaa uickqmaaa rownbmaaaa oxfmaaaaa umpedjmaaaaaa overmaaaaaaa hetmaaaaaaaa azylmaaaaaaaaa ogdmaaaaaaaaaa&quot;

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Notes:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

S contains only uppercase, lowercase and spaces. Exactly one space
between each word.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= S.length <= 150.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
