* [[https://leetcode.com/problems/can-convert-string-in-k-moves][1540.
Can Convert String in K Moves]]
  :PROPERTIES:
  :CUSTOM_ID: can-convert-string-in-k-moves
  :END:
[[./solution/1500-1599/1540.Can Convert String in K Moves/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Given two strings s and t, your goal is to convert s into t in k moves
or less.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

During the ith (1 <= i <= k) move you can:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

Choose any index j (1-indexed) from s, such that 1 <= j <= s.length and
j has not been chosen in any previous move, and shift the character at
that index i times.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Do nothing.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

#+begin_html
  <p>
#+end_html

Shifting a character means replacing it by the next letter in the
alphabet (wrapping around so that 'z' becomes 'a'). Shifting a character
by i means applying the shift operations i times.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Remember that any index j can be picked at most once.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return true if it's possible to convert s into t in no more
than k moves, otherwise return false.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> s = &quot;input&quot;, t = &quot;ouput&quot;, k = 9
  <strong>Output:</strong> true
  <b>Explanation: </b>In the 6th move, we shift &#39;i&#39; 6 times to get &#39;o&#39;. And in the 7th move we shift &#39;n&#39; to get &#39;u&#39;.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> s = &quot;abc&quot;, t = &quot;bcd&quot;, k = 10
  <strong>Output:</strong> false
  <strong>Explanation: </strong>We need to shift each character in s one time to convert it into t. We can shift &#39;a&#39; to &#39;b&#39; during the 1st move. However, there is no way to shift the other characters in the remaining moves to obtain t from s.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> s = &quot;aab&quot;, t = &quot;bbb&quot;, k = 27
  <strong>Output:</strong> true
  <b>Explanation: </b>In the 1st move, we shift the first &#39;a&#39; 1 time to get &#39;b&#39;. In the 27th move, we shift the second &#39;a&#39; 27 times to get &#39;b&#39;.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= s.length, t.length <= 10^5

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= k <= 10^9

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

s, t contain only lowercase English letters.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
