* [[https://leetcode.com/problems/capacity-to-ship-packages-within-d-days][1011.
Capacity To Ship Packages Within D Days]]
  :PROPERTIES:
  :CUSTOM_ID: capacity-to-ship-packages-within-d-days
  :END:
[[./solution/1000-1099/1011.Capacity To Ship Packages Within D Days/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

A conveyor belt has packages that must be shipped from one port to
another within D days.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

The ith package on the conveyor belt has a weight of weights[i]. Each
day, we load the ship with packages on the conveyor belt (in the order
given by weights). We may not load more weight than the maximum weight
capacity of the ship.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the least weight capacity of the ship that will result in all the
packages on the conveyor belt being shipped within D days.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> weights = [1,2,3,4,5,6,7,8,9,10], D = 5
  <strong>Output:</strong> 15
  <strong>Explanation:</strong> A ship capacity of 15 is the minimum to ship all the packages in 5 days like this:
  1st day: 1, 2, 3, 4, 5
  2nd day: 6, 7
  3rd day: 8
  4th day: 9
  5th day: 10

  Note that the cargo must be shipped in the order given, so using a ship of capacity 14 and splitting the packages into parts like (2, 3, 4, 5), (1, 6, 7), (8), (9), (10) is not allowed.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> weights = [3,2,2,4,1,4], D = 3
  <strong>Output:</strong> 6
  <strong>Explanation:</strong> A ship capacity of 6 is the minimum to ship all the packages in 3 days like this:
  1st day: 3, 2
  2nd day: 2, 4
  3rd day: 1, 4
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> weights = [1,2,3,1,1], D = 4
  <strong>Output:</strong> 3
  <strong>Explanation:</strong>
  1st day: 1
  2nd day: 2
  3rd day: 3
  4th day: 1, 1
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= D <= weights.length <= 5 * 104

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= weights[i] <= 500

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html

#+begin_html
  <!-- tabs:end -->
#+end_html
