* [[https://leetcode.com/problems/remove-sub-folders-from-the-filesystem][1233.
Remove Sub-Folders from the Filesystem]]
  :PROPERTIES:
  :CUSTOM_ID: remove-sub-folders-from-the-filesystem
  :END:
[[./solution/1200-1299/1233.Remove Sub-Folders from the Filesystem/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Given a list of folders, remove all sub-folders in those folders and
return in any order the folders after removing.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

If a folder[i] is located within another folder[j], it is called
a sub-folder of it.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

The format of a path is one or more concatenated strings of the
form: / followed by one or more lowercase English letters. For
example, /leetcode and /leetcode/problems are valid paths while an empty
string and / are not.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> folder = [&quot;/a&quot;,&quot;/a/b&quot;,&quot;/c/d&quot;,&quot;/c/d/e&quot;,&quot;/c/f&quot;]
  <strong>Output:</strong> [&quot;/a&quot;,&quot;/c/d&quot;,&quot;/c/f&quot;]
  <strong>Explanation:</strong> Folders &quot;/a/b/&quot; is a subfolder of &quot;/a&quot; and &quot;/c/d/e&quot; is inside of folder &quot;/c/d&quot; in our filesystem.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> folder = [&quot;/a&quot;,&quot;/a/b/c&quot;,&quot;/a/b/d&quot;]
  <strong>Output:</strong> [&quot;/a&quot;]
  <strong>Explanation:</strong> Folders &quot;/a/b/c&quot; and &quot;/a/b/d/&quot; will be removed because they are subfolders of &quot;/a&quot;.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> folder = [&quot;/a/b/c&quot;,&quot;/a/b/ca&quot;,&quot;/a/b/d&quot;]
  <strong>Output:</strong> [&quot;/a/b/c&quot;,&quot;/a/b/ca&quot;,&quot;/a/b/d&quot;]
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= folder.length <= 4 * 10^4

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

2 <= folder[i].length <= 100

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

folder[i] contains only lowercase letters and '/'

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

folder[i] always starts with character '/'

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Each folder name is unique.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
