* [[https://leetcode.com/problems/single-row-keyboard][1165. Single-Row
Keyboard]]
  :PROPERTIES:
  :CUSTOM_ID: single-row-keyboard
  :END:
[[./solution/1100-1199/1165.Single-Row Keyboard/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

There is a special keyboard with all keys in a single row.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Given a string keyboard of length 26 indicating the layout of the
keyboard (indexed from 0 to 25). Initially, your finger is at index 0.
To type a character, you have to move your finger to the index of the
desired character. The time taken to move your finger from index i to
index j is |i - j|.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

You want to type a string word. Write a function to calculate how much
time it takes to type it with one finger.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> keyboard = &quot;abcdefghijklmnopqrstuvwxyz&quot;, word = &quot;cba&quot;
  <strong>Output:</strong> 4
  <strong>Explanation: </strong>The index moves from 0 to 2 to write &#39;c&#39; then to 1 to write &#39;b&#39; then to 0 again to write &#39;a&#39;.
  Total time = 2 + 1 + 1 = 4. 
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> keyboard = &quot;pqrstuvwxyzabcdefghijklmno&quot;, word = &quot;leetcode&quot;
  <strong>Output:</strong> 73
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

keyboard.length == 26

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

keyboard contains each English lowercase letter exactly once in some
order.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= word.length <= 104

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

word[i] is an English lowercase letter.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
