* [[https://leetcode.com/problems/construct-the-rectangle][492.
Construct the Rectangle]]
  :PROPERTIES:
  :CUSTOM_ID: construct-the-rectangle
  :END:
[[./solution/0400-0499/0492.Construct the Rectangle/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

A web developer needs to know how to design a web page's size. So, given
a specific rectangular web page's area, your job by now is to design a
rectangular web page, whose length L and width W satisfy the following
requirements:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ol>
#+end_html

#+begin_html
  <li>
#+end_html

The area of the rectangular web page you designed must equal to the
given target area.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

The width W should not be larger than the length L, which means L >= W.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

The difference between length L and width W should be as small as
possible.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ol>
#+end_html

#+begin_html
  <p>
#+end_html

Return an array [L, W] where L and W are the length and width of the web
page you designed in sequence.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> area = 4
  <strong>Output:</strong> [2,2]
  <strong>Explanation:</strong> The target area is 4, and all the possible ways to construct it are [1,4], [2,2], [4,1]. 
  But according to requirement 2, [1,4] is illegal; according to requirement 3,  [4,1] is not optimal compared to [2,2]. So the length L is 2, and the width W is 2.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> area = 37
  <strong>Output:</strong> [37,1]
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> area = 122122
  <strong>Output:</strong> [427,286]
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= area <= 107

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
  class Solution:
      def constructRectangle(self, area: int) -> List[int]:
          sr = int(math.sqrt(area))
          l = w = sr
          while l <= area and w >= 1:
              s = l * w
              if s == area:
                  break
              if s > area:
                  w -= 1
              else:
                  l += 1
          return [l, w]
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
  class Solution {
      public int[] constructRectangle(int area) {
          int sr = (int) Math.sqrt(area);
          int l = sr, w = sr;
          while (l <= area && w >= 1) {
              int s = l * w;
              if (s == area) break;
              if (s > area) --w;
              else ++l;
          }
          return new int[]{l, w};
      }
  }
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
