* [[https://leetcode.com/problems/maximum-number-of-events-that-can-be-attended-ii][1751.
Maximum Number of Events That Can Be Attended II]]
  :PROPERTIES:
  :CUSTOM_ID: maximum-number-of-events-that-can-be-attended-ii
  :END:
[[./solution/1700-1799/1751.Maximum Number of Events That Can Be Attended II/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

You are given an array of events where events[i] = [startDayi, endDayi,
valuei]. The ith event starts at startDayi and ends at endDayi, and if
you attend this event, you will receive a value of valuei. You are also
given an integer k which represents the maximum number of events you can
attend.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

You can only attend one event at a time. If you choose to attend an
event, you must attend the entire event. Note that the end day is
inclusive: that is, you cannot attend two events where one of them
starts and the other ends on the same day.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the maximum sum of values that you can receive by attending
events.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> events = [[1,2,4],[3,4,3],[2,3,1]], k = 2
  <strong>Output:</strong> 7
  <strong>Explanation: </strong>Choose the green events, 0 and 1 (0-indexed) for a total value of 4 + 3 = 7.</pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> events = [[1,2,4],[3,4,3],[2,3,10]], k = 2
  <strong>Output:</strong> 10
  <strong>Explanation:</strong> Choose event 2 for a total value of 10.
  Notice that you cannot attend any other event as they overlap, and that you do <strong>not</strong> have to attend k events.</pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> events = [[1,1,1],[2,2,2],[3,3,3],[4,4,4]], k = 3
  <strong>Output:</strong> 9
  <strong>Explanation:</strong> Although the events do not overlap, you can only attend 3 events. Pick the highest valued three.</pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= k <= events.length

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= k * events.length <= 106

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= startDayi <= endDayi <= 109

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= valuei <= 106

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
