* [[https://leetcode.com/problems/dota2-senate][649. Dota2 Senate]]
  :PROPERTIES:
  :CUSTOM_ID: dota2-senate
  :END:
[[./solution/0600-0699/0649.Dota2 Senate/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

In the world of Dota2, there are two parties: the Radiant and the Dire.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

The Dota2 senate consists of senators coming from two parties. Now the
senate wants to make a decision about a change in the Dota2 game. The
voting for this change is a round-based procedure. In each round, each
senator can exercise one of the two rights:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ol>
#+end_html

#+begin_html
  <li>
#+end_html

Ban one senator's right: A senator can make another senator lose all his
rights in this and all the following rounds.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Announce the victory: If this senator found the senators who still have
rights to vote are all from the same party, he can announce the victory
and make the decision about the change in the game.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ol>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Given a string representing each senator's party belonging. The
character 'R' and 'D' represent the Radiant party and the Dire party
respectively. Then if there are n senators, the size of the given string
will be n.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

The round-based procedure starts from the first senator to the last
senator in the given order. This procedure will last until the end of
voting. All the senators who have lost their rights will be skipped
during the procedure.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Suppose every senator is smart enough and will play the best strategy
for his own party, you need to predict which party will finally announce
the victory and make the change in the Dota2 game. The output should be
Radiant or Dire.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <b>Input:</b> &quot;RD&quot;

  <b>Output:</b> &quot;Radiant&quot;

  <b>Explanation:</b> The first senator comes from Radiant and he can just ban the next senator&#39;s right in the round 1. 

  And the second senator can&#39;t exercise any rights any more since his right has been banned. 

  And in the round 2, the first senator can just announce the victory since he is the only guy in the senate who can vote.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <b>Input:</b> &quot;RDD&quot;

  <b>Output:</b> &quot;Dire&quot;

  <b>Explanation:</b> 

  The first senator comes from Radiant and he can just ban the next senator&#39;s right in the round 1. 

  And the second senator can&#39;t exercise any rights anymore since his right has been banned. 

  And the third senator comes from Dire and he can ban the first senator&#39;s right in the round 1. 

  And in the round 2, the third senator can just announce the victory since he is the only guy in the senate who can vote.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Note:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ol>
#+end_html

#+begin_html
  <li>
#+end_html

The length of the given string will in the range [1, 10,000].

#+begin_html
  </li>
#+end_html

#+begin_html
  </ol>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
