* [[https://leetcode.com/problems/the-earliest-moment-when-everyone-become-friends][1101.
The Earliest Moment When Everyone Become Friends]]
  :PROPERTIES:
  :CUSTOM_ID: the-earliest-moment-when-everyone-become-friends
  :END:
[[./solution/1100-1199/1101.The Earliest Moment When Everyone Become Friends/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

In a social group, there are N people, with unique integer ids from 0 to
N-1.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

We have a list of logs, where each logs[i] = [timestamp, id_A, id_B]
contains a non-negative integer timestamp, and the ids of two different
people.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Each log represents the time in which two different people became
friends.  Friendship is symmetric: if A is friends with B, then B is
friends with A.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Let's say that person A is acquainted with person B if A is friends with
B, or A is a friend of someone acquainted with B.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the earliest time for which every person became acquainted with
every other person. Return -1 if there is no such earliest time.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input: </strong>logs = <span id="example-input-1-1">[[20190101,0,1],[20190104,3,4],[20190107,2,3],[20190211,1,5],[20190224,2,4],[20190301,0,3],[20190312,1,2],[20190322,4,5]]</span>, N = <span id="example-input-1-2">6</span>
  <strong>Output: </strong><span id="example-output-1">20190301</span>
  <strong>Explanation: </strong>
  The first event occurs at timestamp = 20190101 and after 0 and 1 become friends we have the following friendship groups [0,1], [2], [3], [4], [5].
  The second event occurs at timestamp = 20190104 and after 3 and 4 become friends we have the following friendship groups [0,1], [2], [3,4], [5].
  The third event occurs at timestamp = 20190107 and after 2 and 3 become friends we have the following friendship groups [0,1], [2,3,4], [5].
  The fourth event occurs at timestamp = 20190211 and after 1 and 5 become friends we have the following friendship groups [0,1,5], [2,3,4].
  The fifth event occurs at timestamp = 20190224 and as 2 and 4 are already friend anything happens.
  The sixth event occurs at timestamp = 20190301 and after 0 and 3 become friends we have that all become friends.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Note:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ol>
#+end_html

#+begin_html
  <li>
#+end_html

2 <= N <= 100

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= logs.length <= 10^4

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= logs[i][0] <= 10^9

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= logs[i][1], logs[i][2] <= N - 1

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

It's guaranteed that all timestamps in logs[i][0] are different.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

logs are not necessarily ordered by some criteria.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

logs[i][1] != logs[i][2]

#+begin_html
  </li>
#+end_html

#+begin_html
  </ol>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
