* [[https://leetcode.com/problems/search-suggestions-system][1268.
Search Suggestions System]]
  :PROPERTIES:
  :CUSTOM_ID: search-suggestions-system
  :END:
[[./solution/1200-1299/1268.Search Suggestions System/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Given an array of strings products and a string searchWord. We want to
design a system that suggests at most three product names from
products after each character of searchWord is typed. Suggested products
should have common prefix with the searchWord. If there are more than
three products with a common prefix return the three lexicographically
minimums products.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return list of lists of the suggested products after each character
of searchWord is typed. 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> products = [&quot;mobile&quot;,&quot;mouse&quot;,&quot;moneypot&quot;,&quot;monitor&quot;,&quot;mousepad&quot;], searchWord = &quot;mouse&quot;
  <strong>Output:</strong> [
  [&quot;mobile&quot;,&quot;moneypot&quot;,&quot;monitor&quot;],
  [&quot;mobile&quot;,&quot;moneypot&quot;,&quot;monitor&quot;],
  [&quot;mouse&quot;,&quot;mousepad&quot;],
  [&quot;mouse&quot;,&quot;mousepad&quot;],
  [&quot;mouse&quot;,&quot;mousepad&quot;]
  ]
  <strong>Explanation:</strong> products sorted lexicographically = [&quot;mobile&quot;,&quot;moneypot&quot;,&quot;monitor&quot;,&quot;mouse&quot;,&quot;mousepad&quot;]
  After typing m and mo all products match and we show user [&quot;mobile&quot;,&quot;moneypot&quot;,&quot;monitor&quot;]
  After typing mou, mous and mouse the system suggests [&quot;mouse&quot;,&quot;mousepad&quot;]
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> products = [&quot;havana&quot;], searchWord = &quot;havana&quot;
  <strong>Output:</strong> [[&quot;havana&quot;],[&quot;havana&quot;],[&quot;havana&quot;],[&quot;havana&quot;],[&quot;havana&quot;],[&quot;havana&quot;]]
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> products = [&quot;bags&quot;,&quot;baggage&quot;,&quot;banner&quot;,&quot;box&quot;,&quot;cloths&quot;], searchWord = &quot;bags&quot;
  <strong>Output:</strong> [[&quot;baggage&quot;,&quot;bags&quot;,&quot;banner&quot;],[&quot;baggage&quot;,&quot;bags&quot;,&quot;banner&quot;],[&quot;baggage&quot;,&quot;bags&quot;],[&quot;bags&quot;]]
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 4:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> products = [&quot;havana&quot;], searchWord = &quot;tatiana&quot;
  <strong>Output:</strong> [[],[],[],[],[],[],[]]
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= products.length <= 1000

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

There are no repeated elements in products.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= Σ products[i].length <= 2 * 10^4

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

All characters of products[i] are lower-case English letters.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= searchWord.length <= 1000

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

All characters of searchWord are lower-case English letters.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
