* [[https://leetcode.com/problems/final-prices-with-a-special-discount-in-a-shop][1475.
Final Prices With a Special Discount in a Shop]]
  :PROPERTIES:
  :CUSTOM_ID: final-prices-with-a-special-discount-in-a-shop
  :END:
[[./solution/1400-1499/1475.Final Prices With a Special Discount in a Shop/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Given the array prices where prices[i] is the price of the ith item in a
shop. There is a special discount for items in the shop, if you buy the
ith item, then you will receive a discount equivalent to prices[j] where
j is the minimum index such that j > i and prices[j] <= prices[i],
otherwise, you will not receive any discount at all.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return an array where the ith element is the final price you will pay
for the ith item of the shop considering the special discount.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> prices = [8,4,6,2,3]
  <strong>Output:</strong> [4,2,4,2,3]
  <strong>Explanation:</strong>&nbsp;
  For item 0 with price[0]=8 you will receive a discount equivalent to prices[1]=4, therefore, the final price you will pay is 8 - 4 = 4.&nbsp;
  For item 1 with price[1]=4 you will receive a discount equivalent to prices[3]=2, therefore, the final price you will pay is 4 - 2 = 2.&nbsp;
  For item 2 with price[2]=6 you will receive a discount equivalent to prices[3]=2, therefore, the final price you will pay is 6 - 2 = 4.&nbsp;
  For items 3 and 4 you will not receive any discount at all.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> prices = [1,2,3,4,5]
  <strong>Output:</strong> [1,2,3,4,5]
  <strong>Explanation:</strong> In this case, for all items, you will not receive any discount at all.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> prices = [10,1,1,6]
  <strong>Output:</strong> [9,0,1,6]
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= prices.length <= 500

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= prices[i] <= 10^3

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
