* [[https://leetcode-cn.com/problems/analyze-user-website-visit-pattern][1152.
用户网站访问行为分析]]
  :PROPERTIES:
  :CUSTOM_ID: 用户网站访问行为分析
  :END:
[[./solution/1100-1199/1152.Analyze User Website Visit Pattern/README_EN.org][English
Version]]

** 题目描述
   :PROPERTIES:
   :CUSTOM_ID: 题目描述
   :END:

#+begin_html
  <!-- 这里写题目描述 -->
#+end_html

#+begin_html
  <p>
#+end_html

为了评估某网站的用户转化率，我们需要对用户的访问行为进行分析，并建立用户行为模型。日志文件中已经记录了用户名、访问时间
以及 页面路径。

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

为了方便分析，日志文件中的 N 条记录已经被解析成三个长度相同且长度都为 N
的数组，分别是：用户名 username，访问时间 timestamp 和
页面路径 website。第 i 条记录意味着用户名是 username[i] 的用户在
timestamp[i] 的时候访问了路径为 website[i] 的页面。

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

我们需要找到用户访问网站时的 『共性行为路径』，也就是有最多的用户都
至少按某种次序访问过一次 的三个页面路径。需要注意的是，用户
可能不是连续访问 这三个路径的。

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

『共性行为路径』是一个 长度为 3
的页面路径列表，列表中的路径 不必不同，并且按照访问时间的先后升序排列。

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

如果有多个满足要求的答案，那么就请返回按字典序排列最小的那个。（页面路径列表 X 按字典序小于 Y
的前提条件是：X[0] < Y[0] 或 X[0] == Y[0] 且 (X[1] < Y[1] 或 X[1] ==
Y[1] 且 X[2] < Y[2])）

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

题目保证一个用户会至少访问 3
个路径一致的页面，并且一个用户不会在同一时间访问两个路径不同的页面。

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

示例：

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre><strong>输入：</strong>username = [&quot;joe&quot;,&quot;joe&quot;,&quot;joe&quot;,&quot;james&quot;,&quot;james&quot;,&quot;james&quot;,&quot;james&quot;,&quot;mary&quot;,&quot;mary&quot;,&quot;mary&quot;], timestamp = [1,2,3,4,5,6,7,8,9,10], website = [&quot;home&quot;,&quot;about&quot;,&quot;career&quot;,&quot;home&quot;,&quot;cart&quot;,&quot;maps&quot;,&quot;home&quot;,&quot;home&quot;,&quot;about&quot;,&quot;career&quot;]
  <strong>输出：</strong>[&quot;home&quot;,&quot;about&quot;,&quot;career&quot;]
  <strong>解释：</strong>
  由示例输入得到的记录如下：
  [&quot;joe&quot;, 1, &quot;home&quot;]
  [&quot;joe&quot;, 2, &quot;about&quot;]
  [&quot;joe&quot;, 3, &quot;career&quot;]
  [&quot;james&quot;, 4, &quot;home&quot;]
  [&quot;james&quot;, 5, &quot;cart&quot;]
  [&quot;james&quot;, 6, &quot;maps&quot;]
  [&quot;james&quot;, 7, &quot;home&quot;]
  [&quot;mary&quot;, 8, &quot;home&quot;]
  [&quot;mary&quot;, 9, &quot;about&quot;]
  [&quot;mary&quot;, 10, &quot;career&quot;]
  有 <strong>2</strong> 个用户至少访问过一次 (&quot;home&quot;, &quot;about&quot;, &quot;career&quot;)。
  有 <strong>1</strong> 个用户至少访问过一次 (&quot;home&quot;, &quot;cart&quot;, &quot;maps&quot;)。
  有 <strong>1</strong> 个用户至少访问过一次 (&quot;home&quot;, &quot;cart&quot;, &quot;home&quot;)。
  有 <strong>1</strong> 个用户至少访问过一次 (&quot;home&quot;, &quot;maps&quot;, &quot;home&quot;)。
  有 <strong>1</strong> 个用户至少访问过一次 (&quot;cart&quot;, &quot;maps&quot;, &quot;home&quot;)。
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

提示：

#+begin_html
  </p>
#+end_html

#+begin_html
  <ol>
#+end_html

#+begin_html
  <li>
#+end_html

3 <= N = username.length = timestamp.length = website.length <= 50

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= username[i].length <= 10

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= timestamp[i] <= 10^9

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= website[i].length <= 10

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

username[i] 和 website[i] 都只含小写字符

#+begin_html
  </li>
#+end_html

#+begin_html
  </ol>
#+end_html

** 解法
   :PROPERTIES:
   :CUSTOM_ID: 解法
   :END:

#+begin_html
  <!-- 这里可写通用的实现逻辑 -->
#+end_html

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:

#+begin_html
  <!-- 这里可写当前语言的特殊实现逻辑 -->
#+end_html

#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:

#+begin_html
  <!-- 这里可写当前语言的特殊实现逻辑 -->
#+end_html

#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
