* [[https://leetcode.com/problems/analyze-user-website-visit-pattern][1152.
Analyze User Website Visit Pattern]]
  :PROPERTIES:
  :CUSTOM_ID: analyze-user-website-visit-pattern
  :END:
[[./solution/1100-1199/1152.Analyze User Website Visit Pattern/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

We are given some website visits: the user with name username[i] visited
the website website[i] at time timestamp[i].

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

A 3-sequence is a list of websites of length 3 sorted in ascending
order by the time of their visits.  (The websites in a 3-sequence are
not necessarily distinct.)

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Find the 3-sequence visited by the largest number of users. If there is
more than one solution, return the lexicographically smallest such
3-sequence.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input: </strong>username = <span>[&quot;joe&quot;,&quot;joe&quot;,&quot;joe&quot;,&quot;james&quot;,&quot;james&quot;,&quot;james&quot;,&quot;james&quot;,&quot;mary&quot;,&quot;mary&quot;,&quot;mary&quot;]</span>, timestamp = <span id="example-input-1-2">[1,2,3,4,5,6,7,8,9,10]</span>, website = <span id="example-input-1-3">[&quot;home&quot;,&quot;about&quot;,&quot;career&quot;,&quot;home&quot;,&quot;cart&quot;,&quot;maps&quot;,&quot;home&quot;,&quot;home&quot;,&quot;about&quot;,&quot;career&quot;]</span>
  <strong>Output: </strong><span id="example-output-1">[&quot;home&quot;,&quot;about&quot;,&quot;career&quot;]</span>
  <strong>Explanation: </strong>
  The tuples in this example are:
  [&quot;joe&quot;, 1, &quot;home&quot;]
  [&quot;joe&quot;, 2, &quot;about&quot;]
  [&quot;joe&quot;, 3, &quot;career&quot;]
  [&quot;james&quot;, 4, &quot;home&quot;]
  [&quot;james&quot;, 5, &quot;cart&quot;]
  [&quot;james&quot;, 6, &quot;maps&quot;]
  [&quot;james&quot;, 7, &quot;home&quot;]
  [&quot;mary&quot;, 8, &quot;home&quot;]
  [&quot;mary&quot;, 9, &quot;about&quot;]
  [&quot;mary&quot;, 10, &quot;career&quot;]
  The 3-sequence (&quot;home&quot;, &quot;about&quot;, &quot;career&quot;) was visited at least once by <strong>2</strong> users.
  The 3-sequence (&quot;home&quot;, &quot;cart&quot;, &quot;maps&quot;) was visited at least once by 1 user.
  The 3-sequence (&quot;home&quot;, &quot;cart&quot;, &quot;home&quot;) was visited at least once by 1 user.
  The 3-sequence (&quot;home&quot;, &quot;maps&quot;, &quot;home&quot;) was visited at least once by 1 user.
  The 3-sequence (&quot;cart&quot;, &quot;maps&quot;, &quot;home&quot;) was visited at least once by 1 user.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Note:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ol>
#+end_html

#+begin_html
  <li>
#+end_html

3 <= N = username.length = timestamp.length = website.length <= 50

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= username[i].length <= 10

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= timestamp[i] <= 10^9

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= website[i].length <= 10

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Both username[i] and website[i] contain only lowercase characters.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

It is guaranteed that there is at least one user who visited at least 3
websites.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

No user visits two websites at the same time.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ol>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
