* [[https://leetcode.com/problems/split-bst][776. Split BST]]
  :PROPERTIES:
  :CUSTOM_ID: split-bst
  :END:
[[./solution/0700-0799/0776.Split BST/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Given a Binary Search Tree (BST) with root node root, and a target value
V, split the tree into two subtrees where one subtree has nodes that are
all smaller or equal to the target value, while the other subtree has
all nodes that are greater than the target value.  It's not necessarily
the case that the tree contains a node with value V.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Additionally, most of the structure of the original tree should remain. 
Formally, for any child C with parent P in the original tree, if they
are both in the same subtree after the split, then node C should still
have the parent P.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

You should output the root TreeNode of both subtrees after splitting, in
any order.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> root = [4,2,6,1,3,5,7], V = 2

  <strong>Output:</strong> [[2,1],[4,3,6,null,null,5,7]]

  <strong>Explanation:</strong>

  Note that root, output[0], and output[1] are TreeNode objects, not arrays.



  The given tree [4,2,6,1,3,5,7] is represented by the following diagram:



            4

          /   \

        2      6

       / \    / \

      1   3  5   7



  while the diagrams for the outputs are:



            4

          /   \

        3      6      and    2

              / \           /

             5   7         1

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Note:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ol>
#+end_html

#+begin_html
  <li>
#+end_html

The size of the BST will not exceed 50.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

The BST is always valid and each node's value is different.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ol>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
