* [[https://leetcode.com/problems/sliding-window-maximum][239. Sliding
Window Maximum]]
  :PROPERTIES:
  :CUSTOM_ID: sliding-window-maximum
  :END:
[[./solution/0200-0299/0239.Sliding Window Maximum/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

You are given an array of integers nums, there is a sliding window of
size k which is moving from the very left of the array to the very
right. You can only see the k numbers in the window. Each time the
sliding window moves right by one position.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the max sliding window.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> nums = [1,3,-1,-3,5,3,6,7], k = 3
  <strong>Output:</strong> [3,3,5,5,6,7]
  <strong>Explanation:</strong> 
  Window position                Max
  ---------------               -----
  [1  3  -1] -3  5  3  6  7       <strong>3</strong>
   1 [3  -1  -3] 5  3  6  7       <strong>3</strong>
   1  3 [-1  -3  5] 3  6  7      <strong> 5</strong>
   1  3  -1 [-3  5  3] 6  7       <strong>5</strong>
   1  3  -1  -3 [5  3  6] 7       <strong>6</strong>
   1  3  -1  -3  5 [3  6  7]      <strong>7</strong>
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> nums = [1], k = 1
  <strong>Output:</strong> [1]
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> nums = [1,-1], k = 1
  <strong>Output:</strong> [1,-1]
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 4:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> nums = [9,11], k = 2
  <strong>Output:</strong> [11]
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 5:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> nums = [4,-2], k = 2
  <strong>Output:</strong> [4]
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= nums.length <= 105

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

-104 <= nums[i] <= 104

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= k <= nums.length

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *JavaScript*
    :PROPERTIES:
    :CUSTOM_ID: javascript
    :END:
#+begin_src js
  /**
   * @param {number[]} nums
   * @param {number} k
   * @return {number[]}
   */
  var maxSlidingWindow = function (nums, k) {
      let len = nums.length;
      if (len < k) return [];
      let res = [], win = [];
      for (let i = 0; i < k; i++) {
          while (win.length > 0 && nums[i] >= nums[win[win.length - 1]])
              win.pop();
          win.push(i);
      }
      res.push(nums[win[0]]);
      for (let i = k; i < len; i++) {
          while (win.length > 0 && nums[i] >= nums[win[win.length - 1]])
              win.pop();
          if (win.length > 0 && win[0] < i - k + 1)
              win.shift();
          win.push(i);
          res.push(nums[win[0]]);
      }
      return res;
  };
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
