* [[https://leetcode.com/problems/maximum-repeating-substring][1668.
Maximum Repeating Substring]]
  :PROPERTIES:
  :CUSTOM_ID: maximum-repeating-substring
  :END:
[[./solution/1600-1699/1668.Maximum Repeating Substring/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

For a string sequence, a string word is k-repeating if word concatenated
k times is a substring of sequence. The word's maximum k-repeating value
is the highest value k where word is k-repeating in sequence. If word is
not a substring of sequence, word's maximum k-repeating value is 0.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Given strings sequence and word, return the maximum k-repeating value of
word in sequence.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> sequence = &quot;ababc&quot;, word = &quot;ab&quot;
  <strong>Output:</strong> 2
  <strong>Explanation: </strong>&quot;abab&quot; is a substring in &quot;<u>abab</u>c&quot;.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> sequence = &quot;ababc&quot;, word = &quot;ba&quot;
  <strong>Output:</strong> 1
  <strong>Explanation: </strong>&quot;ba&quot; is a substring in &quot;a<u>ba</u>bc&quot;. &quot;baba&quot; is not a substring in &quot;ababc&quot;.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> sequence = &quot;ababc&quot;, word = &quot;ac&quot;
  <strong>Output:</strong> 0
  <strong>Explanation: </strong>&quot;ac&quot; is not a substring in &quot;ababc&quot;. 
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= sequence.length <= 100

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= word.length <= 100

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

sequence and word contains only lowercase English letters.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
