* [[https://leetcode.com/problems/replace-the-substring-for-balanced-string][1234.
Replace the Substring for Balanced String]]
  :PROPERTIES:
  :CUSTOM_ID: replace-the-substring-for-balanced-string
  :END:
[[./solution/1200-1299/1234.Replace the Substring for Balanced String/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

You are given a string containing only 4 kinds of characters 'Q', 'W',
'E' and 'R'.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

A string is said to be balanced if each of its characters appears n/4
times where n is the length of the string.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the minimum length of the substring that can be replaced with any
other string of the same length to make the original string s balanced.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return 0 if the string is already balanced.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> s = &quot;QWER&quot;
  <strong>Output:</strong> 0
  <strong>Explanation: </strong>s is already balanced.</pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> s = &quot;QQWE&quot;
  <strong>Output:</strong> 1
  <strong>Explanation: </strong>We need to replace a &#39;Q&#39; to &#39;R&#39;, so that &quot;RQWE&quot; (or &quot;QRWE&quot;) is balanced.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> s = &quot;QQQW&quot;
  <strong>Output:</strong> 2
  <strong>Explanation: </strong>We can replace the first &quot;QQ&quot; to &quot;ER&quot;. 
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 4:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> s = &quot;QQQQ&quot;
  <strong>Output:</strong> 3
  <strong>Explanation: </strong>We can replace the last 3 &#39;Q&#39; to make s = &quot;QWER&quot;.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= s.length <= 10^5

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

s.length is a multiple of 4

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

s contains only 'Q', 'W', 'E' and 'R'.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
