* [[https://leetcode.com/problems/soup-servings][808. Soup Servings]]
  :PROPERTIES:
  :CUSTOM_ID: soup-servings
  :END:
[[./solution/0800-0899/0808.Soup Servings/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

There are two types of soup: type A and type B. Initially we have N ml
of each type of soup. There are four kinds of operations:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ol>
#+end_html

#+begin_html
  <li>
#+end_html

Serve 100 ml of soup A and 0 ml of soup B

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Serve 75 ml of soup A and 25 ml of soup B

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Serve 50 ml of soup A and 50 ml of soup B

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Serve 25 ml of soup A and 75 ml of soup B

#+begin_html
  </li>
#+end_html

#+begin_html
  </ol>
#+end_html

#+begin_html
  <p>
#+end_html

When we serve some soup, we give it to someone and we no longer have
it.  Each turn, we will choose from the four operations with equal
probability 0.25. If the remaining volume of soup is not enough to
complete the operation, we will serve as much as we can.  We stop once
we no longer have some quantity of both types of soup.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Note that we do not have the operation where all 100 ml's of soup B are
used first.  

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the probability that soup A will be empty first, plus half the
probability that A and B become empty at the same time.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Example:</strong>

  <strong>Input:</strong> N = 50

  <strong>Output:</strong> 0.625

  <strong>Explanation:</strong> 

  If we choose the first two operations, A will become empty first. For the third operation, A and B will become empty at the same time. For the fourth operation, B will become empty first. So the total probability of A becoming empty first plus half the probability that A and B become empty at the same time, is 0.25 * (1 + 1 + 0.5 + 0) = 0.625.



  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Notes:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= N <= 10^9. 

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Answers within 10^-6 of the true value will be accepted as correct.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
