* [[https://leetcode.com/problems/string-compression-ii][1531. String
Compression II]]
  :PROPERTIES:
  :CUSTOM_ID: string-compression-ii
  :END:
[[./solution/1500-1599/1531.String Compression II/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Run-length encoding is a string compression method that works
by replacing consecutive identical characters (repeated 2 or more times)
with the concatenation of the character and the number marking the count
of the characters (length of the run). For example, to compress the
string "aabccc" we replace "aa" by "a2" and replace "ccc" by "c3". Thus
the compressed string becomes "a2bc3".

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Notice that in this problem, we are not adding '1' after single
characters.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Given a string s and an integer k. You need to delete at most k
characters from s such that the run-length encoded version of s has
minimum length.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Find the minimum length of the run-length encoded version of s after
deleting at most k characters.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> s = &quot;aaabcccd&quot;, k = 2
  <strong>Output:</strong> 4
  <b>Explanation: </b>Compressing s without deleting anything will give us &quot;a3bc3d&quot; of length 6. Deleting any of the characters &#39;a&#39; or &#39;c&#39; would at most decrease the length of the compressed string to 5, for instance delete 2 &#39;a&#39; then we will have s = &quot;abcccd&quot; which compressed is abc3d. Therefore, the optimal way is to delete &#39;b&#39; and &#39;d&#39;, then the compressed version of s will be &quot;a3c3&quot; of length 4.</pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> s = &quot;aabbaa&quot;, k = 2
  <strong>Output:</strong> 2
  <b>Explanation: </b>If we delete both &#39;b&#39; characters, the resulting compressed string would be &quot;a4&quot; of length 2.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> s = &quot;aaaaaaaaaaa&quot;, k = 0
  <strong>Output:</strong> 3
  <strong>Explanation: </strong>Since k is zero, we cannot delete anything. The compressed string is &quot;a11&quot; of length 3.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= s.length <= 100

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= k <= s.length

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

s contains only lowercase English letters.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
