* [[https://leetcode.com/problems/guess-number-higher-or-lower-ii][375.
Guess Number Higher or Lower II]]
  :PROPERTIES:
  :CUSTOM_ID: guess-number-higher-or-lower-ii
  :END:
[[./solution/0300-0399/0375.Guess Number Higher or Lower II/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

We are playing the Guessing Game. The game will work as follows:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ol>
#+end_html

#+begin_html
  <li>
#+end_html

I pick a number between 1 and n.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

You guess a number.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

If you guess the right number, you win the game.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

If you guess the wrong number, then I will tell you whether the number I
picked is higher or lower, and you will continue guessing.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Every time you guess a wrong number x, you will pay x dollars. If you
run out of money, you lose the game.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ol>
#+end_html

#+begin_html
  <p>
#+end_html

Given a particular n, return the minimum amount of money you need
to guarantee a win regardless of what number I pick.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> n = 10
  <strong>Output:</strong> 16
  <strong>Explanation:</strong> The winning strategy is as follows:
  - The range is [1,10]. Guess 7.
  &nbsp;   - If this is my number, your total is $0. Otherwise, you pay $7.
  &nbsp;   - If my number is higher, the range is [8,10]. Guess 9.
  &nbsp;       - If this is my number, your total is $7. Otherwise, you pay $9.
  &nbsp;       - If my number is higher, it must be 10. Guess 10. Your total is $7 + $9 = $16.
  &nbsp;       - If my number is lower, it must be 8. Guess 8. Your total is $7 + $9 = $16.
  &nbsp;   - If my number is lower, the range is [1,6]. Guess 3.
  &nbsp;       - If this is my number, your total is $7. Otherwise, you pay $3.
  &nbsp;       - If my number is higher, the range is [4,6]. Guess 5.
  &nbsp;           - If this is my number, your total is $7 + $3 = $10. Otherwise, you pay $5.
  &nbsp;           - If my number is higher, it must be 6. Guess 6. Your total is $7 + $3 + $5 = $15.
  &nbsp;           - If my number is lower, it must be 4. Guess 4. Your total is $7 + $3 + $5 = $15.
  &nbsp;       - If my number is lower, the range is [1,2]. Guess 1.
  &nbsp;           - If this is my number, your total is $7 + $3 = $10. Otherwise, you pay $1.
  &nbsp;           - If my number is higher, it must be 2. Guess 2. Your total is $7 + $3 + $1 = $11.
  The worst case in all these scenarios is that you pay $16. Hence, you only need $16 to guarantee a win.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> n = 1
  <strong>Output:</strong> 0
  <strong>Explanation:</strong>&nbsp;There is only one possible number, so you can guess 1 and not have to pay anything.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> n = 2
  <strong>Output:</strong> 1
  <strong>Explanation:</strong>&nbsp;There are two possible numbers, 1 and 2.
  - Guess 1.
  &nbsp;   - If this is my number, your total is $0. Otherwise, you pay $1.
  &nbsp;   - If my number is higher, it must be 2. Guess 2. Your total is $1.
  The worst case is that you pay $1.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= n <= 200

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
