* [[https://leetcode.com/problems/optimal-division][553. Optimal
Division]]
  :PROPERTIES:
  :CUSTOM_ID: optimal-division
  :END:
[[./solution/0500-0599/0553.Optimal Division/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Given a list of positive integers, the adjacent integers will perform
the float division. For example, [2,3,4] -> 2 / 3 / 4.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

However, you can add any number of parenthesis at any position to change
the priority of operations. You should find out how to add parenthesis
to get the maximum result, and return the corresponding expression in
string format. Your expression should NOT contain redundant parenthesis.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example:

#+begin_html
  <pre>

  <b>Input:</b> [1000,100,10,2]

  <b>Output:</b> "1000/(100/10/2)"

  <b>Explanation:</b>

  1000/(100/10/2) = 1000/((100/10)/2) = 200

  However, the bold parenthesis in "1000/(<b>(</b>100/10<b>)</b>/2)" are redundant, <br/>since they don't influence the operation priority. So you should return "1000/(100/10/2)". 



  Other cases:

  1000/(100/10)/2 = 50

  1000/(100/(10/2)) = 50

  1000/100/10/2 = 0.5

  1000/100/(10/2) = 2

  </pre>
#+end_html

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Note:

#+begin_html
  <ol>
#+end_html

#+begin_html
  <li>
#+end_html

The length of the input array is [1, 10].

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Elements in the given array will be in range [2, 1000].

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

There is only one optimal division for each test case.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ol>
#+end_html

#+begin_html
  </p>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
