* [[https://leetcode.com/problems/count-number-of-homogenous-substrings][1759.
Count Number of Homogenous Substrings]]
  :PROPERTIES:
  :CUSTOM_ID: count-number-of-homogenous-substrings
  :END:
[[./solution/1700-1799/1759.Count Number of Homogenous Substrings/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Given a string s, return the number of homogenous substrings of s. Since
the answer may be too large, return it modulo 109 + 7.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

A string is homogenous if all the characters of the string are the same.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

A substring is a contiguous sequence of characters within a string.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> s = &quot;abbcccaa&quot;

  <strong>Output:</strong> 13

  <strong>Explanation:</strong> The homogenous substrings are listed as below:

  &quot;a&quot;   appears 3 times.

  &quot;aa&quot;  appears 1 time.

  &quot;b&quot;   appears 2 times.

  &quot;bb&quot;  appears 1 time.

  &quot;c&quot;   appears 3 times.

  &quot;cc&quot;  appears 2 times.

  &quot;ccc&quot; appears 1 time.

  3 + 1 + 2 + 1 + 3 + 2 + 1 = 13.</pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> s = &quot;xy&quot;

  <strong>Output:</strong> 2

  <strong>Explanation:</strong> The homogenous substrings are &quot;x&quot; and &quot;y&quot;.</pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> s = &quot;zzzzz&quot;

  <strong>Output:</strong> 15

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= s.length <= 105

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

s consists of lowercase letters.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
