* [[https://leetcode.com/problems/tallest-billboard][956. Tallest
Billboard]]
  :PROPERTIES:
  :CUSTOM_ID: tallest-billboard
  :END:
[[./solution/0900-0999/0956.Tallest Billboard/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

You are installing a billboard and want it to have the largest height.
The billboard will have two steel supports, one on each side. Each steel
support must be an equal height.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

You are given a collection of rods that can be welded together. For
example, if you have rods of lengths 1, 2, and 3, you can weld them
together to make a support of length 6.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the largest possible height of your billboard installation. If
you cannot support the billboard, return 0.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> rods = [1,2,3,6]
  <strong>Output:</strong> 6
  <strong>Explanation:</strong> We have two disjoint subsets {1,2,3} and {6}, which have the same sum = 6.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> rods = [1,2,3,4,5,6]
  <strong>Output:</strong> 10
  <strong>Explanation:</strong> We have two disjoint subsets {2,3,5} and {4,6}, which have the same sum = 10.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> rods = [1,2]
  <strong>Output:</strong> 0
  <strong>Explanation:</strong> The billboard cannot be supported, so we return 0.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= rods.length <= 20

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= rods[i] <= 1000

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

sum(rods[i]) <= 5000

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
