* [[https://leetcode.com/problems/dice-roll-simulation][1223. Dice Roll
Simulation]]
  :PROPERTIES:
  :CUSTOM_ID: dice-roll-simulation
  :END:
[[./solution/1200-1299/1223.Dice Roll Simulation/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

A die simulator generates a random number from 1 to 6 for each roll. You
introduced a constraint to the generator such that it cannot roll the
number i more than rollMax[i] (1-indexed) consecutive times. 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Given an array of integers rollMax and an integer n, return the number
of distinct sequences that can be obtained with exact n rolls.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Two sequences are considered different if at least one element differs
from each other. Since the answer may be too large, return it modulo
10^9 + 7.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> n = 2, rollMax = [1,1,2,2,2,3]
  <strong>Output:</strong> 34
  <strong>Explanation:</strong> There will be 2 rolls of die, if there are no constraints on the die, there are 6 * 6 = 36 possible combinations. In this case, looking at rollMax array, the numbers 1 and 2 appear at most once consecutively, therefore sequences (1,1) and (2,2) cannot occur, so the final answer is 36-2 = 34.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> n = 2, rollMax = [1,1,1,1,1,1]
  <strong>Output:</strong> 30
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> n = 3, rollMax = [1,1,1,2,2,3]
  <strong>Output:</strong> 181
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= n <= 5000

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

rollMax.length == 6

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= rollMax[i] <= 15

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
