* [[https://leetcode.com/problems/maximum-points-you-can-obtain-from-cards][1423.
Maximum Points You Can Obtain from Cards]]
  :PROPERTIES:
  :CUSTOM_ID: maximum-points-you-can-obtain-from-cards
  :END:
[[./solution/1400-1499/1423.Maximum Points You Can Obtain from Cards/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

There are several cards arranged in a row, and each card has an
associated number of points The points are given in the integer
array cardPoints.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

In one step, you can take one card from the beginning or from the end of
the row. You have to take exactly k cards.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Your score is the sum of the points of the cards you have taken.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Given the integer array cardPoints and the integer k, return the maximum
score you can obtain.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> cardPoints = [1,2,3,4,5,6,1], k = 3
  <strong>Output:</strong> 12
  <strong>Explanation:</strong> After the first step, your score will always be 1. However, choosing the rightmost card first will maximize your total score. The optimal strategy is to take the three cards on the right, giving a final score of 1 + 6 + 5 = 12.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> cardPoints = [2,2,2], k = 2
  <strong>Output:</strong> 4
  <strong>Explanation:</strong> Regardless of which two cards you take, your score will always be 4.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> cardPoints = [9,7,7,9,7,7,9], k = 7
  <strong>Output:</strong> 55
  <strong>Explanation:</strong> You have to take all the cards. Your score is the sum of points of all cards.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 4:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> cardPoints = [1,1000,1], k = 1
  <strong>Output:</strong> 1
  <strong>Explanation:</strong> You cannot take the card in the middle. Your best score is 1. 
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 5:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> cardPoints = [1,79,80,1,1,1,200,1], k = 3
  <strong>Output:</strong> 202
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= cardPoints.length <= 10^5

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= cardPoints[i] <= 10^4

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= k <= cardPoints.length

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
