* [[https://leetcode.com/problems/count-all-possible-routes][1575. Count
All Possible Routes]]
  :PROPERTIES:
  :CUSTOM_ID: count-all-possible-routes
  :END:
[[./solution/1500-1599/1575.Count All Possible Routes/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

You are given an array of distinct positive integers locations where
locations[i] represents the position of city i. You are also
given integers start, finish and fuel representing the starting city,
ending city, and the initial amount of fuel you have, respectively.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

At each step, if you are at city i, you can pick any city j such that j
!= i and 0 <= j < locations.length and move to city j. Moving from city
i to city j reduces the amount of fuel you have by |locations[i] -
locations[j]|. Please notice that |x| denotes the absolute value of x.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Notice that fuel cannot become negative at any point in time, and that
you are allowed to visit any city more than once (including
start and finish).

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the count of all possible routes from start to finish.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Since the answer may be too large, return it modulo 10^9 + 7.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> locations = [2,3,6,8,4], start = 1, finish = 3, fuel = 5
  <strong>Output:</strong> 4
  <strong>Explanation:</strong>&nbsp;The following are all possible routes, each uses 5 units of fuel:
  1 -&gt; 3
  1 -&gt; 2 -&gt; 3
  1 -&gt; 4 -&gt; 3
  1 -&gt; 4 -&gt; 2 -&gt; 3
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> locations = [4,3,1], start = 1, finish = 0, fuel = 6
  <strong>Output:</strong> 5
  <strong>Explanation: </strong>The following are all possible routes:
  1 -&gt; 0, used fuel = 1
  1 -&gt; 2 -&gt; 0, used fuel = 5
  1 -&gt; 2 -&gt; 1 -&gt; 0, used fuel = 5
  1 -&gt; 0 -&gt; 1 -&gt; 0, used fuel = 3
  1 -&gt; 0 -&gt; 1 -&gt; 0 -&gt; 1 -&gt; 0, used fuel = 5
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> locations = [5,2,1], start = 0, finish = 2, fuel = 3
  <strong>Output:</strong> 0
  <b>Explanation: </b>It&#39;s impossible to get from 0 to 2 using only 3 units of fuel since the shortest route needs 4 units of fuel.</pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 4:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> locations = [2,1,5], start = 0, finish = 0, fuel = 3
  <strong>Output:</strong> 2
  <strong>Explanation:</strong>&nbsp;There are two possible routes, 0 and 0 -&gt; 1 -&gt; 0.</pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 5:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> locations = [1,2,3], start = 0, finish = 2, fuel = 40
  <strong>Output:</strong> 615088286
  <strong>Explanation: </strong>The total number of possible routes is 2615088300. Taking this number modulo 10^9 + 7 gives us 615088286.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

2 <= locations.length <= 100

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= locations[i] <= 10^9

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

All integers in locations are distinct.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= start, finish < locations.length

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= fuel <= 200

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
