* [[https://leetcode.com/problems/minimum-ascii-delete-sum-for-two-strings][712.
Minimum ASCII Delete Sum for Two Strings]]
  :PROPERTIES:
  :CUSTOM_ID: minimum-ascii-delete-sum-for-two-strings
  :END:
[[./solution/0700-0799/0712.Minimum ASCII Delete Sum for Two Strings/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Given two strings s1, s2, find the lowest ASCII sum of deleted
characters to make two strings equal.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  <pre>

  <b>Input:</b> s1 = "sea", s2 = "eat"

  <b>Output:</b> 231

  <b>Explanation:</b> Deleting "s" from "sea" adds the ASCII value of "s" (115) to the sum.

  Deleting "t" from "eat" adds 116 to the sum.

  At the end, both strings are equal, and 115 + 116 = 231 is the minimum sum possible to achieve this.

  </pre>
#+end_html

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  <pre>

  <b>Input:</b> s1 = "delete", s2 = "leet"

  <b>Output:</b> 403

  <b>Explanation:</b> Deleting "dee" from "delete" to turn the string into "let",

  adds 100[d]+101[e]+101[e] to the sum.  Deleting "e" from "leet" adds 101[e] to the sum.

  At the end, both strings are equal to "let", and the answer is 100+101+101+101 = 403.

  If instead we turned both strings into "lee" or "eet", we would get answers of 433 or 417, which are higher.

  </pre>
#+end_html

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Note:

#+begin_html
  <li>
#+end_html

0 < s1.length, s2.length <= 1000.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

All elements of each string will have an ASCII value in [97, 122].

#+begin_html
  </li>
#+end_html

#+begin_html
  </p>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
