* [[https://leetcode.com/problems/the-skyline-problem][218. The Skyline
Problem]]
  :PROPERTIES:
  :CUSTOM_ID: the-skyline-problem
  :END:
[[./solution/0200-0299/0218.The Skyline Problem/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

A city's skyline is the outer contour of the silhouette formed by all
the buildings in that city when viewed from a distance. Given the
locations and heights of all the buildings, return the skyline formed by
these buildings collectively.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

The geometric information of each building is given in the array
buildings where buildings[i] = [lefti, righti, heighti]:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

lefti is the x coordinate of the left edge of the ith building.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

righti is the x coordinate of the right edge of the ith building.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

heighti is the height of the ith building.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

#+begin_html
  <p>
#+end_html

You may assume all buildings are perfect rectangles grounded on an
absolutely flat surface at height 0.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

The skyline should be represented as a list of "key points" sorted by
their x-coordinate in the form [[x1,y1],[x2,y2],...]. Each key point is
the left endpoint of some horizontal segment in the skyline except the
last point in the list, which always has a y-coordinate 0 and is used to
mark the skyline's termination where the rightmost building ends. Any
ground between the leftmost and rightmost buildings should be part of
the skyline's contour.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Note: There must be no consecutive horizontal lines of equal height in
the output skyline. For instance, [...,[2 3],[4 5],[7 5],[11 5],[12
7],...] is not acceptable; the three lines of height 5 should be merged
into one in the final output as such: [...,[2 3],[4 5],[12 7],...]

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> buildings = [[2,9,10],[3,7,15],[5,12,12],[15,20,10],[19,24,8]]
  <strong>Output:</strong> [[2,10],[3,15],[7,12],[12,0],[15,10],[20,8],[24,0]]
  <strong>Explanation:</strong>
  Figure A shows the buildings of the input.
  Figure B shows the skyline formed by those buildings. The red points in figure B represent the key points in the output list.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> buildings = [[0,2,3],[2,5,3]]
  <strong>Output:</strong> [[0,3],[5,0]]
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= buildings.length <= 104

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= lefti < righti <= 231 - 1

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= heighti <= 231 - 1

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

buildings is sorted by lefti in non-decreasing order.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
