* [[https://leetcode.com/problems/construct-binary-tree-from-inorder-and-postorder-traversal][106.
Construct Binary Tree from Inorder and Postorder Traversal]]
  :PROPERTIES:
  :CUSTOM_ID: construct-binary-tree-from-inorder-and-postorder-traversal
  :END:
[[./solution/0100-0199/0106.Construct Binary Tree from Inorder and Postorder Traversal/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Given two integer arrays inorder and postorder where inorder is the
inorder traversal of a binary tree and postorder is the postorder
traversal of the same tree, construct and return the binary tree.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> inorder = [9,3,15,20,7], postorder = [9,15,7,20,3]
  <strong>Output:</strong> [3,9,20,null,null,15,7]
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> inorder = [-1], postorder = [-1]
  <strong>Output:</strong> [-1]
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= inorder.length <= 3000

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

postorder.length == inorder.length

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

-3000 <= inorder[i], postorder[i] <= 3000

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

inorder and postorder consist of unique values.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Each value of postorder also appears in inorder.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

inorder is guaranteed to be the inorder traversal of the tree.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

postorder is guaranteed to be the postorder traversal of the tree.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
  # Definition for a binary tree node.
  # class TreeNode:
  #     def __init__(self, x):
  #         self.val = x
  #         self.left = None
  #         self.right = None

  class Solution:
      indexes = {}
      def buildTree(self, inorder: List[int], postorder: List[int]) -> TreeNode:
          def build(inorder, postorder, i1, i2, p1, p2):
              if i1 > i2 or p1 > p2:
                  return None
              root_val = postorder[p2]
              pos = self.indexes[root_val]
              root = TreeNode(root_val)
              root.left = None if pos == i1 else build(inorder, postorder, i1, pos - 1, p1, p1 - i1 + pos - 1)
              root.right = None if pos == i2 else build(inorder, postorder, pos + 1, i2, p1 - i1 + pos, p2 - 1)
              return root
          n = len(inorder)
          for i in range(n):
              self.indexes[inorder[i]] = i
          return build(inorder, postorder, 0, n - 1, 0, n - 1)
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
  /**
   * Definition for a binary tree node.
   * public class TreeNode {
   *     int val;
   *     TreeNode left;
   *     TreeNode right;
   *     TreeNode(int x) { val = x; }
   * }
   */
  class Solution {
      private Map<Integer, Integer> indexes = new HashMap<>();

      public TreeNode buildTree(int[] inorder, int[] postorder) {
          int n = inorder.length;
          for (int i = 0; i < n; ++i) {
              indexes.put(inorder[i], i);
          }
          return build(inorder, postorder, 0, inorder.length - 1, 0, postorder.length - 1);
      }

      private TreeNode build(int[] inorder, int[] postorder, int i1, int i2, int p1, int p2) {
          if (i1 > i2 || p1 > p2) return null;
          int rootVal = postorder[p2];
          int pos = indexes.get(rootVal);
          TreeNode root = new TreeNode(rootVal);
          root.left = pos == i1 ? null : build(inorder, postorder, i1, pos - 1, p1, p1 - i1 + pos - 1);
          root.right = pos == i2 ? null : build(inorder, postorder, pos + 1, i2, p1 - i1 + pos, p2 - 1);
          return root;
      }
  }
#+end_src

*** *C++*
    :PROPERTIES:
    :CUSTOM_ID: c
    :END:
#+begin_src cpp
  class Solution {
  public:
      TreeNode *buildTree(vector<int> &inorder, vector<int> &postorder) {
          return buildTree(inorder, 0, inorder.size() - 1, postorder, 0, postorder.size() - 1);
      }
      TreeNode *buildTree(vector<int> &inorder, int iLeft, int iRight, vector<int> &postorder, int pLeft, int pRight) {
          if (iLeft > iRight || pLeft > pRight) return NULL;
          TreeNode *cur = new TreeNode(postorder[pRight]);
          int i = 0;
          for (i = iLeft; i < inorder.size(); ++i) {
              if (inorder[i] == cur->val)
                  break;
          }
          cur->left = buildTree(inorder, iLeft, i - 1, postorder, pLeft, pLeft + i - iLeft - 1);
          cur->right = buildTree(inorder, i + 1, iRight, postorder, pLeft + i - iLeft, pRight - 1);
          return cur;
      }
  };
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
