* [[https://leetcode.com/problems/can-you-eat-your-favorite-candy-on-your-favorite-day][1744.
Can You Eat Your Favorite Candy on Your Favorite Day]]
  :PROPERTIES:
  :CUSTOM_ID: can-you-eat-your-favorite-candy-on-your-favorite-day
  :END:
[[./solution/1700-1799/1744.Can You Eat Your Favorite Candy on Your Favorite Day/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

You are given a (0-indexed) array of positive integers candiesCount
where candiesCount[i] represents the number of candies of the ith type
you have. You are also given a 2D array queries where queries[i] =
[favoriteTypei, favoriteDayi, dailyCapi].

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

You play a game with the following rules:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

You start eating candies on day 0.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

You cannot eat any candy of type i unless you have eaten all candies of
type i - 1.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

You must eat at least one candy per day until you have eaten all the
candies.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

#+begin_html
  <p>
#+end_html

Construct a boolean array answer such that answer.length ==
queries.length and answer[i] is true if you can eat a candy of type
favoriteTypei on day favoriteDayi without eating more than dailyCapi
candies on any day, and false otherwise. Note that you can eat different
types of candy on the same day, provided that you follow rule 2.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the constructed array answer.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> candiesCount = [7,4,5,3,8], queries = [[0,2,2],[4,2,4],[2,13,1000000000]]
  <strong>Output:</strong> [true,false,true]
  <strong>Explanation:</strong>
  1- If you eat 2 candies (type 0) on day 0 and 2 candies (type 0) on day 1, you will eat a candy of type 0 on day 2.
  2- You can eat at most 4 candies each day.
     If you eat 4 candies every day, you will eat 4 candies (type 0) on day 0 and 4 candies (type 0 and type 1) on day 1.
     On day 2, you can only eat 4 candies (type 1 and type 2), so you cannot eat a candy of type 4 on day 2.
  3- If you eat 1 candy each day, you will eat a candy of type 2 on day 13.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> candiesCount = [5,2,6,4,1], queries = [[3,1,2],[4,10,3],[3,10,100],[4,100,30],[1,3,1]]
  <strong>Output:</strong> [false,true,true,false,false]
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= candiesCount.length <= 105

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= candiesCount[i] <= 105

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= queries.length <= 105

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

queries[i].length == 3

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= favoriteTypei < candiesCount.length

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= favoriteDayi <= 109

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= dailyCapi <= 109

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
