* [[https://leetcode.com/problems/count-pairs-of-equal-substrings-with-minimum-difference][1794.
Count Pairs of Equal Substrings With Minimum Difference]]
  :PROPERTIES:
  :CUSTOM_ID: count-pairs-of-equal-substrings-with-minimum-difference
  :END:
[[./solution/1700-1799/1794.Count Pairs of Equal Substrings With Minimum Difference/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

You are given two strings firstString and secondString that are
0-indexed and consist only of lowercase English letters. Count the
number of index quadruples (i,j,a,b) that satisfy the following
conditions:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= i <= j < firstString.length

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= a <= b < secondString.length

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

The substring of firstString that starts at the ith character and ends
at the jth character (inclusive) is equal to the substring of
secondString that starts at the ath character and ends at the bth
character (inclusive).

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

j - a is the minimum possible value among all quadruples that satisfy
the previous conditions.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

#+begin_html
  <p>
#+end_html

Return the number of such quadruples.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> firstString = &quot;abcd&quot;, secondString = &quot;bccda&quot;

  <strong>Output:</strong> 1

  <strong>Explanation:</strong> The quadruple (0,0,4,4) is the only one that satisfies all the conditions and minimizes j - a.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> firstString = &quot;ab&quot;, secondString = &quot;cd&quot;

  <strong>Output:</strong> 0

  <strong>Explanation:</strong> There are no quadruples satisfying all the conditions.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= firstString.length, secondString.length <= 2 * 105

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Both strings consist only of lowercase English letters.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
