* [[https://leetcode.com/problems/distribute-candies][575. Distribute
Candies]]
  :PROPERTIES:
  :CUSTOM_ID: distribute-candies
  :END:
[[./solution/0500-0599/0575.Distribute Candies/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Alice has n candies, where the ith candy is of type candyType[i]. Alice
noticed that she started to gain weight, so she visited a doctor.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

The doctor advised Alice to only eat n / 2 of the candies she has (n is
always even). Alice likes her candies very much, and she wants to eat
the maximum number of different types of candies while still following
the doctor's advice.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Given the integer array candyType of length n, return the maximum number
of different types of candies she can eat if she only eats n / 2 of
them.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> candyType = [1,1,2,2,3,3]
  <strong>Output:</strong> 3
  <strong>Explanation:</strong> Alice can only eat 6 / 2 = 3 candies. Since there are only 3 types, she can eat one of each type.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> candyType = [1,1,2,3]
  <strong>Output:</strong> 2
  <strong>Explanation:</strong> Alice can only eat 4 / 2 = 2 candies. Whether she eats types [1,2], [1,3], or [2,3], she still can only eat 2 different types.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> candyType = [6,6,6,6]
  <strong>Output:</strong> 1
  <strong>Explanation:</strong> Alice can only eat 4 / 2 = 2 candies. Even though she can eat 2 candies, she only has 1 type.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

n == candyType.length

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

2 <= n <= 104

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

n is even.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

-105 <= candyType[i] <= 105

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
