* [[https://leetcode.com/problems/sentence-similarity-ii][737. Sentence
Similarity II]]
  :PROPERTIES:
  :CUSTOM_ID: sentence-similarity-ii
  :END:
[[./solution/0700-0799/0737.Sentence Similarity II/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Given two sentences words1, words2 (each represented as an array of
strings), and a list of similar word pairs pairs, determine if two
sentences are similar.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

For example, words1 = ["great", "acting", "skills"] and words2 =
["fine", "drama", "talent"] are similar, if the similar word pairs are
pairs = [["great", "good"], ["fine", "good"], ["acting","drama"],
["skills","talent"]].

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Note that the similarity relation is transitive. For example, if "great"
and "good" are similar, and "fine" and "good" are similar, then "great"
and "fine" are similar.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Similarity is also symmetric. For example, "great" and "fine" being
similar is the same as "fine" and "great" being similar.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Also, a word is always similar with itself. For example, the sentences
words1 = ["great"], words2 = ["great"], pairs = [] are similar, even
though there are no specified similar word pairs.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Finally, sentences can only be similar if they have the same number of
words. So a sentence like words1 = ["great"] can never be similar to
words2 = ["doubleplus","good"].

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Note:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

The length of words1 and words2 will not exceed 1000.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

The length of pairs will not exceed 2000.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

The length of each pairs[i] will be 2.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

The length of each words[i] and pairs[i][j] will be in the range [1,
20].

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
