* [[https://leetcode.com/problems/minimum-number-of-frogs-croaking][1419.
Minimum Number of Frogs Croaking]]
  :PROPERTIES:
  :CUSTOM_ID: minimum-number-of-frogs-croaking
  :END:
[[./solution/1400-1499/1419.Minimum Number of Frogs Croaking/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Given the string croakOfFrogs, which represents a combination of the
string "croak" from different frogs, that is, multiple frogs can croak
at the same time, so multiple “croak” are mixed. Return the minimum
number of different frogs to finish all the croak in the given string.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

A valid "croak" means a frog is printing 5 letters ‘c', 'r', 'o', 'a',
'k' sequentially. The frogs have to print all five letters to finish a
croak. If the given string is not a combination of valid "croak" return
-1.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> croakOfFrogs = &quot;croakcroak&quot;
  <strong>Output:</strong> 1 
  <strong>Explanation:</strong> One frog yelling &quot;croak<strong>&quot;</strong> twice.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> croakOfFrogs = &quot;crcoakroak&quot;
  <strong>Output:</strong> 2 
  <strong>Explanation:</strong> The minimum number of frogs is two.&nbsp;
  The first frog could yell &quot;<strong>cr</strong>c<strong>oak</strong>roak&quot;.
  The second frog could yell later &quot;cr<strong>c</strong>oak<strong>roak</strong>&quot;.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> croakOfFrogs = &quot;croakcrook&quot;
  <strong>Output:</strong> -1
  <strong>Explanation:</strong> The given string is an invalid combination of &quot;croak<strong>&quot;</strong> from different frogs.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 4:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> croakOfFrogs = &quot;croakcroa&quot;
  <strong>Output:</strong> -1
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= croakOfFrogs.length <= 10^5

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

All characters in the string are: 'c', 'r', 'o', 'a' or 'k'.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
