* [[https://leetcode.com/problems/course-schedule-ii][210. Course
Schedule II]]
  :PROPERTIES:
  :CUSTOM_ID: course-schedule-ii
  :END:
[[./solution/0200-0299/0210.Course Schedule II/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

There are a total of n courses you have to take labelled from 0 to n -
1.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Some courses may have prerequisites, for example, if prerequisites[i] =
[ai, bi] this means you must take the course bi before the course ai.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Given the total number of courses numCourses and a list of the
prerequisite pairs, return the ordering of courses you should take to
finish all courses.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

If there are many valid answers, return any of them. If it is impossible
to finish all courses, return an empty array.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> numCourses = 2, prerequisites = [[1,0]]
  <strong>Output:</strong> [0,1]
  <strong>Explanation:</strong> There are a total of 2 courses to take. To take course 1 you should have finished course 0. So the correct course order is [0,1].
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> numCourses = 4, prerequisites = [[1,0],[2,0],[3,1],[3,2]]
  <strong>Output:</strong> [0,2,1,3]
  <strong>Explanation:</strong> There are a total of 4 courses to take. To take course 3 you should have finished both courses 1 and 2. Both courses 1 and 2 should be taken after you finished course 0.
  So one correct course order is [0,1,2,3]. Another correct ordering is [0,2,1,3].
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> numCourses = 1, prerequisites = []
  <strong>Output:</strong> [0]
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= numCourses <= 2000

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= prerequisites.length <= numCourses * (numCourses - 1)

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

prerequisites[i].length == 2

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= ai, bi < numCourses

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

ai != bi

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

All the pairs [ai, bi] are distinct.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
