* [[https://leetcode.com/problems/equal-sum-arrays-with-minimum-number-of-operations][1775.
Equal Sum Arrays With Minimum Number of Operations]]
  :PROPERTIES:
  :CUSTOM_ID: equal-sum-arrays-with-minimum-number-of-operations
  :END:
[[./solution/1700-1799/1775.Equal Sum Arrays With Minimum Number of Operations/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

You are given two arrays of integers nums1 and nums2, possibly of
different lengths. The values in the arrays are between 1 and 6,
inclusive.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

In one operation, you can change any integer's value in any of the
arrays to any value between 1 and 6, inclusive.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the minimum number of operations required to make the sum of
values in nums1 equal to the sum of values in nums2. Return -1​​​​​ if
it is not possible to make the sum of the two arrays equal.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> nums1 = [1,2,3,4,5,6], nums2 = [1,1,2,2,2,2]
  <strong>Output:</strong> 3
  <strong>Explanation:</strong> You can make the sums of nums1 and nums2 equal with 3 operations. All indices are 0-indexed.
  - Change nums2[0] to 6. nums1 = [1,2,3,4,5,6], nums2 = [<u><strong>6</strong></u>,1,2,2,2,2].
  - Change nums1[5] to 1. nums1 = [1,2,3,4,5,<strong><u>1</u></strong>], nums2 = [6,1,2,2,2,2].
  - Change nums1[2] to 2. nums1 = [1,2,<strong><u>2</u></strong>,4,5,1], nums2 = [6,1,2,2,2,2].
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> nums1 = [1,1,1,1,1,1,1], nums2 = [6]
  <strong>Output:</strong> -1
  <strong>Explanation:</strong> There is no way to decrease the sum of nums1 or to increase the sum of nums2 to make them equal.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> nums1 = [6,6], nums2 = [1]
  <strong>Output:</strong> 3
  <strong>Explanation:</strong> You can make the sums of nums1 and nums2 equal with 3 operations. All indices are 0-indexed. 
  - Change nums1[0] to 2. nums1 = [<strong><u>2</u></strong>,6], nums2 = [1].
  - Change nums1[1] to 2. nums1 = [2,<strong><u>2</u></strong>], nums2 = [1].
  - Change nums2[0] to 4. nums1 = [2,2], nums2 = [<strong><u>4</u></strong>].
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= nums1.length, nums2.length <= 105

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= nums1[i], nums2[i] <= 6

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
