* [[https://leetcode.com/problems/minimum-score-triangulation-of-polygon][1039.
Minimum Score Triangulation of Polygon]]
  :PROPERTIES:
  :CUSTOM_ID: minimum-score-triangulation-of-polygon
  :END:
[[./solution/1000-1099/1039.Minimum Score Triangulation of Polygon/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

You have a convex n-sided polygon where each vertex has an integer
value. You are given an integer array values where values[i] is the
value of the ith vertex (i.e., clockwise order).

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

You will triangulate the polygon into n - 2 triangles. For each
triangle, the value of that triangle is the product of the values of its
vertices, and the total score of the triangulation is the sum of these
values over all n - 2 triangles in the triangulation.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the smallest possible total score that you can achieve with some
triangulation of the polygon.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> values = [1,2,3]
  <strong>Output:</strong> 6
  <strong>Explanation:</strong> The polygon is already triangulated, and the score of the only triangle is 6.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> values = [3,7,4,5]
  <strong>Output:</strong> 144
  <strong>Explanation:</strong> There are two triangulations, with possible scores: 3*7*5 + 4*5*7 = 245, or 3*4*5 + 3*4*7 = 144.
  The minimum score is 144.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> values = [1,3,1,4,1,5]
  <strong>Output:</strong> 13
  <strong>Explanation:</strong> The minimum score triangulation has score 1*1*3 + 1*1*4 + 1*1*5 + 1*1*1 = 13.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

n == values.length

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

3 <= n <= 50

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= values[i] <= 100

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
