* [[https://leetcode.com/problems/stone-game-v][1563. Stone Game V]]
  :PROPERTIES:
  :CUSTOM_ID: stone-game-v
  :END:
[[./solution/1500-1599/1563.Stone Game V/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

There are several stones arranged in a row, and each stone has an
associated value which is an integer given in the array stoneValue.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

In each round of the game, Alice divides the row into two non-empty rows
(i.e. left row and right row), then Bob calculates the value of each row
which is the sum of the values of all the stones in this row. Bob throws
away the row which has the maximum value, and Alice's score increases by
the value of the remaining row. If the value of the two rows are equal,
Bob lets Alice decide which row will be thrown away. The next round
starts with the remaining row.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

The game ends when there is only one stone remaining. Alice's is
initially zero.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the maximum score that Alice can obtain.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> stoneValue = [6,2,3,4,5,5]
  <strong>Output:</strong> 18
  <strong>Explanation:</strong> In the first round, Alice divides the row to [6,2,3], [4,5,5]. The left row has the value 11 and the right row has value 14. Bob throws away the right row and Alice&#39;s score is now 11.
  In the second round Alice divides the row to [6], [2,3]. This time Bob throws away the left row and Alice&#39;s score becomes 16 (11 + 5).
  The last round Alice has only one choice to divide the row which is [2], [3]. Bob throws away the right row and Alice&#39;s score is now 18 (16 + 2). The game ends because only one stone is remaining in the row.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> stoneValue = [7,7,7,7,7,7,7]
  <strong>Output:</strong> 28
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> stoneValue = [4]
  <strong>Output:</strong> 0
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= stoneValue.length <= 500

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= stoneValue[i] <= 10^6

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
