* [[https://leetcode.com/problems/reformat-the-string][1417. Reformat
The String]]
  :PROPERTIES:
  :CUSTOM_ID: reformat-the-string
  :END:
[[./solution/1400-1499/1417.Reformat The String/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Given alphanumeric string s. (Alphanumeric string is a string consisting
of lowercase English letters and digits).

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

You have to find a permutation of the string where no letter is followed
by another letter and no digit is followed by another digit. That is, no
two adjacent characters have the same type.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the reformatted string or return an empty string if it is
impossible to reformat the string.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> s = &quot;a0b1c2&quot;
  <strong>Output:</strong> &quot;0a1b2c&quot;
  <strong>Explanation:</strong> No two adjacent characters have the same type in &quot;0a1b2c&quot;. &quot;a0b1c2&quot;, &quot;0a1b2c&quot;, &quot;0c2a1b&quot; are also valid permutations.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> s = &quot;leetcode&quot;
  <strong>Output:</strong> &quot;&quot;
  <strong>Explanation:</strong> &quot;leetcode&quot; has only characters so we cannot separate them by digits.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> s = &quot;1229857369&quot;
  <strong>Output:</strong> &quot;&quot;
  <strong>Explanation:</strong> &quot;1229857369&quot; has only digits so we cannot separate them by characters.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 4:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> s = &quot;covid2019&quot;
  <strong>Output:</strong> &quot;c2o0v1i9d&quot;
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 5:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> s = &quot;ab123&quot;
  <strong>Output:</strong> &quot;1a2b3&quot;
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= s.length <= 500

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

s consists of only lowercase English letters and/or digits.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
