* [[https://leetcode.com/problems/design-file-system][1166. Design File
System]]
  :PROPERTIES:
  :CUSTOM_ID: design-file-system
  :END:
[[./solution/1100-1199/1166.Design File System/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

You are asked to design a file system that allows you to create new
paths and associate them with different values.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

The format of a path is one or more concatenated strings of the form: /
followed by one or more lowercase English letters. For example,
"/leetcode" and "/leetcode/problems" are valid paths while an
empty string "" and "/" are not.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Implement the FileSystem class:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

bool createPath(string path, int value) Creates a new path and
associates a value to it if possible and returns true. Returns false if
the path already exists or its parent path doesn't exist.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

int get(string path) Returns the value associated with path or
returns -1 if the path doesn't exist.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> 
  [&quot;FileSystem&quot;,&quot;createPath&quot;,&quot;get&quot;]
  [[],[&quot;/a&quot;,1],[&quot;/a&quot;]]
  <strong>Output:</strong> 
  [null,true,1]
  <strong>Explanation:</strong> 
  FileSystem fileSystem = new FileSystem();

  fileSystem.createPath(&quot;/a&quot;, 1); // return true
  fileSystem.get(&quot;/a&quot;); // return 1
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> 
  [&quot;FileSystem&quot;,&quot;createPath&quot;,&quot;createPath&quot;,&quot;get&quot;,&quot;createPath&quot;,&quot;get&quot;]
  [[],[&quot;/leet&quot;,1],[&quot;/leet/code&quot;,2],[&quot;/leet/code&quot;],[&quot;/c/d&quot;,1],[&quot;/c&quot;]]
  <strong>Output:</strong> 
  [null,true,true,2,false,-1]
  <strong>Explanation:</strong> 
  FileSystem fileSystem = new FileSystem();

  fileSystem.createPath(&quot;/leet&quot;, 1); // return true
  fileSystem.createPath(&quot;/leet/code&quot;, 2); // return true
  fileSystem.get(&quot;/leet/code&quot;); // return 2
  fileSystem.createPath(&quot;/c/d&quot;, 1); // return false because the parent path &quot;/c&quot; doesn&#39;t exist.
  fileSystem.get(&quot;/c&quot;); // return -1 because this path doesn&#39;t exist.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

The number of calls to the two functions is less than or equal to 104 in
total.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

2 <= path.length <= 100

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= value <= 109

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
