* [[https://leetcode.com/problems/binary-tree-cameras][968. Binary Tree
Cameras]]
  :PROPERTIES:
  :CUSTOM_ID: binary-tree-cameras
  :END:
[[./solution/0900-0999/0968.Binary Tree Cameras/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Given a binary tree, we install cameras on the nodes of the tree. 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Each camera at a node can monitor its parent, itself, and its immediate
children.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Calculate the minimum number of cameras needed to monitor all nodes of
the tree.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input: </strong><span id="example-input-1-1">[0,0,null,0,0]</span>

  <strong>Output: </strong><span id="example-output-1">1</span>

  <strong>Explanation: </strong>One camera is enough to monitor all nodes if placed as shown.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input: </strong><span id="example-input-2-1">[0,0,null,0,null,0,null,null,0]</span>

  <strong>Output: </strong><span id="example-output-2">2

  <strong>Explanation:</strong> At least two cameras are needed to monitor all nodes of the tree. The above image shows one of the valid configurations of camera placement.</span>

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Note:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ol>
#+end_html

#+begin_html
  <li>
#+end_html

The number of nodes in the given tree will be in the range [1, 1000].

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Every node has value 0.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ol>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
