* [[https://leetcode.com/problems/number-of-dice-rolls-with-target-sum][1155.
Number of Dice Rolls With Target Sum]]
  :PROPERTIES:
  :CUSTOM_ID: number-of-dice-rolls-with-target-sum
  :END:
[[./solution/1100-1199/1155.Number of Dice Rolls With Target Sum/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

You have d dice and each die has f faces numbered 1, 2, ..., f.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the number of possible ways (out of fd total ways) modulo 109 + 7
to roll the dice so the sum of the face-up numbers equals target.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> d = 1, f = 6, target = 3
  <strong>Output:</strong> 1
  <strong>Explanation: </strong>
  You throw one die with 6 faces.  There is only one way to get a sum of 3.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> d = 2, f = 6, target = 7
  <strong>Output:</strong> 6
  <strong>Explanation: </strong>
  You throw two dice, each with 6 faces.  There are 6 ways to get a sum of 7:
  1+6, 2+5, 3+4, 4+3, 5+2, 6+1.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> d = 2, f = 5, target = 10
  <strong>Output:</strong> 1
  <strong>Explanation: </strong>
  You throw two dice, each with 5 faces.  There is only one way to get a sum of 10: 5+5.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 4:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> d = 1, f = 2, target = 3
  <strong>Output:</strong> 0
  <strong>Explanation: </strong>
  You throw one die with 2 faces.  There is no way to get a sum of 3.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 5:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> d = 30, f = 30, target = 500
  <strong>Output:</strong> 222616187
  <strong>Explanation: </strong>
  The answer must be returned modulo 10^9 + 7.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= d, f <= 30

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= target <= 1000

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
