* [[https://leetcode.com/problems/add-two-numbers][2. Add Two Numbers]]
  :PROPERTIES:
  :CUSTOM_ID: add-two-numbers
  :END:
[[./solution/0000-0099/0002.Add Two Numbers/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

You are given two non-empty linked lists representing two non-negative
integers. The digits are stored in reverse order, and each of their
nodes contains a single digit. Add the two numbers and return the sum as
a linked list.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

You may assume the two numbers do not contain any leading zero, except
the number 0 itself.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> l1 = [2,4,3], l2 = [5,6,4]
  <strong>Output:</strong> [7,0,8]
  <strong>Explanation:</strong> 342 + 465 = 807.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> l1 = [0], l2 = [0]
  <strong>Output:</strong> [0]
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> l1 = [9,9,9,9,9,9,9], l2 = [9,9,9,9]
  <strong>Output:</strong> [8,9,9,9,0,0,0,1]
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

The number of nodes in each linked list is in the range [1, 100].

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= Node.val <= 9

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

It is guaranteed that the list represents a number that does not have
leading zeros.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
  # Definition for singly-linked list.
  # class ListNode:
  #     def __init__(self, val=0, next=None):
  #         self.val = val
  #         self.next = next
  class Solution:
      def addTwoNumbers(self, l1: ListNode, l2: ListNode) -> ListNode:
          dummy = ListNode()
          carry, cur = 0, dummy
          while l1 or l2 or carry:
              s = (0 if not l1 else l1.val) + (0 if not l2 else l2.val) + carry
              carry, val = divmod(s, 10)
              cur.next = ListNode(val)
              cur = cur.next
              l1 = None if not l1 else l1.next
              l2 = None if not l2 else l2.next
          return dummy.next
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
  /**
   * Definition for singly-linked list.
   * public class ListNode {
   *     int val;
   *     ListNode next;
   *     ListNode() {}
   *     ListNode(int val) { this.val = val; }
   *     ListNode(int val, ListNode next) { this.val = val; this.next = next; }
   * }
   */
  class Solution {
      public ListNode addTwoNumbers(ListNode l1, ListNode l2) {
          ListNode dummy = new ListNode(0);
          int carry = 0;
          ListNode cur = dummy;
          while (l1 != null || l2 != null || carry != 0) {
              int s = (l1 == null ? 0 : l1.val) + (l2 == null ? 0 : l2.val) + carry;
              carry = s / 10;
              cur.next = new ListNode(s % 10);
              cur = cur.next;
              l1 = l1 == null ? null : l1.next;
              l2 = l2 == null ? null : l2.next;
          }
          return dummy.next;
      }
  }
#+end_src

*** *C++*
    :PROPERTIES:
    :CUSTOM_ID: c
    :END:
#+begin_src cpp
  /**
   * Definition for singly-linked list.
   * struct ListNode {
   *     int val;
   *     ListNode *next;
   *     ListNode() : val(0), next(nullptr) {}
   *     ListNode(int x) : val(x), next(nullptr) {}
   *     ListNode(int x, ListNode *next) : val(x), next(next) {}
   * };
   */
  class Solution {
  public:
      ListNode* addTwoNumbers(ListNode* l1, ListNode* l2) {
          ListNode* dummy = new ListNode();
          int carry = 0;
          ListNode* cur = dummy;
          while (l1 || l2 || carry) {
              int s = (l1 ? l1->val : 0) + (l2 ? l2->val : 0) + carry;
              carry = s / 10;
              cur->next = new ListNode(s % 10);
              cur = cur->next;
              l1 = l1 ? l1->next : nullptr;
              l2 = l2 ? l2->next : nullptr;
          }
          return dummy->next;
      }
  };
#+end_src

*** *JavaScript*
    :PROPERTIES:
    :CUSTOM_ID: javascript
    :END:
#+begin_src js
  /**
   * Definition for singly-linked list.
   * function ListNode(val, next) {
   *     this.val = (val===undefined ? 0 : val)
   *     this.next = (next===undefined ? null : next)
   * }
   */
  /**
   * @param {ListNode} l1
   * @param {ListNode} l2
   * @return {ListNode}
   */
  var addTwoNumbers = function(l1, l2) {
      const dummy = new ListNode();
      let carry = 0;
      let cur = dummy;
      while (l1 || l2 || carry) {
          const s = (l1?.val || 0) + (l2?.val || 0) + carry;
          carry = Math.floor(s / 10);
          cur.next = new ListNode(s % 10);
          cur = cur.next;
          l1 = l1?.next;
          l2 = l2?.next;
      }
      return dummy.next;
  };
#+end_src

*** *C#*
    :PROPERTIES:
    :CUSTOM_ID: c-1
    :END:
#+begin_example
  /**
   * Definition for singly-linked list.
   * public class ListNode {
   *     public int val;
   *     public ListNode next;
   *     public ListNode(int val=0, ListNode next=null) {
   *         this.val = val;
   *         this.next = next;
   *     }
   * }
   */
  public class Solution {
      public ListNode AddTwoNumbers(ListNode l1, ListNode l2) {
          ListNode dummy = new ListNode();
          int carry = 0;
          ListNode cur = dummy;
          while (l1 != null || l2 != null || carry != 0) {
              int s = (l1 == null ? 0 : l1.val) + (l2 == null ? 0 : l2.val) + carry;
              carry = s / 10;
              cur.next = new ListNode(s % 10);
              cur = cur.next;
              l1 = l1 == null ? null : l1.next;
              l2 = l2 == null ? null : l2.next;
          }
          return dummy.next;
      }
  }
#+end_example

*** *Go*
    :PROPERTIES:
    :CUSTOM_ID: go
    :END:
#+begin_example
  /**
   * Definition for singly-linked list.
   * type ListNode struct {
   *     Val int
   *     Next *ListNode
   * }
   */
  func addTwoNumbers(l1 *ListNode, l2 *ListNode) *ListNode {
      dummy := &ListNode{}
      carry := 0
      cur := dummy
      for l1 != nil || l2 != nil || carry != 0 {
          s := carry
          if l1 != nil {
              s += l1.Val
          }
          if l2 != nil {
              s += l2.Val
          }
          carry = s / 10
          cur.Next = &ListNode{s % 10, nil}
          cur = cur.Next
          if l1 != nil {
              l1 = l1.Next
          }
          if l2 != nil {
              l2 = l2.Next
          }
      }
      return dummy.Next
  }
#+end_example

*** *Ruby*
    :PROPERTIES:
    :CUSTOM_ID: ruby
    :END:
#+begin_example
  # Definition for singly-linked list.
  # class ListNode
  #     attr_accessor :val, :next
  #     def initialize(val = 0, _next = nil)
  #         @val = val
  #         @next = _next
  #     end
  # end
  # @param {ListNode} l1
  # @param {ListNode} l2
  # @return {ListNode}
  def add_two_numbers(l1, l2)
      dummy = ListNode.new()
      carry = 0
      cur = dummy
      while !l1.nil? || !l2.nil? || carry > 0
          s = (l1.nil? ? 0 : l1.val) + (l2.nil? ? 0 : l2.val) + carry
          carry = s / 10
          cur.next = ListNode.new(s % 10)
          cur = cur.next
          l1 = l1.nil? ? l1 : l1.next
          l2 = l2.nil? ? l2 : l2.next
      end
      dummy.next
  end
#+end_example

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
