* [[https://leetcode.com/problems/even-odd-tree][1609. Even Odd Tree]]
  :PROPERTIES:
  :CUSTOM_ID: even-odd-tree
  :END:
[[./solution/1600-1699/1609.Even Odd Tree/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

A binary tree is named Even-Odd if it meets the following conditions:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

The root of the binary tree is at level index 0, its children are at
level index 1, their children are at level index 2, etc.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

For every even-indexed level, all nodes at the level have odd integer
values in strictly increasing order (from left to right).

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

For every odd-indexed level, all nodes at the level have even integer
values in strictly decreasing order (from left to right).

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

#+begin_html
  <p>
#+end_html

Given the root of a binary tree, return true if the binary tree is
Even-Odd, otherwise return false.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> root = [1,10,4,3,null,7,9,12,8,6,null,null,2]
  <strong>Output:</strong> true
  <strong>Explanation:</strong> The node values on each level are:
  Level 0: [1]
  Level 1: [10,4]
  Level 2: [3,7,9]
  Level 3: [12,8,6,2]
  Since levels 0 and 2 are all odd and increasing, and levels 1 and 3 are all even and decreasing, the tree is Even-Odd.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> root = [5,4,2,3,3,7]
  <strong>Output:</strong> false
  <strong>Explanation:</strong> The node values on each level are:
  Level 0: [5]
  Level 1: [4,2]
  Level 2: [3,3,7]
  Node values in the level 2 must be in strictly increasing order, so the tree is not Even-Odd.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> root = [5,9,1,3,5,7]
  <strong>Output:</strong> false
  <strong>Explanation:</strong> Node values in the level 1 should be even integers.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 4:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> root = [1]
  <strong>Output:</strong> true
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 5:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> root = [11,8,6,1,3,9,11,30,20,18,16,12,10,4,2,17]
  <strong>Output:</strong> true
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

The number of nodes in the tree is in the range [1, 105].

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= Node.val <= 106

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
