* [[https://leetcode.com/problems/longest-uncommon-subsequence-i][521.
Longest Uncommon Subsequence I]]
  :PROPERTIES:
  :CUSTOM_ID: longest-uncommon-subsequence-i
  :END:
[[./solution/0500-0599/0521.Longest Uncommon Subsequence I/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Given two strings a and b, find the length of the longest uncommon
subsequence between them.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

A subsequence of a string s is a string that can be obtained after
deleting any number of characters from s. For example, "abc" is a
subsequence of "aebdc" because you can delete the underlined characters
in "aebdc" to get "abc". Other subsequences
of "aebdc" include "aebdc", "aeb", and "" (empty string).

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

An uncommon subsequence between two strings is a string that is a
subsequence of one but not the other.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the length of the longest uncommon subsequence between a and b.
If the longest uncommon subsequence doesn't exist, return -1.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> a = &quot;aba&quot;, b = &quot;cdc&quot;
  <strong>Output:</strong> 3
  <strong>Explanation:</strong> One longest uncommon subsequence is &quot;aba&quot; because &quot;aba&quot; is a subsequence of &quot;aba&quot; but not &quot;cdc&quot;.
  Note that &quot;cdc&quot; is also a longest uncommon subsequence.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> a = &quot;aaa&quot;, b = &quot;bbb&quot;
  <strong>Output:</strong> 3
  <strong>Explanation:</strong>&nbsp;The longest uncommon subsequences are &quot;aaa&quot; and &quot;bbb&quot;.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> a = &quot;aaa&quot;, b = &quot;aaa&quot;
  <strong>Output:</strong> -1
  <strong>Explanation:</strong>&nbsp;Every subsequence of string a is also a subsequence of string b. Similarly, every subsequence of string b is also a subsequence of string a.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= a.length, b.length <= 100

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

a and b consist of lower-case English letters.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
