* [[https://leetcode.com/problems/alien-dictionary][269. Alien
Dictionary]]
  :PROPERTIES:
  :CUSTOM_ID: alien-dictionary
  :END:
[[./solution/0200-0299/0269.Alien Dictionary/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

There is a new alien language that uses the English alphabet. However,
the order among the letters is unknown to you.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

You are given a list of strings words from the alien language's
dictionary, where the strings in words are sorted lexicographically by
the rules of this new language.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return a string of the unique letters in the new alien language sorted
in lexicographically increasing order by the new language's rules. If
there is no solution, return "". If there are multiple solutions, return
any of them.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

A string s is lexicographically smaller than a string t if at the first
letter where they differ, the letter in s comes before the letter in t
in the alien language. If the first min(s.length, t.length) letters are
the same, then s is smaller if and only if s.length < t.length.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> words = [&quot;wrt&quot;,&quot;wrf&quot;,&quot;er&quot;,&quot;ett&quot;,&quot;rftt&quot;]
  <strong>Output:</strong> &quot;wertf&quot;
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> words = [&quot;z&quot;,&quot;x&quot;]
  <strong>Output:</strong> &quot;zx&quot;
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> words = [&quot;z&quot;,&quot;x&quot;,&quot;z&quot;]
  <strong>Output:</strong> &quot;&quot;
  <strong>Explanation:</strong> The order is invalid, so return <code>&quot;&quot;</code>.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= words.length <= 100

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= words[i].length <= 100

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

words[i] consists of only lowercase English letters.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
