* [[https://leetcode.com/problems/zuma-game][488. Zuma Game]]
  :PROPERTIES:
  :CUSTOM_ID: zuma-game
  :END:
[[./solution/0400-0499/0488.Zuma Game/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Think about Zuma Game. You have a row of balls on the table, colored
red(R), yellow(Y), blue(B), green(G), and white(W). You also have
several balls in your hand.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Each time, you may choose a ball in your hand, and insert it into the
row (including the leftmost place and rightmost place). Then, if there
is a group of 3 or more balls in the same color touching, remove these
balls. Keep doing this until no more balls can be removed.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Find the minimal balls you have to insert to remove all the balls on the
table. If you cannot remove all the balls, output -1.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> board = &quot;WRRBBW&quot;, hand = &quot;RB&quot;
  <strong>Output:</strong> -1
  <strong>Explanation:</strong> WRRBBW -&gt; WRR[R]BBW -&gt; WBBW -&gt; WBB[B]W -&gt; WW
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> board = &quot;WWRRBBWW&quot;, hand = &quot;WRBRW&quot;
  <strong>Output:</strong> 2
  <strong>Explanation:</strong> WWRRBBWW -&gt; WWRR[R]BBWW -&gt; WWBBWW -&gt; WWBB[B]WW -&gt; WWWW -&gt; empty
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> board = &quot;G&quot;, hand = &quot;GGGGG&quot;
  <strong>Output:</strong> 2
  <strong>Explanation:</strong> G -&gt; G[G] -&gt; GG[G] -&gt; empty 
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 4:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> board = &quot;RBYYBBRRB&quot;, hand = &quot;YRBGB&quot;
  <strong>Output:</strong> 3
  <strong>Explanation:</strong> RBYYBBRRB -&gt; RBYY[Y]BBRRB -&gt; RBBBRRB -&gt; RRRB -&gt; B -&gt; B[B] -&gt; BB[B] -&gt; empty 
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

You may assume that the initial row of balls on the table won't have any
3 or more consecutive balls with the same color.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= board.length <= 16

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= hand.length <= 5

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Both input strings will be non-empty and only contain characters
'R','Y','B','G','W'.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
