* [[https://leetcode.com/problems/confusing-number-ii][1088. Confusing
Number II]]
  :PROPERTIES:
  :CUSTOM_ID: confusing-number-ii
  :END:
[[./solution/1000-1099/1088.Confusing Number II/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

We can rotate digits by 180 degrees to form new digits. When 0, 1, 6, 8,
9 are rotated 180 degrees, they become 0, 1, 9, 8, 6 respectively. When
2, 3, 4, 5 and 7 are rotated 180 degrees, they become invalid.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

A confusing number is a number that when rotated 180 degrees becomes a
different number with each digit valid.(Note that the rotated number can
be greater than the original number.)

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Given a positive integer N, return the number of confusing numbers
between 1 and N inclusive.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input: </strong><span id="example-input-1-1">20</span>

  <strong>Output: </strong><span id="example-output-1">6</span>

  <strong>Explanation: </strong>

  The confusing numbers are [6,9,10,16,18,19].

  6 converts to 9.

  9 converts to 6.

  10 converts to 01 which is just 1.

  16 converts to 91.

  18 converts to 81.

  19 converts to 61.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input: </strong><span id="example-input-2-1">100</span>

  <strong>Output: </strong><span id="example-output-2">19</span>

  <strong>Explanation: </strong>

  The confusing numbers are [6,9,10,16,18,19,60,61,66,68,80,81,86,89,90,91,98,99,100].

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Note:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ol>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= N <= 10^9

#+begin_html
  </li>
#+end_html

#+begin_html
  </ol>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
