* [[https://leetcode.com/problems/numbers-at-most-n-given-digit-set][902.
Numbers At Most N Given Digit Set]]
  :PROPERTIES:
  :CUSTOM_ID: numbers-at-most-n-given-digit-set
  :END:
[[./solution/0900-0999/0902.Numbers At Most N Given Digit Set/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Given an array of digits which is sorted in non-decreasing order. You
can write numbers using each digits[i] as many times as we want. For
example, if digits = ['1','3','5'], we may write numbers such as '13',
'551', and '1351315'.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the number of positive integers that can be generated that are
less than or equal to a given integer n.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> digits = [&quot;1&quot;,&quot;3&quot;,&quot;5&quot;,&quot;7&quot;], n = 100
  <strong>Output:</strong> 20
  <strong>Explanation: </strong>
  The 20 numbers that can be written are:
  1, 3, 5, 7, 11, 13, 15, 17, 31, 33, 35, 37, 51, 53, 55, 57, 71, 73, 75, 77.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> digits = [&quot;1&quot;,&quot;4&quot;,&quot;9&quot;], n = 1000000000
  <strong>Output:</strong> 29523
  <strong>Explanation: </strong>
  We can write 3 one digit numbers, 9 two digit numbers, 27 three digit numbers,
  81 four digit numbers, 243 five digit numbers, 729 six digit numbers,
  2187 seven digit numbers, 6561 eight digit numbers, and 19683 nine digit numbers.
  In total, this is 29523 integers that can be written using the digits array.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> digits = [&quot;7&quot;], n = 8
  <strong>Output:</strong> 1
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= digits.length <= 9

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

digits[i].length == 1

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

digits[i] is a digit from '1' to '9'.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

All the values in digits are unique.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

digits is sorted in non-decreasing order.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= n <= 109

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
