* [[https://leetcode.com/problems/smallest-rotation-with-highest-score][798.
Smallest Rotation with Highest Score]]
  :PROPERTIES:
  :CUSTOM_ID: smallest-rotation-with-highest-score
  :END:
[[./solution/0700-0799/0798.Smallest Rotation with Highest Score/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

 Given an array A, we may rotate it by a non-negative integer K so that
the array becomes A[K], A[K+1], A{K+2], ... A[A.length - 1], A[0], A[1],
..., A[K-1].  Afterward, any entries that are less than or equal to
their index are worth 1 point. 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

For example, if we have [2, 4, 1, 3, 0], and we rotate by K = 2, it
becomes [1, 3, 0, 2, 4].  This is worth 3 points because 1 > 0 [no
points], 3 > 1 [no points], 0 <= 2 [one point], 2 <= 3 [one point], 4 <=
4 [one point].

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Over all possible rotations, return the rotation index K that
corresponds to the highest score we could receive.  If there are
multiple answers, return the smallest such index K.

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Example 1:</strong>

  <strong>Input:</strong> [2, 3, 1, 4, 0]

  <strong>Output:</strong> 3

  <strong>Explanation: </strong> 

  Scores for each K are listed below: 

  K = 0,  A = [2,3,1,4,0],    score 2

  K = 1,  A = [3,1,4,0,2],    score 3

  K = 2,  A = [1,4,0,2,3],    score 3

  K = 3,  A = [4,0,2,3,1],    score 4

  K = 4,  A = [0,2,3,1,4],    score 3

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

So we should choose K = 3, which has the highest score.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Example 2:</strong>

  <strong>Input:</strong> [1, 3, 0, 2, 4]

  <strong>Output:</strong> 0

  <strong>Explanation: </strong> A will always have 3 points no matter how it shifts.

  So we will choose the smallest K, which is 0.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Note:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

A will have length at most 20000.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

A[i] will be in the range [0, A.length].

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
