* [[https://leetcode.com/problems/find-nearest-point-that-has-the-same-x-or-y-coordinate][1779.
Find Nearest Point That Has the Same X or Y Coordinate]]
  :PROPERTIES:
  :CUSTOM_ID: find-nearest-point-that-has-the-same-x-or-y-coordinate
  :END:
[[./solution/1700-1799/1779.Find Nearest Point That Has the Same X or Y Coordinate/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

You are given two integers, x and y, which represent your current
location on a Cartesian grid: (x, y). You are also given an array points
where each points[i] = [ai, bi] represents that a point exists at (ai,
bi). A point is valid if it shares the same x-coordinate or the same
y-coordinate as your location.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the index (0-indexed) of the valid point with the smallest
Manhattan distance from your current location. If there are multiple,
return the valid point with the smallest index. If there are no valid
points, return -1.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

The Manhattan distance between two points (x1, y1) and (x2, y2) is
abs(x1 - x2) + abs(y1 - y2).

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> x = 3, y = 4, points = [[1,2],[3,1],[2,4],[2,3],[4,4]]
  <strong>Output:</strong> 2
  <strong>Explanation:</strong> Of all the points, only [3,1], [2,4] and [4,4] are valid. Of the valid points, [2,4] and [4,4] have the smallest Manhattan distance from your current location, with a distance of 1. [2,4] has the smallest index, so return 2.</pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> x = 3, y = 4, points = [[3,4]]
  <strong>Output:</strong> 0
  <strong>Explanation:</strong> The answer is allowed to be on the same location as your current location.</pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> x = 3, y = 4, points = [[2,3]]
  <strong>Output:</strong> -1
  <strong>Explanation:</strong> There are no valid points.</pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= points.length <= 104

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

points[i].length == 2

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= x, y, ai, bi <= 104

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
