* [[https://leetcode.com/problems/student-attendance-record-i][551.
Student Attendance Record I]]
  :PROPERTIES:
  :CUSTOM_ID: student-attendance-record-i
  :END:
[[./solution/0500-0599/0551.Student Attendance Record I/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

You are given a string s representing an attendance record for a student
where each character signifies whether the student was absent, late, or
present on that day. The record only contains the following three
characters:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

'A': Absent.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

'L': Late.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

'P': Present.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

#+begin_html
  <p>
#+end_html

The student is eligible for an attendance award if they meet both of the
following criteria:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

The student was absent ('A') for strictly fewer than 2 days total.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

The student was never late ('L') for 3 or more consecutive days.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

#+begin_html
  <p>
#+end_html

Return true if the student is eligible for an attendance award, or false
otherwise.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> s = &quot;PPALLP&quot;
  <strong>Output:</strong> true
  <strong>Explanation:</strong> The student has fewer than 2 absences and was never late 3 or more consecutive days.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> s = &quot;PPALLL&quot;
  <strong>Output:</strong> false
  <strong>Explanation:</strong> The student was late 3 consecutive days in the last 3 days, so is not eligible for the award.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= s.length <= 1000

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

s[i] is either 'A', 'L', or 'P'.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
  class Solution:
      def checkRecord(self, s: str) -> bool:
          return s.count('A') <= 1 and 'LLL' not in s
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
  class Solution {
      public boolean checkRecord(String s) {
          int i = s.indexOf("A");
          return (i == -1 || s.lastIndexOf("A") == i) && !s.contains("LLL");
      }
  }
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
