* [[https://leetcode.com/problems/minimum-time-to-build-blocks][1199.
Minimum Time to Build Blocks]]
  :PROPERTIES:
  :CUSTOM_ID: minimum-time-to-build-blocks
  :END:
[[./solution/1100-1199/1199.Minimum Time to Build Blocks/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

You are given a list of blocks, where blocks[i] = t means that the i-th
block needs t units of time to be built. A block can only be built by
exactly one worker.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

A worker can either split into two workers (number of workers increases
by one) or build a block then go home. Both decisions cost some time.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

The time cost of spliting one worker into two workers is given as an
integer split. Note that if two workers split at the same time, they
split in parallel so the cost would be split.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Output the minimum time needed to build all blocks.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Initially, there is only one worker.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> blocks = [1], split = 1
  <strong>Output:</strong> 1
  <strong>Explanation: </strong>We use 1 worker to build 1 block in 1 time unit.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> blocks = [1,2], split = 5
  <strong>Output:</strong> 7
  <strong>Explanation: </strong>We split the worker into 2 workers in 5 time units then assign each of them to a block so the cost is 5 + max(1, 2) = 7.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> blocks = [1,2,3], split = 1
  <strong>Output:</strong> 4
  <strong>Explanation: </strong>Split 1 worker into 2, then assign the first worker to the last block and split the second worker into 2.
  Then, use the two unassigned workers to build the first two blocks.
  The cost is 1 + max(3, 1 + max(1, 2)) = 4.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= blocks.length <= 1000

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= blocks[i] <= 10^5

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= split <= 100

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
