* [[https://leetcode.com/problems/faulty-sensor][1826. Faulty Sensor]]
  :PROPERTIES:
  :CUSTOM_ID: faulty-sensor
  :END:
[[./solution/1800-1899/1826.Faulty Sensor/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

An experiment is being conducted in a lab. To ensure accuracy, there are
two sensors collecting data simultaneously. You are given 2 arrays
sensor1 and sensor2, where sensor1[i] and sensor2[i] are the ith data
points collected by the two sensors.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

However, this type of sensor has a chance of being defective, which
causes exactly one data point to be dropped. After the data is dropped,
all the data points to the right of the dropped data are shifted one
place to the left, and the last data point is replaced with some random
value. It is guaranteed that this random value will not be equal to the
dropped value.

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

For example, if the correct data is [1,2,3,4,5] and 3 is dropped, the
sensor could return [1,2,4,5,7] (the last position can be any value, not
just 7).

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

#+begin_html
  <p>
#+end_html

We know that there is a defect in at most one of the sensors. Return the
sensor number (1 or 2) with the defect. If there is no defect in either
sensor or if it is impossible to determine the defective sensor, return
-1.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> sensor1 = [2,3,4,5], sensor2 = [2,1,3,4]
  <strong>Output:</strong> 1
  <strong>Explanation:</strong> Sensor 2 has the correct values.
  The second data point from sensor 2 is dropped, and the last value of sensor 1 is replaced by a 5.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> sensor1 = [2,2,2,2,2], sensor2 = [2,2,2,2,5]
  <strong>Output:</strong> -1
  <strong>Explanation:</strong> It is impossible to determine which sensor has a defect.
  Dropping the last value for either sensor could produce the output for the other sensor.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> sensor1 = [2,3,2,2,3,2], sensor2 = [2,3,2,3,2,7]
  <strong>Output:</strong> 2
  <strong>Explanation: </strong>Sensor 1 has the correct values.
  The fourth data point from sensor 1 is dropped, and the last value of sensor 1 is replaced by a 7.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

sensor1.length == sensor2.length

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= sensor1.length <= 100

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= sensor1[i], sensor2[i] <= 100

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
