* [[https://leetcode.com/problems/get-equal-substrings-within-budget][1208.
Get Equal Substrings Within Budget]]
  :PROPERTIES:
  :CUSTOM_ID: get-equal-substrings-within-budget
  :END:
[[./solution/1200-1299/1208.Get Equal Substrings Within Budget/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

You are given two strings s and t of the same length. You want to change
s to t. Changing the i-th character of s to i-th character of t costs
|s[i] - t[i]| that is, the absolute difference between the ASCII values
of the characters.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

You are also given an integer maxCost.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the maximum length of a substring of s that can be changed to be
the same as the corresponding substring of twith a cost less than or
equal to maxCost.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

If there is no substring from s that can be changed to its corresponding
substring from t, return 0.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> s = &quot;abcd&quot;, t = &quot;bcdf&quot;, maxCost = 3
  <strong>Output:</strong> 3
  <strong>Explanation: </strong>&quot;abc&quot; of s can change to &quot;bcd&quot;. That costs 3, so the maximum length is 3.</pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> s = &quot;abcd&quot;, t = &quot;cdef&quot;, maxCost = 3
  <strong>Output:</strong> 1
  <strong>Explanation: </strong>Each character in s costs 2 to change to charactor in <code>t, so the maximum length is 1.</code>
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> s = &quot;abcd&quot;, t = &quot;acde&quot;, maxCost = 0
  <strong>Output:</strong> 1
  <strong>Explanation: </strong>You can&#39;t make any change, so the maximum length is 1.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= s.length, t.length <= 10^5

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= maxCost <= 10^6

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

s and t only contain lower case English letters.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
