* [[https://leetcode.com/problems/most-profit-assigning-work][826. Most
Profit Assigning Work]]
  :PROPERTIES:
  :CUSTOM_ID: most-profit-assigning-work
  :END:
[[./solution/0800-0899/0826.Most Profit Assigning Work/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

We have jobs: difficulty[i] is the difficulty of the ith job,
and profit[i] is the profit of the ith job. 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Now we have some workers. worker[i] is the ability of the ith worker,
which means that this worker can only complete a job with difficulty at
most worker[i]. 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Every worker can be assigned at most one job, but one job can be
completed multiple times.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

For example, if 3 people attempt the same job that pays $1, then the
total profit will be $3.  If a worker cannot complete any job, his
profit is $0.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

What is the most profit we can make?

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input: </strong>difficulty = [2,4,6,8,10], profit = [10,20,30,40,50], worker = [4,5,6,7]

  <strong>Output: </strong>100 

  <strong>Explanation: W</strong>orkers are assigned jobs of difficulty [4,4,6,6] and they get profit of [20,20,30,30] seperately.</pre>
#+end_html

#+begin_html
  <p>
#+end_html

Notes:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= difficulty.length = profit.length <= 10000

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= worker.length <= 10000

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

difficulty[i], profit[i], worker[i]  are in range [1, 10^5]

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
