* [[https://leetcode.com/problems/longest-turbulent-subarray][978.
Longest Turbulent Subarray]]
  :PROPERTIES:
  :CUSTOM_ID: longest-turbulent-subarray
  :END:
[[./solution/0900-0999/0978.Longest Turbulent Subarray/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Given an integer array arr, return the length of a maximum size
turbulent subarray of arr.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

A subarray is turbulent if the comparison sign flips between each
adjacent pair of elements in the subarray.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

More formally, a subarray [arr[i], arr[i + 1], ..., arr[j]] of arr is
said to be turbulent if and only if:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

For i <= k < j:

#+begin_example
  <ul>
      <li><code>arr[k] &gt; arr[k + 1]</code> when <code>k</code> is odd, and</li>
      <li><code>arr[k] &lt; arr[k + 1]</code> when <code>k</code> is even.</li>
  </ul>
  </li>
  <li>Or, for <code>i &lt;= k &lt; j</code>:
  <ul>
      <li><code>arr[k] &gt; arr[k + 1]</code> when <code>k</code> is even, and</li>
      <li><code>arr[k] &lt; arr[k + 1]</code> when <code>k</code> is odd.</li>
  </ul>
  </li>
#+end_example

#+begin_html
  </ul>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> arr = [9,4,2,10,7,8,8,1,9]
  <strong>Output:</strong> 5
  <strong>Explanation:</strong> arr[1] &gt; arr[2] &lt; arr[3] &gt; arr[4] &lt; arr[5]
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> arr = [4,8,12,16]
  <strong>Output:</strong> 2
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> arr = [100]
  <strong>Output:</strong> 1
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= arr.length <= 4 * 104

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= arr[i] <= 109

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
