* [[https://leetcode.com/problems/text-justification][68. Text
Justification]]
  :PROPERTIES:
  :CUSTOM_ID: text-justification
  :END:
[[./solution/0000-0099/0068.Text Justification/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Given an array of words and a width maxWidth, format the text such that
each line has exactly maxWidth characters and is fully (left and right)
justified.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

You should pack your words in a greedy approach; that is, pack as many
words as you can in each line. Pad extra spaces ' ' when necessary so
that each line has exactly maxWidth characters.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Extra spaces between words should be distributed as evenly as possible.
If the number of spaces on a line do not divide evenly between words,
the empty slots on the left will be assigned more spaces than the slots
on the right.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

For the last line of text, it should be left justified and no extra
space is inserted between words.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Note:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

A word is defined as a character sequence consisting of non-space
characters only.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Each word's length is guaranteed to be greater than 0 and not exceed
maxWidth.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

The input array words contains at least one word.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> words = [&quot;This&quot;, &quot;is&quot;, &quot;an&quot;, &quot;example&quot;, &quot;of&quot;, &quot;text&quot;, &quot;justification.&quot;], maxWidth = 16
  <strong>Output:</strong>
  [
  &nbsp; &nbsp;&quot;This &nbsp; &nbsp;is &nbsp; &nbsp;an&quot;,
  &nbsp; &nbsp;&quot;example &nbsp;of text&quot;,
  &nbsp; &nbsp;&quot;justification. &nbsp;&quot;
  ]</pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> words = [&quot;What&quot;,&quot;must&quot;,&quot;be&quot;,&quot;acknowledgment&quot;,&quot;shall&quot;,&quot;be&quot;], maxWidth = 16
  <strong>Output:</strong>
  [
  &nbsp; &quot;What &nbsp; must &nbsp; be&quot;,
  &nbsp; &quot;acknowledgment &nbsp;&quot;,
  &nbsp; &quot;shall be &nbsp; &nbsp; &nbsp; &nbsp;&quot;
  ]
  <strong>Explanation:</strong> Note that the last line is &quot;shall be    &quot; instead of &quot;shall     be&quot;, because the last line must be left-justified instead of fully-justified.
  Note that the second line is also left-justified becase it contains only one word.</pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> words = [&quot;Science&quot;,&quot;is&quot;,&quot;what&quot;,&quot;we&quot;,&quot;understand&quot;,&quot;well&quot;,&quot;enough&quot;,&quot;to&quot;,&quot;explain&quot;,&quot;to&quot;,&quot;a&quot;,&quot;computer.&quot;,&quot;Art&quot;,&quot;is&quot;,&quot;everything&quot;,&quot;else&quot;,&quot;we&quot;,&quot;do&quot;], maxWidth = 20
  <strong>Output:</strong>
  [
  &nbsp; &quot;Science &nbsp;is &nbsp;what we&quot;,
    &quot;understand &nbsp; &nbsp; &nbsp;well&quot;,
  &nbsp; &quot;enough to explain to&quot;,
  &nbsp; &quot;a &nbsp;computer. &nbsp;Art is&quot;,
  &nbsp; &quot;everything &nbsp;else &nbsp;we&quot;,
  &nbsp; &quot;do &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&quot;
  ]</pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= words.length <= 300

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= words[i].length <= 20

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

words[i] consists of only English letters and symbols.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= maxWidth <= 100

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

words[i].length <= maxWidth

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
