* [[https://leetcode.com/problems/maximize-grid-happiness][1659.
Maximize Grid Happiness]]
  :PROPERTIES:
  :CUSTOM_ID: maximize-grid-happiness
  :END:
[[./solution/1600-1699/1659.Maximize Grid Happiness/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

You are given four integers, m, n, introvertsCount, and extrovertsCount.
You have an m x n grid, and there are two types of people: introverts
and extroverts. There are introvertsCount introverts and extrovertsCount
extroverts.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

You should decide how many people you want to live in the grid and
assign each of them one grid cell. Note that you do not have to have all
the people living in the grid.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

The happiness of each person is calculated as follows:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

Introverts start with 120 happiness and lose 30 happiness for each
neighbor (introvert or extrovert).

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Extroverts start with 40 happiness and gain 20 happiness for each
neighbor (introvert or extrovert).

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

#+begin_html
  <p>
#+end_html

Neighbors live in the directly adjacent cells north, east, south, and
west of a person's cell.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

The grid happiness is the sum of each person's happiness. Return the
maximum possible grid happiness.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> m = 2, n = 3, introvertsCount = 1, extrovertsCount = 2
  <strong>Output:</strong> 240
  <strong>Explanation:</strong> Assume the grid is 1-indexed with coordinates (row, column).
  We can put the introvert in cell (1,1) and put the extroverts in cells (1,3) and (2,3).
  - Introvert at (1,1) happiness: 120 (starting happiness) - (0 * 30) (0 neighbors) = 120
  - Extrovert at (1,3) happiness: 40 (starting happiness) + (1 * 20) (1 neighbor) = 60
  - Extrovert at (2,3) happiness: 40 (starting happiness) + (1 * 20) (1 neighbor) = 60
  The grid happiness is 120 + 60 + 60 = 240.
  The above figure shows the grid in this example with each person&#39;s happiness. The introvert stays in the light green cell while the extroverts live on the light purple cells.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> m = 3, n = 1, introvertsCount = 2, extrovertsCount = 1
  <strong>Output:</strong> 260
  <strong>Explanation:</strong> Place the two introverts in (1,1) and (3,1) and the extrovert at (2,1).
  - Introvert at (1,1) happiness: 120 (starting happiness) - (1 * 30) (1 neighbor) = 90
  - Extrovert at (2,1) happiness: 40 (starting happiness) + (2 * 20) (2 neighbors) = 80
  - Introvert at (3,1) happiness: 120 (starting happiness) - (1 * 30) (1 neighbor) = 90
  The grid happiness is 90 + 80 + 90 = 260.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> m = 2, n = 2, introvertsCount = 4, extrovertsCount = 0
  <strong>Output:</strong> 240
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= m, n <= 5

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= introvertsCount, extrovertsCount <= min(m * n, 6)

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
