* [[https://leetcode.com/problems/poor-pigs][458. Poor Pigs]]
  :PROPERTIES:
  :CUSTOM_ID: poor-pigs
  :END:
[[./solution/0400-0499/0458.Poor Pigs/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

There are buckets buckets of liquid, where exactly one of the buckets is
poisonous. To figure out which one is poisonous, you feed some number of
(poor) pigs the liquid to see whether they will die or not.
Unfortunately, you only have minutesToTest minutes to determine which
bucket is poisonous.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

You can feed the pigs according to these steps:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ol>
#+end_html

#+begin_html
  <li>
#+end_html

Choose some live pigs to feed.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

For each pig, choose which buckets to feed it. The pig will consume all
the chosen buckets simultaneously and will take no time.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Wait for minutesToDie minutes. You may not feed any other pigs during
this time.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

After minutesToDie minutes have passed, any pigs that have been fed the
poisonous bucket will die, and all others will survive.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Repeat this process until you run out of time.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ol>
#+end_html

#+begin_html
  <p>
#+end_html

Given buckets, minutesToDie, and minutesToTest, return the minimum
number of pigs needed to figure out which bucket is poisonous within the
allotted time.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre><strong>Input:</strong> buckets = 1000, minutesToDie = 15, minutesToTest = 60
  <strong>Output:</strong> 5
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre><strong>Input:</strong> buckets = 4, minutesToDie = 15, minutesToTest = 15
  <strong>Output:</strong> 2
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre><strong>Input:</strong> buckets = 4, minutesToDie = 15, minutesToTest = 30
  <strong>Output:</strong> 2
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= buckets <= 1000

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= minutesToDie <= minutesToTest <= 100

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
