* [[https://leetcode.com/problems/stone-game][877. Stone Game]]
  :PROPERTIES:
  :CUSTOM_ID: stone-game
  :END:
[[./solution/0800-0899/0877.Stone Game/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Alex and Lee play a game with piles of stones.  There are an even number
of piles arranged in a row, and each pile has a positive integer number
of stones piles[i].

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

The objective of the game is to end with the most stones.  The total
number of stones is odd, so there are no ties.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Alex and Lee take turns, with Alex starting first.  Each turn, a
player takes the entire pile of stones from either the beginning or the
end of the row.  This continues until there are no more piles left, at
which point the person with the most stones wins.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Assuming Alex and Lee play optimally, return True if and only if Alex
wins the game.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> piles = [5,3,4,5]
  <strong>Output:</strong> true
  <strong>Explanation: </strong>
  Alex starts first, and can only take the first 5 or the last 5.
  Say he takes the first 5, so that the row becomes [3, 4, 5].
  If Lee takes 3, then the board is [4, 5], and Alex takes 5 to win with 10 points.
  If Lee takes the last 5, then the board is [3, 4], and Alex takes 4 to win with 9 points.
  This demonstrated that taking the first 5 was a winning move for Alex, so we return true.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

2 <= piles.length <= 500

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

piles.length is even.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= piles[i] <= 500

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

sum(piles) is odd.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
