* [[https://leetcode.com/problems/furthest-building-you-can-reach][1642.
Furthest Building You Can Reach]]
  :PROPERTIES:
  :CUSTOM_ID: furthest-building-you-can-reach
  :END:
[[./solution/1600-1699/1642.Furthest Building You Can Reach/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

You are given an integer array heights representing the heights of
buildings, some bricks, and some ladders.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

You start your journey from building 0 and move to the next building by
possibly using bricks or ladders.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

While moving from building i to building i+1 (0-indexed),

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

If the current building's height is greater than or equal to the next
building's height, you do not need a ladder or bricks.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

If the current building's height is less than the next building's
height, you can either use one ladder or (h[i+1] - h[i]) bricks.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

#+begin_html
  <p>
#+end_html

Return the furthest building index (0-indexed) you can reach if you use
the given ladders and bricks optimally.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> heights = [4,2,7,6,9,14,12], bricks = 5, ladders = 1
  <strong>Output:</strong> 4
  <strong>Explanation:</strong> Starting at building 0, you can follow these steps:
  - Go to building 1 without using ladders nor bricks since 4 &gt;= 2.
  - Go to building 2 using 5 bricks. You must use either bricks or ladders because 2 &lt; 7.
  - Go to building 3 without using ladders nor bricks since 7 &gt;= 6.
  - Go to building 4 using your only ladder. You must use either bricks or ladders because 6 &lt; 9.
  It is impossible to go beyond building 4 because you do not have any more bricks or ladders.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> heights = [4,12,2,7,3,18,20,3,19], bricks = 10, ladders = 2
  <strong>Output:</strong> 7
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> heights = [14,3,19,3], bricks = 17, ladders = 0
  <strong>Output:</strong> 3
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= heights.length <= 105

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= heights[i] <= 106

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= bricks <= 109

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= ladders <= heights.length

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
