* [[https://leetcode.com/problems/complete-binary-tree-inserter][919.
Complete Binary Tree Inserter]]
  :PROPERTIES:
  :CUSTOM_ID: complete-binary-tree-inserter
  :END:
[[./solution/0900-0999/0919.Complete Binary Tree Inserter/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

A complete binary tree is a binary tree in which every level, except
possibly the last, is completely filled, and all nodes are as far left
as possible.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Write a data structure CBTInserter that is initialized with a complete
binary tree and supports the following operations:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

CBTInserter(TreeNode root) initializes the data structure on a given
tree with head node root;

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

CBTInserter.insert(int v) will insert a TreeNode into the tree with
value node.val = v so that the tree remains complete, and returns the
value of the parent of the inserted TreeNode;

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

CBTInserter.get_root() will return the head node of the tree.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

#+begin_html
  <ol>
#+end_html

#+begin_html
  </ol>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input: </strong>inputs = <span id="example-input-1-1">[&quot;CBTInserter&quot;,&quot;insert&quot;,&quot;get_root&quot;]</span>, inputs = <span id="example-input-1-2">[[[1]],[2],[]]</span>

  <strong>Output: </strong><span id="example-output-1">[null,1,[1,2]]</span>

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input: </strong>inputs = <span id="example-input-2-1">[&quot;CBTInserter&quot;,&quot;insert&quot;,&quot;insert&quot;,&quot;get_root&quot;]</span>, inputs = <span id="example-input-2-2">[[[1,2,3,4,5,6]],[7],[8],[]]</span>

  <strong>Output: </strong><span id="example-output-2">[null,3,4,[1,2,3,4,5,6,7,8]]</span></pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Note:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ol>
#+end_html

#+begin_html
  <li>
#+end_html

The initial given tree is complete and contains between 1 and 1000
nodes.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

CBTInserter.insert is called at most 10000 times per test case.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Every value of a given or inserted node is between 0 and 5000.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ol>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

 

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
