* [[https://leetcode.com/problems/redundant-connection][684. Redundant
Connection]]
  :PROPERTIES:
  :CUSTOM_ID: redundant-connection
  :END:
[[./solution/0600-0699/0684.Redundant Connection/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

In this problem, a tree is an undirected graph that is connected and has
no cycles.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

The given input is a graph that started as a tree with N nodes (with
distinct values 1, 2, ..., N), with one additional edge added. The added
edge has two different vertices chosen from 1 to N, and was not an edge
that already existed.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

The resulting graph is given as a 2D-array of edges. Each element of
edges is a pair [u, v] with u < v, that represents an undirected edge
connecting nodes u and v.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return an edge that can be removed so that the resulting graph is a tree
of N nodes. If there are multiple answers, return the answer that occurs
last in the given 2D-array. The answer edge [u, v] should be in the same
format, with u < v.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  <pre>

  <b>Input:</b> [[1,2], [1,3], [2,3]]

  <b>Output:</b> [2,3]

  <b>Explanation:</b> The given undirected graph will be like this:

    1

   / \

  2 - 3

  </pre>
#+end_html

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  <pre>

  <b>Input:</b> [[1,2], [2,3], [3,4], [1,4], [1,5]]

  <b>Output:</b> [1,4]

  <b>Explanation:</b> The given undirected graph will be like this:

  5 - 1 - 2

      |   |

      4 - 3

  </pre>
#+end_html

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Note:

#+begin_html
  <li>
#+end_html

The size of the input 2D-array will be between 3 and 1000.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Every integer represented in the 2D-array will be between 1 and N, where
N is the size of the input array.

#+begin_html
  </li>
#+end_html

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Update (2017-09-26):

We have overhauled the problem description + test cases and specified
clearly the graph is an undirected graph. For the directed graph follow
up please see Redundant Connection II). We apologize for any
inconvenience caused.

#+begin_html
  </p>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
