* [[https://leetcode.com/problems/my-calendar-ii][731. My Calendar II]]
  :PROPERTIES:
  :CUSTOM_ID: my-calendar-ii
  :END:
[[./solution/0700-0799/0731.My Calendar II/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Implement a MyCalendarTwo class to store your events. A new event can be
added if adding the event will not cause a triple booking.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Your class will have one method, book(int start, int end). Formally,
this represents a booking on the half open interval [start, end), the
range of real numbers x such that start <= x < end.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

A triple booking happens when three events have some non-empty
intersection (ie., there is some time that is common to all 3 events.)

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

For each call to the method MyCalendar.book, return true if the event
can be added to the calendar successfully without causing a triple
booking. Otherwise, return false and do not add the event to the
calendar.

#+begin_html
  </p>
#+end_html

Your class will be called like this: MyCalendar cal = new MyCalendar();
MyCalendar.book(start, end)

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  MyCalendar();

  MyCalendar.book(10, 20); // returns true

  MyCalendar.book(50, 60); // returns true

  MyCalendar.book(10, 40); // returns true

  MyCalendar.book(5, 15); // returns false

  MyCalendar.book(5, 10); // returns true

  MyCalendar.book(25, 55); // returns true

  <b>Explanation:</b> 

  The first two events can be booked.  The third event can be double booked.

  The fourth event (5, 15) can&#39;t be booked, because it would result in a triple booking.

  The fifth event (5, 10) can be booked, as it does not use time 10 which is already double booked.

  The sixth event (25, 55) can be booked, as the time in [25, 40) will be double booked with the third event;

  the time [40, 50) will be single booked, and the time [50, 55) will be double booked with the second event.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Note:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

The number of calls to MyCalendar.book per test case will be at most
1000.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

In calls to MyCalendar.book(start, end), start and end are integers in
the range [0, 10^9].

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
