* [[https://leetcode.com/problems/car-fleet][853. Car Fleet]]
  :PROPERTIES:
  :CUSTOM_ID: car-fleet
  :END:
[[./solution/0800-0899/0853.Car Fleet/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

N cars are going to the same destination along a one lane road.  The
destination is target miles away.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Each car i has a constant speed speed[i] (in miles per hour), and
initial position position[i] miles towards the target along the road.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

A car can never pass another car ahead of it, but it can catch up to it,
and drive bumper to bumper at the same speed.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

The distance between these two cars is ignored - they are assumed to
have the same position.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

A car fleet is some non-empty set of cars driving at the same position
and same speed.  Note that a single car is also a car fleet.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

If a car catches up to a car fleet right at the destination point, it
will still be considered as one car fleet.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

How many car fleets will arrive at the destination?

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input: </strong>target = <span id="example-input-1-1">12</span>, position = <span id="example-input-1-2">[10,8,0,5,3]</span>, speed = <span id="example-input-1-3">[2,4,1,1,3]</span>

  <strong>Output: </strong><span id="example-output-1">3</span>

  <strong>Explanation</strong>:

  The cars starting at 10 and 8 become a fleet, meeting each other at 12.

  The car starting at 0 doesn&#39;t catch up to any other car, so it is a fleet by itself.

  The cars starting at 5 and 3 become a fleet, meeting each other at 6.

  Note that no other cars meet these fleets before the destination, so the answer is 3.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Note:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ol>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= N <= 10 ^ 4

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 < target <= 10 ^ 6

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 < speed[i] <= 10 ^ 6

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= position[i] < target

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

All initial positions are different.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ol>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
