* [[https://leetcode.com/problems/maximum-average-pass-ratio][1792.
Maximum Average Pass Ratio]]
  :PROPERTIES:
  :CUSTOM_ID: maximum-average-pass-ratio
  :END:
[[./solution/1700-1799/1792.Maximum Average Pass Ratio/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

There is a school that has classes of students and each class will be
having a final exam. You are given a 2D integer array classes, where
classes[i] = [passi, totali]. You know beforehand that in the ith class,
there are totali total students, but only passi number of students will
pass the exam.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

You are also given an integer extraStudents. There are another
extraStudents brilliant students that are guaranteed to pass the exam of
any class they are assigned to. You want to assign each of the
extraStudents students to a class in a way that maximizes the average
pass ratio across all the classes.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

The pass ratio of a class is equal to the number of students of the
class that will pass the exam divided by the total number of students of
the class. The average pass ratio is the sum of pass ratios of all the
classes divided by the number of the classes.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the maximum possible average pass ratio after assigning the
extraStudents students. Answers within 10-5 of the actual answer will be
accepted.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> classes = [[1,2],[3,5],[2,2]], <code>extraStudents</code> = 2
  <strong>Output:</strong> 0.78333
  <strong>Explanation:</strong> You can assign the two extra students to the first class. The average pass ratio will be equal to (3/4 + 3/5 + 2/2) / 3 = 0.78333.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> classes = [[2,4],[3,9],[4,5],[2,10]], <code>extraStudents</code> = 4
  <strong>Output:</strong> 0.53485
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= classes.length <= 105

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

classes[i].length == 2

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= passi <= totali <= 105

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= extraStudents <= 105

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
