* [[https://leetcode.com/problems/maximum-students-taking-exam][1349.
Maximum Students Taking Exam]]
  :PROPERTIES:
  :CUSTOM_ID: maximum-students-taking-exam
  :END:
[[./solution/1300-1399/1349.Maximum Students Taking Exam/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Given a m * n matrix seats  that represent seats distributions in a
classroom. If a seat is broken, it is denoted by '#' character otherwise
it is denoted by a '.' character.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Students can see the answers of those sitting next to the left, right,
upper left and upper right, but he cannot see the answers of the student
sitting directly in front or behind him. Return the maximum number of
students that can take the exam together without any cheating being
possible..

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Students must be placed in seats in good condition.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> seats = [[&quot;#&quot;,&quot;.&quot;,&quot;#&quot;,&quot;#&quot;,&quot;.&quot;,&quot;#&quot;],
  &nbsp;               [&quot;.&quot;,&quot;#&quot;,&quot;#&quot;,&quot;#&quot;,&quot;#&quot;,&quot;.&quot;],
  &nbsp;               [&quot;#&quot;,&quot;.&quot;,&quot;#&quot;,&quot;#&quot;,&quot;.&quot;,&quot;#&quot;]]
  <strong>Output:</strong> 4
  <strong>Explanation:</strong> Teacher can place 4 students in available seats so they don&#39;t cheat on the exam. 
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> seats = [[&quot;.&quot;,&quot;#&quot;],
  &nbsp;               [&quot;#&quot;,&quot;#&quot;],
  &nbsp;               [&quot;#&quot;,&quot;.&quot;],
  &nbsp;               [&quot;#&quot;,&quot;#&quot;],
  &nbsp;               [&quot;.&quot;,&quot;#&quot;]]
  <strong>Output:</strong> 3
  <strong>Explanation:</strong> Place all students in available seats. 

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> seats = [[&quot;#&quot;,&quot;.&quot;,&quot;<strong>.</strong>&quot;,&quot;.&quot;,&quot;#&quot;],
  &nbsp;               [&quot;<strong>.</strong>&quot;,&quot;#&quot;,&quot;<strong>.</strong>&quot;,&quot;#&quot;,&quot;<strong>.</strong>&quot;],
  &nbsp;               [&quot;<strong>.</strong>&quot;,&quot;.&quot;,&quot;#&quot;,&quot;.&quot;,&quot;<strong>.</strong>&quot;],
  &nbsp;               [&quot;<strong>.</strong>&quot;,&quot;#&quot;,&quot;<strong>.</strong>&quot;,&quot;#&quot;,&quot;<strong>.</strong>&quot;],
  &nbsp;               [&quot;#&quot;,&quot;.&quot;,&quot;<strong>.</strong>&quot;,&quot;.&quot;,&quot;#&quot;]]
  <strong>Output:</strong> 10
  <strong>Explanation:</strong> Place students in available seats in column 1, 3 and 5.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

seats contains only characters '.' and'#'.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

m == seats.length

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

n == seats[i].length

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= m <= 8

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= n <= 8

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
