* [[https://leetcode-cn.com/problems/living-people-lcci][16.10. Living
People]]
  :PROPERTIES:
  :CUSTOM_ID: living-people
  :END:
[[./lcci/16.10.Living People/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Given a list of people with their birth and death years, implement a
method to compute the year with the most number of people alive. You may
assume that all people were born between 1900 and 2000 (inclusive). If a
person was alive during any portion of that year, they should be
included in that year's count. For example, Person (birth= 1908,
death= 1909) is included in the counts for both 1908 and 1909.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

If there are more than one years that have the most number of people
alive, return the smallest one.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input: </strong>

  birth = {1900, 1901, 1950}

  death = {1948, 1951, 2000}

  <strong>Output: </strong> 1901

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Note:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

0 < birth.length == death.length <= 10000

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

birth[i] <= death[i]

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
  class Solution:
      def maxAliveYear(self, birth: List[int], death: List[int]) -> int:
          years = [0] * 101
          for i in range(len(birth)):
              start = birth[i] - 1900
              end = death[i] - 1900
              for j in range(start, end + 1):
                  years[j] += 1
          max_v = years[0]
          res = 0
          for i in range(1, 101):
              if years[i] > max_v:
                  max_v = years[i]
                  res = i
          return 1900 + res
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
  class Solution {
      public int maxAliveYear(int[] birth, int[] death) {
          int[] years = new int[101];
          int n = birth.length;
          for (int i = 0; i < n; ++i) {
              int start = birth[i] - 1900;
              int end = death[i] - 1900;
              for (int j = start; j <= end; ++j) {
                  ++years[j];
              }
          }
          int max = years[0];
          int res = 0;
          for (int i = 1; i < 101; ++i) {
              if (years[i] > max) {
                  max = years[i];
                  res = i;
              }
          }
          return 1900 + res;
      }
  }
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
