* [[https://leetcode.com/problems/minimum-cost-to-connect-sticks][1167.
Minimum Cost to Connect Sticks]]
  :PROPERTIES:
  :CUSTOM_ID: minimum-cost-to-connect-sticks
  :END:
[[./solution/1100-1199/1167.Minimum Cost to Connect Sticks/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

You have some number of sticks with positive integer lengths. These
lengths are given as an array sticks, where sticks[i] is the length of
the ith stick.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

You can connect any two sticks of lengths x and y into one stick by
paying a cost of x + y. You must connect all the sticks until there is
only one stick remaining.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the minimum cost of connecting all the given sticks into one
stick in this way.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> sticks = [2,4,3]
  <strong>Output:</strong> 14
  <strong>Explanation:</strong>&nbsp;You start with sticks = [2,4,3].
  1. Combine sticks 2 and 3 for a cost of 2 + 3 = 5. Now you have sticks = [5,4].
  2. Combine sticks 5 and 4 for a cost of 5 + 4 = 9. Now you have sticks = [9].
  There is only one stick left, so you are done. The total cost is 5 + 9 = 14.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> sticks = [1,8,3,5]
  <strong>Output:</strong> 30
  <strong>Explanation:</strong> You start with sticks = [1,8,3,5].
  1. Combine sticks 1 and 3 for a cost of 1 + 3 = 4. Now you have sticks = [4,8,5].
  2. Combine sticks 4 and 5 for a cost of 4 + 5 = 9. Now you have sticks = [9,8].
  3. Combine sticks 9 and 8 for a cost of 9 + 8 = 17. Now you have sticks = [17].
  There is only one stick left, so you are done. The total cost is 4 + 9 + 17 = 30.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> sticks = [5]
  <strong>Output:</strong> 0
  <strong>Explanation:</strong> There is only one stick, so you don&#39;t need to do anything. The total cost is 0.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= sticks.length <= 104

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= sticks[i] <= 104

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
