* [[https://leetcode.com/problems/number-of-lines-to-write-string][806.
Number of Lines To Write String]]
  :PROPERTIES:
  :CUSTOM_ID: number-of-lines-to-write-string
  :END:
[[./solution/0800-0899/0806.Number of Lines To Write String/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

You are given a string s of lowercase English letters and an array
widths denoting how many pixels wide each lowercase English letter is.
Specifically, widths[0] is the width of 'a', widths[1] is the width of
'b', and so on.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

You are trying to write s across several lines, where each line is no
longer than 100 pixels. Starting at the beginning of s, write as many
letters on the first line such that the total width does not exceed 100
pixels. Then, from where you stopped in s, continue writing as many
letters as you can on the second line. Continue this process until you
have written all of s.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return an array result of length 2 where:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

result[0] is the total number of lines.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

result[1] is the width of the last line in pixels.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> widths = [10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10], s = &quot;abcdefghijklmnopqrstuvwxyz&quot;
  <strong>Output:</strong> [3,60]
  <strong>Explanation:</strong> You can write s as follows:
  abcdefghij  // 100 pixels wide
  klmnopqrst  // 100 pixels wide
  uvwxyz      // 60 pixels wide
  There are a total of 3 lines, and the last line is 60 pixels wide.</pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> widths = [4,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10], s = &quot;bbbcccdddaaa&quot;
  <strong>Output:</strong> [2,4]
  <strong>Explanation:</strong> You can write s as follows:
  bbbcccdddaa  // 98 pixels wide
  a            // 4 pixels wide
  There are a total of 2 lines, and the last line is 4 pixels wide.</pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

widths.length == 26

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

2 <= widths[i] <= 10

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= s.length <= 1000

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

s contains only lowercase English letters.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
