* [[https://leetcode.com/problems/finding-the-users-active-minutes][1817.
Finding the Users Active Minutes]]
  :PROPERTIES:
  :CUSTOM_ID: finding-the-users-active-minutes
  :END:
[[./solution/1800-1899/1817.Finding the Users Active Minutes/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

You are given the logs for users' actions on LeetCode, and an integer k.
The logs are represented by a 2D integer array logs where each logs[i] =
[IDi, timei] indicates that the user with IDi performed an action at the
minute timei.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Multiple users can perform actions simultaneously, and a single user can
perform multiple actions in the same minute.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

The user active minutes (UAM) for a given user is defined as the number
of unique minutes in which the user performed an action on LeetCode. A
minute can only be counted once, even if multiple actions occur during
it.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

You are to calculate a 1-indexed array answer of size k such that, for
each j (1 <= j <= k), answer[j] is the number of users whose UAM equals
j.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the array answer as described above.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> logs = [[0,5],[1,2],[0,2],[0,5],[1,3]], k = 5
  <strong>Output:</strong> [0,2,0,0,0]
  <strong>Explanation:</strong>
  The user with ID=0 performed actions at minutes 5, 2, and 5 again. Hence, they have a UAM of 2 (minute 5 is only counted once).
  The user with ID=1 performed actions at minutes 2 and 3. Hence, they have a UAM of 2.
  Since both users have a UAM of 2, answer[2] is 2, and the remaining answer[j] values are 0.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> logs = [[1,1],[2,2],[2,3]], k = 4
  <strong>Output:</strong> [1,1,0,0]
  <strong>Explanation:</strong>
  The user with ID=1 performed a single action at minute 1. Hence, they have a UAM of 1.
  The user with ID=2 performed actions at minutes 2 and 3. Hence, they have a UAM of 2.
  There is one user with a UAM of 1 and one with a UAM of 2.
  Hence, answer[1] = 1, answer[2] = 1, and the remaining values are 0.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= logs.length <= 104

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= IDi <= 109

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= timei <= 105

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

k is in the range [The maximum UAM for a user, 105].

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
