* [[https://leetcode.com/problems/longest-substring-of-all-vowels-in-order][1839.
Longest Substring Of All Vowels in Order]]
  :PROPERTIES:
  :CUSTOM_ID: longest-substring-of-all-vowels-in-order
  :END:
[[./solution/1800-1899/1839.Longest Substring Of All Vowels in Order/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

A string is considered beautiful if it satisfies the following
conditions:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

Each of the 5 English vowels ('a', 'e', 'i', 'o', 'u') must appear at
least once in it.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

The letters must be sorted in alphabetical order (i.e. all 'a's before
'e's, all 'e's before 'i's, etc.).

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

#+begin_html
  <p>
#+end_html

For example, strings "aeiou" and "aaaaaaeiiiioou" are considered
beautiful, but "uaeio", "aeoiu", and "aaaeeeooo" are not beautiful.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Given a string word consisting of English vowels, return the length of
the longest beautiful substring of word. If no such substring exists,
return 0.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

A substring is a contiguous sequence of characters in a string.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> word = &quot;aeiaaio<u>aaaaeiiiiouuu</u>ooaauuaeiu&quot;
  <strong>Output:</strong> 13
  <b>Explanation:</b> The longest beautiful substring in word is &quot;aaaaeiiiiouuu&quot; of length 13.</pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> word = &quot;aeeeiiiioooauuu<u>aeiou</u>&quot;
  <strong>Output:</strong> 5
  <b>Explanation:</b> The longest beautiful substring in word is &quot;aeiou&quot; of length 5.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> word = &quot;a&quot;
  <strong>Output:</strong> 0
  <b>Explanation:</b> There is no beautiful substring, so return 0.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= word.length <= 5 * 105

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

word consists of characters 'a', 'e', 'i', 'o', and 'u'.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
