* [[https://leetcode.com/problems/number-of-burgers-with-no-waste-of-ingredients][1276.
Number of Burgers with No Waste of Ingredients]]
  :PROPERTIES:
  :CUSTOM_ID: number-of-burgers-with-no-waste-of-ingredients
  :END:
[[./solution/1200-1299/1276.Number of Burgers with No Waste of Ingredients/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Given two integers tomatoSlices and cheeseSlices. The ingredients of
different burgers are as follows:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

Jumbo Burger: 4 tomato slices and 1 cheese slice.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Small Burger: 2 Tomato slices and 1 cheese slice.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

#+begin_html
  <p>
#+end_html

Return [total_jumbo, total_small] so that the number of remaining
tomatoSlices equal to 0 and the number of remaining cheeseSlices equal
to 0. If it is not possible to make the remaining tomatoSlices and
cheeseSlices equal to 0 return [].

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> tomatoSlices = 16, cheeseSlices = 7

  <strong>Output:</strong> [1,6]

  <strong>Explantion:</strong> To make one jumbo burger and 6 small burgers we need 4*1 + 2*6 = 16 tomato and 1 + 6 = 7 cheese. There will be no remaining ingredients.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> tomatoSlices = 17, cheeseSlices = 4

  <strong>Output:</strong> []

  <strong>Explantion:</strong> There will be no way to use all ingredients to make small and jumbo burgers.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> tomatoSlices = 4, cheeseSlices = 17

  <strong>Output:</strong> []

  <strong>Explantion:</strong> Making 1 jumbo burger there will be 16 cheese remaining and making 2 small burgers there will be 15 cheese remaining.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 4:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> tomatoSlices = 0, cheeseSlices = 0

  <strong>Output:</strong> [0,0]

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 5:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> tomatoSlices = 2, cheeseSlices = 1

  <strong>Output:</strong> [0,1]

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= tomatoSlices <= 10^7

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= cheeseSlices <= 10^7

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
