* [[https://leetcode-cn.com/problems/re-space-lcci][17.13. Re-Space]]
  :PROPERTIES:
  :CUSTOM_ID: re-space
  :END:
[[./lcci/17.13.Re-Space/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Oh, no! You have accidentally removed all spaces, punctuation, and
capitalization in a lengthy document. A sentence like "I reset the
computer. It still didn't boot!" became
"iresetthecomputeritstilldidntboot''. You'll deal with the punctuation
and capi­talization later; right now you need to re-insert the spaces.
Most of the words are in a dictionary but a few are not. Given a
dictionary (a list of strings) and the document (a string), design an
algorithm to unconcatenate the document in a way that minimizes the
number of unrecognized characters. Return the number of unrecognized
characters.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Note: This problem is slightly different from the original one in the
book.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input: </strong>

  dictionary = [&quot;looked&quot;,&quot;just&quot;,&quot;like&quot;,&quot;her&quot;,&quot;brother&quot;]

  sentence = &quot;jesslookedjustliketimherbrother&quot;

  <strong>Output: </strong> 7

  <strong>Explanation: </strong> After unconcatenating, we got &quot;<strong>jess</strong> looked just like <strong>tim</strong> her brother&quot;, which containing 7 unrecognized characters.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Note:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= len(sentence) <= 1000

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

The total number of characters in dictionary is less than or equal
to 150000.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

There are only lowercase letters in dictionary and sentence.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
