* [[https://leetcode.com/problems/path-with-minimum-effort][1631. Path
With Minimum Effort]]
  :PROPERTIES:
  :CUSTOM_ID: path-with-minimum-effort
  :END:
[[./solution/1600-1699/1631.Path With Minimum Effort/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

You are a hiker preparing for an upcoming hike. You are given heights, a
2D array of size rows x columns, where heights[row][col] represents the
height of cell (row, col). You are situated in the top-left cell,
(0, 0), and you hope to travel to the bottom-right cell, (rows-1,
columns-1) (i.e., 0-indexed). You can move up, down, left, or right, and
you wish to find a route that requires the minimum effort.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

A route's effort is the maximum absolute difference in heights between
two consecutive cells of the route.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the minimum effort required to travel from the top-left cell to
the bottom-right cell.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> heights = [[1,2,2],[3,8,2],[5,3,5]]
  <strong>Output:</strong> 2
  <strong>Explanation:</strong> The route of [1,3,5,3,5] has a maximum absolute difference of 2 in consecutive cells.
  This is better than the route of [1,2,2,2,5], where the maximum absolute difference is 3.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> heights = [[1,2,3],[3,8,4],[5,3,5]]
  <strong>Output:</strong> 1
  <strong>Explanation:</strong> The route of [1,2,3,4,5] has a maximum absolute difference of 1 in consecutive cells, which is better than route [1,3,5,3,5].
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> heights = [[1,2,1,1,1],[1,2,1,2,1],[1,2,1,2,1],[1,2,1,2,1],[1,1,1,2,1]]
  <strong>Output:</strong> 0
  <strong>Explanation:</strong> This route does not require any effort.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

rows == heights.length

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

columns == heights[i].length

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= rows, columns <= 100

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= heights[i][j] <= 106

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
