* [[https://leetcode.com/problems/open-the-lock][752. Open the Lock]]
  :PROPERTIES:
  :CUSTOM_ID: open-the-lock
  :END:
[[./solution/0700-0799/0752.Open the Lock/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

You have a lock in front of you with 4 circular wheels. Each wheel has
10 slots: '0', '1', '2', '3', '4', '5', '6', '7', '8', '9'. The wheels
can rotate freely and wrap around: for example we can turn '9' to be
'0', or '0' to be '9'. Each move consists of turning one wheel one slot.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

The lock initially starts at '0000', a string representing the state of
the 4 wheels.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

You are given a list of deadends dead ends, meaning if the lock displays
any of these codes, the wheels of the lock will stop turning and you
will be unable to open it.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Given a target representing the value of the wheels that will unlock the
lock, return the minimum total number of turns required to open the
lock, or -1 if it is impossible.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> deadends = [&quot;0201&quot;,&quot;0101&quot;,&quot;0102&quot;,&quot;1212&quot;,&quot;2002&quot;], target = &quot;0202&quot;
  <strong>Output:</strong> 6
  <strong>Explanation:</strong>
  A sequence of valid moves would be &quot;0000&quot; -&gt; &quot;1000&quot; -&gt; &quot;1100&quot; -&gt; &quot;1200&quot; -&gt; &quot;1201&quot; -&gt; &quot;1202&quot; -&gt; &quot;0202&quot;.
  Note that a sequence like &quot;0000&quot; -&gt; &quot;0001&quot; -&gt; &quot;0002&quot; -&gt; &quot;0102&quot; -&gt; &quot;0202&quot; would be invalid,
  because the wheels of the lock become stuck after the display becomes the dead end &quot;0102&quot;.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> deadends = [&quot;8888&quot;], target = &quot;0009&quot;
  <strong>Output:</strong> 1
  <strong>Explanation:</strong>
  We can turn the last wheel in reverse to move from &quot;0000&quot; -&gt; &quot;0009&quot;.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> deadends = [&quot;8887&quot;,&quot;8889&quot;,&quot;8878&quot;,&quot;8898&quot;,&quot;8788&quot;,&quot;8988&quot;,&quot;7888&quot;,&quot;9888&quot;], target = &quot;8888&quot;
  <strong>Output:</strong> -1
  Explanation:
  We can&#39;t reach the target without getting stuck.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 4:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> deadends = [&quot;0000&quot;], target = &quot;8888&quot;
  <strong>Output:</strong> -1
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= deadends.length <= 500

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

deadends[i].length == 4

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

target.length == 4

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

target will not be in the list deadends.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

target and deadends[i] consist of digits only.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
