* [[https://leetcode.com/problems/sum-root-to-leaf-numbers][129. Sum
Root to Leaf Numbers]]
  :PROPERTIES:
  :CUSTOM_ID: sum-root-to-leaf-numbers
  :END:
[[./solution/0100-0199/0129.Sum Root to Leaf Numbers/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

You are given the root of a binary tree containing digits from 0 to 9
only.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Each root-to-leaf path in the tree represents a number.

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

For example, the root-to-leaf path 1 -> 2 -> 3 represents the number
123.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

#+begin_html
  <p>
#+end_html

Return the total sum of all root-to-leaf numbers.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

A leaf node is a node with no children.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> root = [1,2,3]
  <strong>Output:</strong> 25
  <strong>Explanation:</strong>
  The root-to-leaf path <code>1-&gt;2</code> represents the number <code>12</code>.
  The root-to-leaf path <code>1-&gt;3</code> represents the number <code>13</code>.
  Therefore, sum = 12 + 13 = <code>25</code>.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> root = [4,9,0,5,1]
  <strong>Output:</strong> 1026
  <strong>Explanation:</strong>
  The root-to-leaf path <code>4-&gt;9-&gt;5</code> represents the number 495.
  The root-to-leaf path <code>4-&gt;9-&gt;1</code> represents the number 491.
  The root-to-leaf path <code>4-&gt;0</code> represents the number 40.
  Therefore, sum = 495 + 491 + 40 = <code>1026</code>.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

The number of nodes in the tree is in the range [1, 1000].

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= Node.val <= 9

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

The depth of the tree will not exceed 10.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
