* [[https://leetcode.com/problems/minimum-cost-to-connect-two-groups-of-points][1595.
Minimum Cost to Connect Two Groups of Points]]
  :PROPERTIES:
  :CUSTOM_ID: minimum-cost-to-connect-two-groups-of-points
  :END:
[[./solution/1500-1599/1595.Minimum Cost to Connect Two Groups of Points/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

You are given two groups of points where the first group has size1
points, the second group has size2 points, and size1 >= size2.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

The cost of the connection between any two points are given in an size1
x size2 matrix where cost[i][j] is the cost of connecting point i of the
first group and point j of the second group. The groups are connected if
each point in both groups is connected to one or more points in the
opposite group. In other words, each point in the first group must be
connected to at least one point in the second group, and each point in
the second group must be connected to at least one point in the first
group.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the minimum cost it takes to connect the two groups.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> cost = [[15, 96], [36, 2]]
  <strong>Output:</strong> 17
  <strong>Explanation</strong>: The optimal way of connecting the groups is:
  1--A
  2--B
  This results in a total cost of 17.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> cost = [[1, 3, 5], [4, 1, 1], [1, 5, 3]]
  <strong>Output:</strong> 4
  <strong>Explanation</strong>: The optimal way of connecting the groups is:
  1--A
  2--B
  2--C
  3--A
  This results in a total cost of 4.
  Note that there are multiple points connected to point 2 in the first group and point A in the second group. This does not matter as there is no limit to the number of points that can be connected. We only care about the minimum total cost.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> cost = [[2, 5, 1], [3, 4, 7], [8, 1, 2], [6, 2, 4], [3, 8, 8]]
  <strong>Output:</strong> 10
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

size1 == cost.length

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

size2 == cost[i].length

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= size1, size2 <= 12

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

size1 >= size2

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= cost[i][j] <= 100

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
