* [[https://leetcode-cn.com/problems/pattern-matching-lcci][16.18.
Pattern Matching]]
  :PROPERTIES:
  :CUSTOM_ID: pattern-matching
  :END:
[[./lcci/16.18.Pattern Matching/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

You are given two strings, pattern and value. The pattern string
consists of just the letters a and b, describing a pattern within a
string. For example, the string catcatgocatgo matches the pattern aabab
(where cat is a and go is b). It also matches patterns like a, ab, and
b. Write a method to determine if value matches pattern. a and b cannot
be the same string.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input: </strong> pattern = &quot;abba&quot;, value = &quot;dogcatcatdog&quot;

  <strong>Output: </strong> true

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input: </strong> pattern = &quot;abba&quot;, value = &quot;dogcatcatfish&quot;

  <strong>Output: </strong> false

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input: </strong> pattern = &quot;aaaa&quot;, value = &quot;dogcatcatdog&quot;

  <strong>Output: </strong> false

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 4:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input: </strong> pattern = &quot;abba&quot;, value = &quot;dogdogdogdog&quot;

  <strong>Output: </strong> true

  <strong>Explanation: </strong> &quot;a&quot;=&quot;dogdog&quot;,b=&quot;&quot;，vice versa.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Note:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= len(pattern) <= 1000

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= len(value) <= 1000

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

pattern only contains "a" and "b", value only contains lowercase
letters.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
