* [[https://leetcode.com/problems/last-moment-before-all-ants-fall-out-of-a-plank][1503.
Last Moment Before All Ants Fall Out of a Plank]]
  :PROPERTIES:
  :CUSTOM_ID: last-moment-before-all-ants-fall-out-of-a-plank
  :END:
[[./solution/1500-1599/1503.Last Moment Before All Ants Fall Out of a Plank/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

We have a wooden plank of the length n units. Some ants are walking on
the plank, each ant moves with speed 1 unit per second. Some of the ants
move to the left, the other move to the right.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

When two ants moving in two different directions meet at some point,
they change their directions and continue moving again. Assume changing
directions doesn't take any additional time.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

When an ant reaches one end of the plank at a time t, it falls out of
the plank imediately.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Given an integer n and two integer arrays left and right, the positions
of the ants moving to the left and the right. Return the moment when the
last ant(s) fall out of the plank.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> n = 4, left = [4,3], right = [0,1]

  <strong>Output:</strong> 4

  <strong>Explanation:</strong> In the image above:

  -The ant at index 0 is named A and going to the right.

  -The ant at index 1 is named B and going to the right.

  -The ant at index 3 is named C and going to the left.

  -The ant at index 4 is named D and going to the left.

  Note that the last moment when an ant was on the plank is t = 4 second, after that it falls imediately out of the plank. (i.e. We can say that at t = 4.0000000001, there is no ants on the plank).

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> n = 7, left = [], right = [0,1,2,3,4,5,6,7]

  <strong>Output:</strong> 7

  <strong>Explanation:</strong> All ants are going to the right, the ant at index 0 needs 7 seconds to fall.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> n = 7, left = [0,1,2,3,4,5,6,7], right = []

  <strong>Output:</strong> 7

  <strong>Explanation:</strong> All ants are going to the left, the ant at index 7 needs 7 seconds to fall.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 4:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> n = 9, left = [5], right = [4]

  <strong>Output:</strong> 5

  <strong>Explanation:</strong> At t = 1 second, both ants will be at the same intial position but with different direction.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 5:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input:</strong> n = 6, left = [6], right = [0]

  <strong>Output:</strong> 6

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= n <= 10^4

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= left.length <= n + 1

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= left[i] <= n

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= right.length <= n + 1

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= right[i] <= n

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= left.length + right.length <= n + 1

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

All values of left and right are unique, and each value can appear only
in one of the two arrays.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
