* [[https://leetcode.com/problems/reformat-phone-number][1694. Reformat
Phone Number]]
  :PROPERTIES:
  :CUSTOM_ID: reformat-phone-number
  :END:
[[./solution/1600-1699/1694.Reformat Phone Number/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

You are given a phone number as a string number. number consists of
digits, spaces ' ', and/or dashes '-'.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

You would like to reformat the phone number in a certain manner.
Firstly, remove all spaces and dashes. Then, group the digits from left
to right into blocks of length 3 until there are 4 or fewer digits. The
final digits are then grouped as follows:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

2 digits: A single block of length 2.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

3 digits: A single block of length 3.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

4 digits: Two blocks of length 2 each.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

#+begin_html
  <p>
#+end_html

The blocks are then joined by dashes. Notice that the reformatting
process should never produce any blocks of length 1 and produce at most
two blocks of length 2.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the phone number after formatting.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> number = &quot;1-23-45 6&quot;
  <strong>Output:</strong> &quot;123-456&quot;
  <strong>Explanation:</strong> The digits are &quot;123456&quot;.
  Step 1: There are more than 4 digits, so group the next 3 digits. The 1st block is &quot;123&quot;.
  Step 2: There are 3 digits remaining, so put them in a single block of length 3. The 2nd block is &quot;456&quot;.
  Joining the blocks gives &quot;123-456&quot;.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> number = &quot;123 4-567&quot;
  <strong>Output:</strong> &quot;123-45-67&quot;
  <strong>Explanation: </strong>The digits are &quot;1234567&quot;.
  Step 1: There are more than 4 digits, so group the next 3 digits. The 1st block is &quot;123&quot;.
  Step 2: There are 4 digits left, so split them into two blocks of length 2. The blocks are &quot;45&quot; and &quot;67&quot;.
  Joining the blocks gives &quot;123-45-67&quot;.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> number = &quot;123 4-5678&quot;
  <strong>Output:</strong> &quot;123-456-78&quot;
  <strong>Explanation:</strong> The digits are &quot;12345678&quot;.
  Step 1: The 1st block is &quot;123&quot;.
  Step 2: The 2nd block is &quot;456&quot;.
  Step 3: There are 2 digits left, so put them in a single block of length 2. The 3rd block is &quot;78&quot;.
  Joining the blocks gives &quot;123-456-78&quot;.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 4:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> number = &quot;12&quot;
  <strong>Output:</strong> &quot;12&quot;
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 5:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> number = &quot;--17-5 229 35-39475 &quot;
  <strong>Output:</strong> &quot;175-229-353-94-75&quot;
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

2 <= number.length <= 100

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

number consists of digits and the characters '-' and ' '.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

There are at least two digits in number.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
