* [[https://leetcode.com/problems/break-a-palindrome][1328. Break a
Palindrome]]
  :PROPERTIES:
  :CUSTOM_ID: break-a-palindrome
  :END:
[[./solution/1300-1399/1328.Break a Palindrome/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Given a palindromic string of lowercase English letters palindrome,
replace exactly one character with any lowercase English letter so that
the resulting string is not a palindrome and that it is the
lexicographically smallest one possible.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the resulting string. If there is no way to replace a character
to make it not a palindrome, return an empty string.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

A string a is lexicographically smaller than a string b (of the same
length) if in the first position where a and b differ, a has a character
strictly smaller than the corresponding character in b. For example,
"abcc" is lexicographically smaller than "abcd" because the first
position they differ is at the fourth character, and 'c' is smaller than
'd'.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> palindrome = &quot;abccba&quot;
  <strong>Output:</strong> &quot;aaccba&quot;
  <strong>Explanation:</strong> There are many ways to make &quot;abccba&quot; not a palindrome, such as &quot;<u>z</u>bccba&quot;, &quot;a<u>a</u>ccba&quot;, and &quot;ab<u>a</u>cba&quot;.
  Of all the ways, &quot;aaccba&quot; is the lexicographically smallest.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> palindrome = &quot;a&quot;
  <strong>Output:</strong> &quot;&quot;
  <strong>Explanation:</strong> There is no way to replace a single character to make &quot;a&quot; not a palindrome, so return an empty string.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> palindrome = &quot;aa&quot;
  <strong>Output:</strong> &quot;ab&quot;</pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 4:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> palindrome = &quot;aba&quot;
  <strong>Output:</strong> &quot;abb&quot;
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= palindrome.length <= 1000

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

palindrome consists of only lowercase English letters.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
