* [[https://leetcode.com/problems/change-minimum-characters-to-satisfy-one-of-three-conditions][1737.
Change Minimum Characters to Satisfy One of Three Conditions]]
  :PROPERTIES:
  :CUSTOM_ID: change-minimum-characters-to-satisfy-one-of-three-conditions
  :END:
[[./solution/1700-1799/1737.Change Minimum Characters to Satisfy One of Three Conditions/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

You are given two strings a and b that consist of lowercase letters. In
one operation, you can change any character in a or b to any lowercase
letter.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Your goal is to satisfy one of the following three conditions:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

Every letter in a is strictly less than every letter in b in the
alphabet.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Every letter in b is strictly less than every letter in a in the
alphabet.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Both a and b consist of only one distinct letter.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

#+begin_html
  <p>
#+end_html

Return the minimum number of operations needed to achieve your goal.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> a = &quot;aba&quot;, b = &quot;caa&quot;
  <strong>Output:</strong> 2
  <strong>Explanation:</strong> Consider the best way to make each condition true:
  1) Change b to &quot;ccc&quot; in 2 operations, then every letter in a is less than every letter in b.
  2) Change a to &quot;bbb&quot; and b to &quot;aaa&quot; in 3 operations, then every letter in b is less than every letter in a.
  3) Change a to &quot;aaa&quot; and b to &quot;aaa&quot; in 2 operations, then a and b consist of one distinct letter.
  The best way was done in 2 operations (either condition 1 or condition 3).
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> a = &quot;dabadd&quot;, b = &quot;cda&quot;
  <strong>Output:</strong> 3
  <strong>Explanation:</strong> The best way is to make condition 1 true by changing b to &quot;eee&quot;.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= a.length, b.length <= 105

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

a and b consist only of lowercase letters.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
