* [[https://leetcode.com/problems/new-21-game][837. New 21 Game]]
  :PROPERTIES:
  :CUSTOM_ID: new-21-game
  :END:
[[./solution/0800-0899/0837.New 21 Game/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Alice plays the following game, loosely based on the card game "21".

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Alice starts with 0 points, and draws numbers while she has less than K
points.  During each draw, she gains an integer number of points
randomly from the range [1, W], where W is an integer.  Each draw is
independent and the outcomes have equal probabilities.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Alice stops drawing numbers when she gets K or more points.  What is the
probability that she has N or less points?

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input: </strong>N = 10, K = 1, W = 10

  <strong>Output: </strong>1.00000

  <strong>Explanation: </strong> Alice gets a single card, then stops.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input: </strong>N = 6, K = 1, W = 10

  <strong>Output: </strong>0.60000

  <strong>Explanation: </strong> Alice gets a single card, then stops.

  In 6 out of W = 10 possibilities, she is at or below N = 6 points.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input: </strong>N = 21, K = 17, W = 10

  <strong>Output: </strong>0.73278</pre>
#+end_html

#+begin_html
  <p>
#+end_html

Note:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ol>
#+end_html

#+begin_html
  <li>
#+end_html

0 <= K <= N <= 10000

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= W <= 10000

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Answers will be accepted as correct if they are within 10^-5 of the
correct answer.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

The judging time limit has been reduced for this question.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ol>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
