* [[https://leetcode.com/problems/alert-using-same-key-card-three-or-more-times-in-a-one-hour-period][1604.
Alert Using Same Key-Card Three or More Times in a One Hour Period]]
  :PROPERTIES:
  :CUSTOM_ID: alert-using-same-key-card-three-or-more-times-in-a-one-hour-period
  :END:
[[./solution/1600-1699/1604.Alert Using Same Key-Card Three or More Times in a One Hour Period/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

LeetCode company workers use key-cards to unlock office doors. Each time
a worker uses their key-card, the security system saves the worker's
name and the time when it was used. The system emits an alert if any
worker uses the key-card three or more times in a one-hour period.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

You are given a list of strings keyName and keyTime where [keyName[i],
keyTime[i]] corresponds to a person's name and the time when their
key-card was used in a single day.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Access times are given in the 24-hour time format "HH:MM", such as
"23:51" and "09:49".

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return a list of unique worker names who received an alert for frequent
keycard use. Sort the names in ascending order alphabetically.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Notice that "10:00" - "11:00" is considered to be within a one-hour
period, while "22:51" - "23:52" is not considered to be within a
one-hour period.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> keyName = [&quot;daniel&quot;,&quot;daniel&quot;,&quot;daniel&quot;,&quot;luis&quot;,&quot;luis&quot;,&quot;luis&quot;,&quot;luis&quot;], keyTime = [&quot;10:00&quot;,&quot;10:40&quot;,&quot;11:00&quot;,&quot;09:00&quot;,&quot;11:00&quot;,&quot;13:00&quot;,&quot;15:00&quot;]
  <strong>Output:</strong> [&quot;daniel&quot;]
  <strong>Explanation:</strong> &quot;daniel&quot; used the keycard 3 times in a one-hour period (&quot;10:00&quot;,&quot;10:40&quot;, &quot;11:00&quot;).
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> keyName = [&quot;alice&quot;,&quot;alice&quot;,&quot;alice&quot;,&quot;bob&quot;,&quot;bob&quot;,&quot;bob&quot;,&quot;bob&quot;], keyTime = [&quot;12:01&quot;,&quot;12:00&quot;,&quot;18:00&quot;,&quot;21:00&quot;,&quot;21:20&quot;,&quot;21:30&quot;,&quot;23:00&quot;]
  <strong>Output:</strong> [&quot;bob&quot;]
  <strong>Explanation:</strong> &quot;bob&quot; used the keycard 3 times in a one-hour period (&quot;21:00&quot;,&quot;21:20&quot;, &quot;21:30&quot;).
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> keyName = [&quot;john&quot;,&quot;john&quot;,&quot;john&quot;], keyTime = [&quot;23:58&quot;,&quot;23:59&quot;,&quot;00:01&quot;]
  <strong>Output:</strong> []
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 4:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> keyName = [&quot;leslie&quot;,&quot;leslie&quot;,&quot;leslie&quot;,&quot;clare&quot;,&quot;clare&quot;,&quot;clare&quot;,&quot;clare&quot;], keyTime = [&quot;13:00&quot;,&quot;13:20&quot;,&quot;14:00&quot;,&quot;18:00&quot;,&quot;18:51&quot;,&quot;19:30&quot;,&quot;19:49&quot;]
  <strong>Output:</strong> [&quot;clare&quot;,&quot;leslie&quot;]
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= keyName.length, keyTime.length <= 105

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

keyName.length == keyTime.length

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

keyTime[i] is in the format "HH:MM".

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

[keyName[i], keyTime[i]] is unique.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= keyName[i].length <= 10

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

keyName[i] contains only lowercase English letters.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
