* [[https://leetcode.com/problems/replace-words][648. Replace Words]]
  :PROPERTIES:
  :CUSTOM_ID: replace-words
  :END:
[[./solution/0600-0699/0648.Replace Words/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

In English, we have a concept called root, which can be followed by some
other word to form another longer word - let's call this word successor.
For example, when the root "an" is followed by the
successor word "other", we can form a new word "another".

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Given a dictionary consisting of many roots and a sentence consisting of
words separated by spaces, replace all the successors in the sentence
with the root forming it. If a successor can be replaced by more than
one root, replace it with the root that has the shortest length.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the sentence after the replacement.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre><strong>Input:</strong> dictionary = ["cat","bat","rat"], sentence = "the cattle was rattled by the battery"
  <strong>Output:</strong> "the cat was rat by the bat"
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre><strong>Input:</strong> dictionary = ["a","b","c"], sentence = "aadsfasf absbs bbab cadsfafs"
  <strong>Output:</strong> "a a b c"
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre><strong>Input:</strong> dictionary = ["a", "aa", "aaa", "aaaa"], sentence = "a aa a aaaa aaa aaa aaa aaaaaa bbb baba ababa"
  <strong>Output:</strong> "a a a a a a a a bbb baba a"
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 4:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre><strong>Input:</strong> dictionary = ["catt","cat","bat","rat"], sentence = "the cattle was rattled by the battery"
  <strong>Output:</strong> "the cat was rat by the bat"
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 5:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre><strong>Input:</strong> dictionary = ["ac","ab"], sentence = "it is abnormal that this solution is accepted"
  <strong>Output:</strong> "it is ab that this solution is ac"
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= dictionary.length <= 1000

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= dictionary[i].length <= 100

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

dictionary[i] consists of only lower-case letters.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= sentence.length <= 10^6

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

sentence consists of only lower-case letters and spaces.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

The number of words in sentence is in the range [1, 1000]

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

The length of each word in sentence is in the range [1, 1000]

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

Each two consecutive words in sentence will be separated by exactly one
space.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

sentence does not have leading or trailing spaces.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
