* [[https://leetcode.com/problems/long-pressed-name][925. Long Pressed
Name]]
  :PROPERTIES:
  :CUSTOM_ID: long-pressed-name
  :END:
[[./solution/0900-0999/0925.Long Pressed Name/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Your friend is typing his name into a keyboard. Sometimes, when typing a
character c, the key might get long pressed, and the character will be
typed 1 or more times.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

You examine the typed characters of the keyboard. Return True if it is
possible that it was your friends name, with some characters (possibly
none) being long pressed.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> name = &quot;alex&quot;, typed = &quot;aaleex&quot;
  <strong>Output:</strong> true
  <strong>Explanation: </strong>&#39;a&#39; and &#39;e&#39; in &#39;alex&#39; were long pressed.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> name = &quot;saeed&quot;, typed = &quot;ssaaedd&quot;
  <strong>Output:</strong> false
  <strong>Explanation: </strong>&#39;e&#39; must have been pressed twice, but it wasn&#39;t in the typed output.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> name = &quot;leelee&quot;, typed = &quot;lleeelee&quot;
  <strong>Output:</strong> true
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 4:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> name = &quot;laiden&quot;, typed = &quot;laiden&quot;
  <strong>Output:</strong> true
  <strong>Explanation: </strong>It&#39;s not necessary to long press any character.
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= name.length <= 1000

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= typed.length <= 1000

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

name and typed contain only lowercase English letters.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
