* [[https://leetcode.com/problems/fair-candy-swap][888. Fair Candy
Swap]]
  :PROPERTIES:
  :CUSTOM_ID: fair-candy-swap
  :END:
[[./solution/0800-0899/0888.Fair Candy Swap/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Alice and Bob have candy bars of different sizes: A[i] is the size of
the i-th bar of candy that Alice has, and B[j] is the size of the j-th
bar of candy that Bob has.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Since they are friends, they would like to exchange one candy bar each
so that after the exchange, they both have the same total amount of
candy.  (The total amount of candy a person has is the sum of the sizes
of candy bars they have.)

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return an integer array ans where ans[0] is the size of the candy bar
that Alice must exchange, and ans[1] is the size of the candy bar that
Bob must exchange.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

If there are multiple answers, you may return any one of them.  It is
guaranteed an answer exists.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input: </strong>A = <span id="example-input-1-1">[1,1]</span>, B = <span id="example-input-1-2">[2,2]</span>

  <strong>Output: </strong><span id="example-output-1">[1,2]</span>

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 2:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input: </strong>A = <span id="example-input-2-1">[1,2]</span>, B = <span id="example-input-2-2">[2,3]</span>

  <strong>Output: </strong><span id="example-output-2">[1,2]</span>

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 3:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input: </strong>A = <span id="example-input-3-1">[2]</span>, B = <span id="example-input-3-2">[1,3]</span>

  <strong>Output: </strong><span id="example-output-3">[2,3]</span>

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 4:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Input: </strong>A = <span id="example-input-4-1">[1,2,5]</span>, B = <span id="example-input-4-2">[2,4]</span>

  <strong>Output: </strong><span id="example-output-4">[5,4]</span>

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Note:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= A.length <= 10000

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= B.length <= 10000

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= A[i] <= 100000

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= B[i] <= 100000

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

It is guaranteed that Alice and Bob have different total amounts
of candy.

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

It is guaranteed there exists an answer.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
