* [[https://leetcode.com/problems/minimum-swaps-to-make-sequences-increasing][801.
Minimum Swaps To Make Sequences Increasing]]
  :PROPERTIES:
  :CUSTOM_ID: minimum-swaps-to-make-sequences-increasing
  :END:
[[./solution/0800-0899/0801.Minimum Swaps To Make Sequences Increasing/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

We have two integer sequences A and B of the same non-zero length.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

We are allowed to swap elements A[i] and B[i].  Note that both elements
are in the same index position in their respective sequences.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

At the end of some number of swaps, A and B are both strictly
increasing.  (A sequence is strictly increasing if and only if A[0] <
A[1] < A[2] < ... < A[A.length - 1].)

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Given A and B, return the minimum number of swaps to make both sequences
strictly increasing.  It is guaranteed that the given input always makes
it possible.

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>

  <strong>Example:</strong>

  <strong>Input:</strong> A = [1,3,5,4], B = [1,2,3,7]

  <strong>Output:</strong> 1

  <strong>Explanation: </strong>

  Swap A[3] and B[3].  Then the sequences are:

  A = [1, 3, 5, 7] and B = [1, 2, 3, 4]

  which are both strictly increasing.

  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Note:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

A, B are arrays with the same length, and that length will be in the
range [1, 1000].

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

A[i], B[i] are integer values in the range [0, 2000].

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
