* [[https://leetcode.com/problems/count-substrings-that-differ-by-one-character][1638.
Count Substrings That Differ by One Character]]
  :PROPERTIES:
  :CUSTOM_ID: count-substrings-that-differ-by-one-character
  :END:
[[./solution/1600-1699/1638.Count Substrings That Differ by One Character/README.org][中文文档]]

** Description
   :PROPERTIES:
   :CUSTOM_ID: description
   :END:

#+begin_html
  <p>
#+end_html

Given two strings s and t, find the number of ways you can choose a
non-empty substring of s and replace a single character by a different
character such that the resulting substring is a substring of t. In
other words, find the number of substrings in s that differ from some
substring in t by exactly one character.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

For example, the underlined substrings in "computer" and "computation"
only differ by the 'e'/'a', so this is a valid way.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Return the number of substrings that satisfy the condition above.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

A substring is a contiguous sequence of characters within a string.

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Example 1:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> s = &quot;aba&quot;, t = &quot;baba&quot;
  <strong>Output:</strong> 6
  <strong>Explanation: </strong>The following are the pairs of substrings from s and t that differ by exactly 1 character:
  (&quot;<u>a</u>ba&quot;, &quot;<u>b</u>aba&quot;)
  (&quot;<u>a</u>ba&quot;, &quot;ba<u>b</u>a&quot;)
  (&quot;ab<u>a</u>&quot;, &quot;<u>b</u>aba&quot;)
  (&quot;ab<u>a</u>&quot;, &quot;ba<u>b</u>a&quot;)
  (&quot;a<u>b</u>a&quot;, &quot;b<u>a</u>ba&quot;)
  (&quot;a<u>b</u>a&quot;, &quot;bab<u>a</u>&quot;)
  The underlined portions are the substrings that are chosen from s and t.
  </pre>
#+end_html

​​Example 2:

#+begin_html
  <pre>
  <strong>Input:</strong> s = &quot;ab&quot;, t = &quot;bb&quot;
  <strong>Output:</strong> 3
  <strong>Explanation: </strong>The following are the pairs of substrings from s and t that differ by 1 character:
  (&quot;<u>a</u>b&quot;, &quot;<u>b</u>b&quot;)
  (&quot;<u>a</u>b&quot;, &quot;b<u>b</u>&quot;)
  (&quot;<u>ab</u>&quot;, &quot;<u>bb</u>&quot;)
  ​​​​The underlined portions are the substrings that are chosen from s and t.
  </pre>
#+end_html

Example 3:

#+begin_html
  <pre>
  <strong>Input:</strong> s = &quot;a&quot;, t = &quot;a&quot;
  <strong>Output:</strong> 0
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

Example 4:

#+begin_html
  </p>
#+end_html

#+begin_html
  <pre>
  <strong>Input:</strong> s = &quot;abe&quot;, t = &quot;bbc&quot;
  <strong>Output:</strong> 10
  </pre>
#+end_html

#+begin_html
  <p>
#+end_html

 

#+begin_html
  </p>
#+end_html

#+begin_html
  <p>
#+end_html

Constraints:

#+begin_html
  </p>
#+end_html

#+begin_html
  <ul>
#+end_html

#+begin_html
  <li>
#+end_html

1 <= s.length, t.length <= 100

#+begin_html
  </li>
#+end_html

#+begin_html
  <li>
#+end_html

s and t consist of lowercase English letters only.

#+begin_html
  </li>
#+end_html

#+begin_html
  </ul>
#+end_html

** Solutions
   :PROPERTIES:
   :CUSTOM_ID: solutions
   :END:

#+begin_html
  <!-- tabs:start -->
#+end_html

*** *Python3*
    :PROPERTIES:
    :CUSTOM_ID: python3
    :END:
#+begin_src python
#+end_src

*** *Java*
    :PROPERTIES:
    :CUSTOM_ID: java
    :END:
#+begin_src java
#+end_src

*** *...*
    :PROPERTIES:
    :CUSTOM_ID: section
    :END:
#+begin_example
#+end_example

#+begin_html
  <!-- tabs:end -->
#+end_html
